### ISSUE TITLE
iOS：课程播放页 - 学习过程打卡分享需求变更

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#10]
## [学习] - 点击某课程 - 课程播放页：

 - 当前 lesson播放结束时， 弹出打卡提示框  [如图](https://modao.cc/app/1e194398bfad04bb9e17cc11a331415a9ef4adbc ) 

- 在提示框上， 点击“继续学习下一课”按钮，自动跳转至下一个lesson的播放界面。

- 在提示框上， 点击“结束本次学习，打卡”按钮，跳转至朋友圈分享页面。

- 朋友圈分享页面上， 点击“发送”按钮，成功后返回APP并显示打卡成功弹窗 [如图](https://modao.cc/app/1e194398bfad04bb9e17cc11a331415a9ef4adbc#screen=s41AC6A0B711506076068852)。

- 打卡成功提示框上， 点击“我知道了”按钮，关闭提示框。

<br>
<br>

 查看交互, https://modao.cc/app/1e194398bfad04bb9e17cc11a331415a9ef4adbc 

 查看UI的切图和效果图, 
 [ftp://192.168.1.134/www/bstcine-ui/bsctine-ios](url)
 [ftp://192.168.1.134//www/bstcine-ui/bsctine-ui-v1](url)

**Comment by MaryLinker** [comment]
交互图点击链接https://modao.cc/app/527110cbae2b2e3530bdf2bb75292e9b359ac20c进行查看

**Comment by limingLiuBaBa** [comment]
新的打卡界面,及打卡分享界面.完成.

**Comment by limingLiuBaBa** [comment]
新版打卡界面,及打卡完成界面,完成
