### ISSUE TITLE
PC-后台管理: 课程课件-数据维护存在的误操作情况

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#107]
## 课件图片错误
 - 1：图片排序错误(如下排序{图片2：10s,图片1：0s)：`√`
   可能情况分析：
    （1）上传错误，先上图片2填写10s时间后，在上传图片1。
    （2）后台保存，保存数据进数据表时候发生错位。

<br>

 - 2：图片显示时间错误(如图片应该10秒位置切换，实际8秒切换)：`X`
   可能情况分析：
    （1）课件错误，老师提供时间错误
    （2）后台填写错误，填写时间错误
    （3）更改错误，如更换了音频，或者更改了图片导致内容和音频不对应

<br>

 - 3：图片错误: `X`
       可能情况分析：
      （1）上传导致错误,上传时候选择图片错误
      （2）更改图片导致错误,后期课件更改图片更改时候上传的是错误图片

<br>

  - 4：图片不显示: `√`
       可能情况分析：
      （1）上传导致错误,没有上传该图片，图片不存在
      （2）更改图片导致错误,图片新上传后，后台没有进行转义，系统获取到的是一个不存在的文件路径
      （3）网速问题

<br>

## 课件音频
 - 1：音频错误:`X`
       可能情况分析：
      （1）上传导致错误,上传错误音频。如果是APP端也可能是对该音频的时长维护数据错误导致

<br>

 - 2：音频不播放:  `√`
       可能情况分析：
      （1）该音频没有上传
      （2）该音频更改重新上传后没有进行转义
      （3）网速问题

**Comment by itwangxiang** [comment]
-图片：每个 media 下 image 数组
   - 时间约束
      - 第一张一定是：0s
      - 图片时间点不能重复
      - 图片时间点不能超过音频时长
   - 文件约束：图片文件路径一定是可访问的

**Comment by joelin109** [comment]
## 路径
PC-Admin:  系统管理 - 工具目录 - 校验数据
