### ISSUE TITLE
PC-购买与支付：用户购买查理和巧克力工厂课程无法分享

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#108]
该用户使用优惠券95折，50积分购买了查理和巧克力工厂课程之后无法分享课程得积分
用户名：howeverno

**Comment by daweilv** [comment]
Reason:
用户在购买完一笔订单后系统会自动创建一条未分享的分享记录，再次分享的时候复用记录，不会重新创建一条新的记录。2017-08-25之前的 t_sharelog 表中的 share_title、share_desc、share_link、share_imgUrl 均为 null ，提供给 app 的参数为空，导致分享失败
Solution:
删除异常历史数据，问题用户重新分享的时候新建一条记录即可
