### ISSUE TITLE
PC-Tool: 压缩音频、压缩图片、及图片加水印

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#114]
支持客户端压缩音频，图片。 及在图片上面加水印

**Comment by itwangxiang** [comment]
- 安装
   [imagemagick](https://www.imagemagick.org/script/download.php#windows)
   [ffmpeg](https://www.ffmpeg.org/download.html#build-windows)
   [cine-tool.zip](https://github.com/bstcine/cine.tool.go/files/1465472/cine-tool.zip)
- 运行
   - 解压 `cine-tool.zip` 
   - 将 `cine-tool.exe` 放在需要压缩并打水印的文件目录下运行

**Comment by zhuyichun** [comment]
压缩后的图片清晰度不够，要求比目前官网的图片清晰
