### ISSUE TITLE
安卓-购买与支付：课程详情页里面的图片需要不加 http://www.bstcine.com前缀也能正常显示

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#117]
bug描述：编辑课程详情页的内容时，里面的图片一定要加上 http://www.bstcine.com 前缀才能正常显示，这是不合理的，需要不加前缀也能正常显示。
bug提出人：David

![image](https://user-images.githubusercontent.com/32290407/32357963-75a69adc-c07c-11e7-869e-337a5f7858e4.png)

**Comment by itwangxiang** [comment]
## Solution:
- 设置 WebView `loadDataWithBaseURL(baseUrl,...)`

**Comment by itwangxiang** [comment]
@MaryLinker ？

**Comment by MaryLinker** [comment]
@jerry 反馈测试结果
