### ISSUE TITLE
安卓-商城：未登录情况下分享课程详情页提示语有误

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#118]
在未登录的情况下，在商城里面的任意一门课程详情页面，点击右上角的分享按钮，提示语为“该课程无法分享”这是不合理的，具体提示语待定
![image](https://user-images.githubusercontent.com/32290407/32368713-abf5da5e-c0c1-11e7-9caa-cf5a69f55cd4.png)
![image](https://user-images.githubusercontent.com/32290407/32368777-ea221f04-c0c1-11e7-8b7c-976d4128637a.png)

**Comment by itwangxiang** [comment]
该 API 已经支持未登录分享，确认关闭
