### ISSUE TITLE
pc-购买与支付: 微信&手机浏览器 -购买课程支付成功后的页面改进

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#12]
需求未定，优先级不高

**Comment by daweilv** [comment]
这个分享交互没有考虑到各终端情况，建议参考 Web 端打卡分享的处理方式。
打卡分享的交互分为 3 种情况处理：
1. PC 端
显示二维码，提示“打卡流程：1.微信扫描二维码  2.分享到朋友圈”；
2. 手机浏览器
显示二维码，提示“打卡流程：1.截图  2. 微信扫一扫，点击右上角“相册”，选择二维码图片”；
3. 微信内置浏览器
显示 button，点击后显示灰色蒙版 + “请点击右上角 ...，选择分享到朋友圈”；

**Comment by daweilv** [comment]
另外，建议 Android&iOS 购买后成功应该一并设计处理

**Comment by MaryLinker** [comment]
鉴于以后将取消购买后分享可得5%的积分得需求，此需求关闭
