### ISSUE TITLE
iOS-下载：课程内容的本地自动更新下载 - V2的代码结构设计

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#120]
## V2的结构设计
- 添加的Logic 文件
- 每个Logic 的 public 方法

```
先不包含具体实现代码， 大家确认后再继续coding
```

**Comment by YinZhenJob** [comment]
1. 更新数据管理：UpdateDataLogic
   1. 获取本地下载数据 Lesson 信息；
   2. 获取网络最新数据 Lesson 信息；
   3. 更新本地数据 Lesson 信息；
   4. 移除本地数据以及文件 Lesson 信息；
2. 更新数据比较方法（更新标记、删除标记）：UpdateCompareLogic
   1. 比较 Lesson 的方法；
   2. 比较 Media  的方法；
   3. 比较 Image  的方法；
3. 更新限制条件管理：UpdateRequirement
   1. 是否有本地下载数据，没有则退出
4. 更新业务管理：UpdateManager
5. 更新 Lesson 完成度的监控：UpdateSupervise

**Comment by joelin109** [comment]
## Question
- 文件命名规则：BC***
- 那些func是提供给UI层(iphone)调用？

**Comment by YinZhenJob** [comment]
流程图所示
![Uploading 屏幕快照 2017-11-07 09.56.32.png…]()

**Comment by YinZhenJob** [comment]
![update](https://user-images.githubusercontent.com/23608794/32474585-32ea5984-c3a8-11e7-8e80-cab4fa4c5eff.jpg)
