### ISSUE TITLE
PC: 部分用户高考全国卷课程无法学习

### ISSUE THREAD

**Issue by daweilv** [bstcine/cine-tasklist#121]
原课程A被拆分成了课程A和课程B，部分用户课程A的学习记录为课程B的一个节点，api在请求的时候根据历史记录的节点id找到课程B，而该用户只开通了课程A，课程B的资源则打不开。

**Comment by joelin109** [comment]
## Reason
- ？

**Comment by joelin109** [comment]
## Solution
- ？
