### ISSUE TITLE
H5-个人设置: 我的优惠券- 显示优惠券信息，与app类似

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#122]
用户领取优惠券后，只能在app的“我的”里面显示，但在pc，网页端都无法查看，烦请看下是否能实现pc，app都能查看到同样的内容，

- From Willing

重复issue， #340

**Comment by Anawangqi** [comment]
1. 我的-我的优惠券- 手机版
![6wap_ _](https://user-images.githubusercontent.com/32318334/37825515-16395126-2ecb-11e8-968c-86b0f8f1b291.png)

2. 我的-我的优惠券- 
PC版
![10 _](https://user-images.githubusercontent.com/32318334/37825516-16789e94-2ecb-11e8-9782-184ca840283a.png)
