### ISSUE TITLE
PC-邮件提醒: 销售报表每日邮件推送

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#123]
## 销售统计
- 统计数据中去掉“免费开通”“分享开通”“合作学校”“线下学生”这几类开通方式，然后在剩下的数据中只统计“实付金额 >= 1.00”的记录。

- 销量和金额数据请加上千分符

<br>

- 格式如下：
![screen shot 2017-11-07 at 2 47 37 pm](https://user-images.githubusercontent.com/23466882/32480630-5db32720-c355-11e7-9b55-4b6cc68b1737.png)

```
数据库添加一个字段：统计时显示排序字段
```

**Comment by joelin109** [comment]
![screen shot 2017-11-07 at 2 47 37 pm](https://user-images.githubusercontent.com/23466882/32480630-5db32720-c355-11e7-9b55-4b6cc68b1737.png)

**Comment by iott** [comment]
1.产品小计的意思不太明白
2.每日什么时间点发送邮件通知

**Comment by iott** [comment]
### 格式示例
![default](https://user-images.githubusercontent.com/12130164/32766554-7df07768-c94a-11e7-831d-63689952f5f7.jpg)

**Comment by joelin109** [comment]
## Solution
- ？
