### ISSUE TITLE
安卓-学习系统：拖动播放进度条，按下暂停键，视频没有暂停

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#126]
重现步骤：
1.在我的学习页面点击《one fish two fish red fish blue fish》课程进入目录页面；
2.点击lesson1 进入课程播放界面；
3.拖动播放进度条，视频正在加载时，按下暂停键；
此时，视频没有暂停，这是不合理的，应该暂停播放视频。

**Comment by itwangxiang** [comment]
华为低版本设备原因
