### ISSUE TITLE
app-测试用例：APP每个页面的测试用例的文档

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#128]
## 1. 学习（学习广场）
-  已登录
- [ ] 1.a.1. 有网络，显示已购课程列表,  需要正常显示已学天数和学习进度, 课程排序正常
- [ ] 1.a.2. 无网络,  显示最近一次的查询信息, 下拉页面提示“请检查网络状态”
- [ ] 1.a.3. 无网络,  如果第一次点击`课程`,  提示“请检查网络状态”

<br>

- 未登录
- [ ]  1.b. 只显示免费课程列表 

<br>

 ### 1. 1 课程Chapter目录  
- 有网络 - `是否登录情况一样`
- [ ]  1.1.a.1. 页面初始化，目录是展开的。当前进度的Lesson显示在最上面
- [ ]  1.1.a.2.  没有Media的Lesson， 没有对应的`下载`按钮
- [ ]  1.1.a.3.  点击没有Media的Lesson， 显示相应的信息或有相应的提示

<br>

- 无网络 
- [ ]  1.1.b.1. 没有下载过的Lesson应该显示灰的， 无法点击
- [ ]  1.1.b.2. 下载过的Lesson应该正常显示， 点击进入Lesson播放页

<br>

 ### 1. 2  Lesson播放页面
- 有网络 
- [ ]  1.2.a.1. 。。。 

<br>

<br>

**Comment by MaryLinker** [comment]
- 1. 学习（学习广场）
   - 1.1 未登录
     - 1.1.1 有网络
        - 显示免费课程列表；     
        - 已学天数为0，学习进度为还没开始学哦
        - 点击课程可进入对应课程播放界面
        - 下拉可刷新页面     无网络情况下提示“获取失败，请检查网络状态”
     - 1.1.2 无网络

  - 1.2 已登录
     - 显示免费课程和已购课程列表
     - 点击课程可进入对应课程播放界面
     - 检查课程的已学天数和学习进度是否正确
     - 有网络情况下可下拉刷新页面；无网络情况下提示“获取失败，请检查网络状态”
- 2. 商城
   - 2.1 未登录
     - 点击课程搜索可进入搜索页面
     - 检查课程价格、课程名称和课程图标是否正确
     - 点击课程可进入对应课程详情页
   - 2.2 已登录
     - 点击课程搜索可进入搜索页面
     - 检查课程价格、课程名称和课程图标是否正确
     - 点击课程可进入对应课程详情页
     - 已购买的课程有已购买标签
     - 有网络情况下可下拉刷新页面；无网络情况下提示“网络断开啦！”

**Comment by zhuyichun** [comment]
## 1 学习（学习广场）
### 1.2 已登录
- 1.2.1 有网络
- [ ]  显示“每日一词”和已购课程列表
- [ ]  下拉页面可刷新页面
- [ ]  点击课程可进入对应课程目录界面
- [ ]  点击已下载课程目录，进入播放界面播放已下载的文件
- [ ]  点击未下载的课程目录播放网络文件
- [ ]  当账号被其它设备登录时，点击课程弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 1.2.2 无网络
- [ ]  显示免费课程和已购课程列表
- [ ]  下拉页面提示“获取失败，请检查网络状态”
- [ ]  点击课程进入课程目录界面，已下载的目录正常显示，未下载的目录置灰显示。
- [ ]  已下载的目录点击播放已下载的文件，未下载的目录置灰显示，不可点击。

**Comment by zhuyichun** [comment]
- 3 我的
- 3.1 未登录
- 3.1.1 有网络
- [ ]  输入正确的账号和密码点击登录可进入我的详情页面，输入错误的账号或密码点击登录提示“账号或密码错误”
- [ ]  点击“没有账号？立即注册”可进入账号注册页面
- [ ]  点击“忘记密码”可进入重置密码页面
- [ ]  点击右上角“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击《善恩英语软件许可及服务协议》和《善恩隐私政策》可进入相应的说明页面
- 3.1.2 无网络
- [ ]  输入账号和密码点击登录不可进入我的详情页面并提示“网络异常，请检查网络状态”
- [ ]  点击“注册”和“忘记密码”不可进入对应的页面并提示“网络异常，请检查网络状态”
- [ ]  点击右上角“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击《善恩英语软件许可及服务协议》和《善恩隐私政策》可进入相应的说明页面
- 3.2 已登录
- 3.2.1 有网络
- [ ]  我的头像、昵称、可用积分输、未领取积分数、优惠券数和待付款数显示正常
- [ ]  点击每个模块可进入相应的页面
- [ ]  点击退出弹出“您确定要退出吗？”提示框
点 [ ] 击取消-停留在我的页面；
点 [ ] 击确定-如果当前存在正在下载的课程则弹窗提醒“您有文件正在下载，确定要退出吗？”-点击立即退出进入我的未登录页面，点击暂不退出-停留在我的页面；如果没有正在下载的课程直接进入我的未登录页面
- [ ]  点击分享APP，就得积分进入微信朋友圈编辑页面，点击发表回到我的页面并弹出分享成功提示框
- [ ]  当账号被其它设备登录时，点击课程弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 3.2.2 无网络
- [ ]  我的头像、昵称、可用积分输、未领取积分数、优惠券数、待付款数和待分享数显示与有网络显示一致
- [ ]  点击我的学习、我的下载、关于我们均可进入相应的页面
- [ ]  点击退出弹出“您确定要退出吗？”提示框，点击取消停留在我的页面，点击确定进入我的未登录页面
- [ ]  点击我的头像、可用积分、未领取积分、优惠券、待付款、待分享和查看全部均不可进入对应页面且提示“网络异常，请检查网络状态”
- 4 个人信息页面
- 4.1 有网络
- [ ]  点击编辑进入个人信息设置页面
- [ ]  点击返回进入我的页面
- [ ]  当账号被其它设备登录时，点击编辑或返回弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 4.2 无网络
- [ ]  点击编辑不可进入个人信息设置页面且提示“网络异常，请检查网络状态”
- [ ]  点击进入我的页面
- 5 个人设置页面
- 5.1 有网络
- [ ]  头像、昵称、城市、年级和性别均可进行编辑，点击保存后编辑成功并回到我的页面
- [ ]  点击返回进入个人信息页面
- [ ]  当账号被其它设备登录时，点击保存或返回弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 5.2 无网络
- [ ]  头像、昵称、城市、年级和性别均可进行编辑，点击保存后提示“网络异常，请检查网络状态”
- [ ]  点击返回进入个人信息页面
- 6 积分明细
- 6.1 有网络
- [ ]  积分数、积分明细显示正常
- [ ]  点击积分规则可进入积分规则页面
- [ ]  点击返回进入我的页面
- [ ]  下拉页面可刷新页面
- [ ]  当账号被其它设备登录时，点击积分规则或返回弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 6.2 无网络
- [ ]  点击积分规则不可进入积分规则页面并提示“网络异常，请检查网络状态”
- [ ]  积分数、积分明细显示正常
- [ ]  下拉页面提示“获取失败，请检查网络状态”
- [ ]  点击返回进入我的页面
- 7 我的优惠券
- 7.1 有网络
- [ ]  点击未使用、已使用和已过期页面可查看对应优惠券信息
- [ ]  点击右上角“添加+”弹出优惠券码输入框-输入正确的优惠券码-点击确认之后可在对应的优惠券信息的页面进行查看
- [ ]  点击返回进入我的页面
- [ ]  当账号被其它设备登录时，点击添加或返回弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 7.2 无网络
- [ ]  点击未使用、已使用、已过期和添加+时提示“网络异常，请检查网络状态”
- [ ]  点击返回进入我的页面
- 8 我的订单
- 8.1 全部
- 8.1.1 有网络
- [ ]  该页面包括已完成、已取消、待付款和待分享的所有订单且价格、订单状态显示正常
- [ ]  点击已取消的订单可进入该订单详情页面；点击重新购买如果未购买该课程可进入结算中心页面，如果已购买该课程则提示用户“不能重复购买”
- [ ]  点击等待付款的订单可进入该订单详情页面；点击去支付如果未购买该课程可进入善恩收银台页面，如果已购买该课程则提示用户“不能重复购买”；点击取消订单弹出“您确定取消订单吗？”的弹窗，点击确定可使该订单变为已取消状态
- [ ]  点击已完成的订单可进入订单详情页面
- [ ]  点击待分享的订单可进入订单详情页面；点击分享得积分可进入微信朋友圈编辑页面，点击发表回到我的页面并弹出分享成功提示框，到我的页面-可用积分-积分明细-查看有没有获得实付金额5%的奖励
- [ ]  点击待付款和待分享可进入相对应的订单列表页面
- [ ]  点击返回可进入我的页面
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- [ ]  下拉页面可刷新页面
- 8.1.2 无网络
- [ ]  点击其他页面或刷新页面均提示“获取失败，请检查网络状态”
- 8.2 待付款
- 8.2.1 有网络
- [ ]  点击等待付款的订单可进入该订单详情页面；点击去支付如果未购买该课程可进入善恩收银台页面，如果已购买该课程则提示用户“不能重复购买”；点击取消订单弹出“您确定取消订单吗？”的弹窗，点击确定可使该订单变为已取消状态
- [ ]  点击全部和待分享可进入相对应的订单列表页面
- [ ]  点击返回可进入我的页面
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 8.2.2 无网络
- [ ]  点击其他页面或刷新页面均提示“获取失败，请检查网络状态”
- 8.3 待分享
- 8.2.1 有网络
- [ ]  点击待分享的订单可进入订单详情页面；点击分享得积分可进入微信朋友圈编辑页面，点击发表回到我的页面并弹出分享成功提示框，到我的页面-可用积分-积分明细-查看有没有获得实付金额5%的奖励
- [ ]  点击返回可进入我的页面
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 8.2.2 无网络
- [ ]  点击其他页面或刷新页面均提示“获取失败，请检查网络状态”
- 9 关于我们
- [ ]  点击返回可进入我的页面
- 10 我的下载
- 10.1 已下载
- [ ]  点击已下载的课程可进入该课程的已下载章节目录
- [ ]  点击返回可进入到我的页面
- [ ]  点击下载中或左滑可进入下载中的页面
- [ ]  当前页面全是已下载的课程
- 10.2 下载中
- 11.1 有网络
- [ ]  点击下载中的课程可进入该课程的下载章节列表
- [ ]  点击返回可进入到我的页面
- [ ]  点击已下载或右滑可进入下载中的页面
- [ ]  正在下载的课程处于下载中的状态，下载完的课程会从当前页面移除
- 11.1 无网络
- [ ]  点击下载中的课程可进入该课程的下载章节列表
- [ ]  点击返回可进入到我的页面
- [ ]  点击已下载或右滑可进入下载中的页面
- [ ]  正在下载的课程暂停下载，并提示“获取失败，请检查网络状态”
- 11 已下载章节目录
- [ ]  点击 lesson 可进入对应的视频播放界面
- [ ]  长按 lesson 或章节会弹出“您要删除已下载的文件么？”点击确定可删除对应的lesson 或章节，点击以后删除可取消删除
- 12 正在下载章节目录
- 12.1 有网络
- [ ]  在此页面中只有一个lesson处于正在下载状态，其他处于等待下载的状态
- [ ]  点击编辑-选中需要删除的lesson或点击全选-点击删除可删除对应lesson或点击取消-回到正在下载的页面
- [ ]  点击lesson上的“下载中”可暂停下载；点击lesson上的“已暂停”可开始下载；
- [ ]  已下载完的lesson会从当前页面移除
- [ ]  点击返回可进入到我的下载-下载中页面
- 12.2 无网络
- [ ]  所有正在下载的课程都暂停下载，并提示“获取失败，请检查网络状态”
- [ ]  点击编辑-选中需要删除的lesson或点击全选-点击删除可删除对应lesson或点击取消-回到正在下载的页面
- [ ]  点击返回可进入到我的下载-下载中页面
- 13 课程详情页
- 13.1 已登录
- [ ]  已购买
- [ ]  点击右上角分享按钮可进入微信朋友圈编辑界面，点击发表后返回至课程详情页并提示分享成功
- [ ]  点击返回可进入商城页面
- [ ]  未购买
- [ ]  点击右上角分享按钮可进入微信朋友圈编辑界面，点击发表后返回至课程详情页并提示分享成功
- [ ]  点击返回可进入商城页面
- [ ]  当账号被其它设备登录时，点击立即购买按钮会弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 13.2 未登录
- [ ]  点击右上角分享按钮弹出“请登录后分享”提示框，点击确定后进入账号登录界面
- [ ]  点击立即购买弹出“请登陆后购买”提示框，点击确定后进入账号登录界面
- [ ]  点击返回可进入商城页面
- 13.3 无网络
- [ ]  点击立即购买或分享提示“获取失败，请检查网络状态”
- 14 结算中心
- 14.1 有网络
- [ ]  点击可用积分-输入积分数-1积分可抵扣1元
- [ ]  点击优惠券-选择优惠券-返回至结算中心页面
- [ ]  点击提交订单进入善恩收银台页面
- [ ]  点击返回可进入课程详情页
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 14.2 无网络
- [ ]  点击提交订单或刷新页面提示“获取失败，请检查网络状态”
-15 善恩收银台页面
- 15.1 有网络
- [ ]  点击微信支付可跳转至微信端支付页面，如果支付成功会返回至APP的支付完成页面，如果支付失败会回到APP的善恩收银台页面并弹窗提示“支付失败”
- [ ]  点击支付宝支付可跳转至支付宝端支付页面，如果支付成功会返回至APP的支付完成页面，如果支付失败会回到APP的善恩收银台页面并弹窗提示“支付失败”
- [ ]  点击返回进入课程详情页页面
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 15.2 无网络
- [ ]  点击微信支付或支付宝支付提示“当前无网络，请检查后重试”
- [ ]  点击返回进入课程详情页页面
- 16 注册
- 16.1 有网络
- [ ]  点击“国家/地区”选择注册手机号所属地区-点击“请输入您的手机号”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个手机号”-点击确定（如果该手机号已注册弹窗提醒“该手机号已注册，请选择立即登录或忘记密码”-点击立即登录则进入登录界面；点击忘记密码则进入重置密码界面）-进入输入验证码页面
- [ ]  点击“我要用电子邮箱注册”进入邮箱快速注册页面-点击“请输入您的电子邮箱”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个邮箱号”-点击确定（如果该邮箱号已注册弹窗提醒“该邮箱号已注册，请选择立即登录或忘记密码”-点击立即登录则进入登录界面；点击忘记密码则进入重置密码界面）-进入输入验证码页面
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  如果“国家/地区”未选择则默认中国
- [ ]  如果输入空或错误的手机号则提示“输入正确的手机号”
- [ ]  点击返回进入登录界面
- [ ]  点击右上角“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击《善恩英语软件许可及服务协议》和《善恩隐私政策》可进入相应的说明页面
- 16.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
- 17 重置密码
- 17.1 有网络
- [ ]  点击“国家/地区”选择注册手机号所属地区-点击“请输入您的手机号”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个手机号”-点击确定（如果该手机号未注册弹窗提醒“用户不存在”-回到重置密码界面重复从第一步开始）-进入输入验证码页面
- [ ]  点击“我要用电子邮箱注册”进入邮箱快速注册页面-点击“请输入您的电子邮箱”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个邮箱号”-点击确定（如果该邮箱号未注册弹窗提醒“用户不存在”-回到重置密码界面重复从第一步开始）-进入输入验证码页面
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击返回进入登录界面
- 17.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
-18 填写验证码
- 18.1 有网络
- [ ] 输入正确的验证码-点击下一步-进入设置密码页面
- [ ] 输入错误的验证码-点击下一步-弹窗提示“验证码输入错误”-点击确定-重新输入验证码
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击返回进入登录界面
- [ ]  18.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
-19 设置密码
- 19.1 有网络
- [ ]  两次输入的密码一致则弹窗提醒“密码重置成功”-点击确定-回到登录界面
- [ ]  输入的密码不足6位或没有同时包含字母和数字则弹窗提醒“输入的密码需要是6位数同时包含字母和数字”-点击确定-重新输入密码
- [ ]  两次输入的密码不一致则弹窗提醒“两次输入的密码不一致”-点击确定-重新输入密码
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  点击返回进入登录界面
- 19.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
- 20 课程播放目录
- 20.1 有网络
- [ ]  点击任意lesson可播放相应的视频
- [ ]  点击lesson上的下载按钮可下载对应的lesson且下载按钮如果读取成功变为正在下载状态的按钮；如果未读取成功则下载按钮变为正在读取状态；点击下载中的按钮可以暂停下载且下载中的按钮变为暂停下载按钮
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 20.2 无网络
- [ ]  如果当前课程存在已下载的lesson，则已下载的lesson显示为可播放状态，未下载的均为不可播放状态
- [ ]  点击已下载的lesson可播放对应的lesson，点击未下载的lesson则提示“获取失败，请检查网络后重试”
- 21 播放界面
- 21.1 有网络
- [ ]  课程播放界面的标题要与lesson相对应
- [ ]  点击←/→可切换视频的下一节/上一节；暂停、全屏和目录按钮都可正常点击；拖动进度条时视频会随着进度条拖动地时间而变化；双击播放界面可切换视频的暂停/播放状态
- [ ]  点击播放界面阴影条上的“结束本次学习，立即打卡”可跳转至微信朋友圈编辑页面，点击发表回到我的页面并弹出打卡成功提示框，点击“我知道了”进入学习广场页面
- [ ]  一个lesson播放完成会弹出“学习过程打卡框”-点击“继续学习”会自动跳转到下一个lesson的播放界面；点击“结束本次学习，打卡”会跳转至微信朋友圈编辑页面，点击发表回到我的页面并弹出打卡成功提示框，点击“我知道了”进入学习广场页面
- 21.2 无网络
- [ ]  如果当前播放的lesson是已下载的课程则可以继续播放；如果是未下载的课程则提示用户“获取失败，请检查网络后重试”
- 22 课程搜索
- 22.1 有网络
- [ ]  输入关键词-点击搜索-如果关键词可以找到相对应的课程（如果关键词不符合则提示搜索无结果）会出现对应的课程列表-点击课程可进入对应课程详情页
- [ ]  点击返回进入商城页面
- 22.2 无网络
- [ ]  点击搜索提示“当前无网络，请检查后重试”

**Comment by zhuyichun** [comment]
## 10 我的下载
### 10.1 已下载
- [ ]  点击已下载的课程可进入该课程的已下载章节目录
- [ ]  点击返回可进入到我的页面
- [ ]  点击下载中或左滑可进入下载中的页面
- [ ]  当前页面全是已下载的课程
### 10.2 下载中
### 11.1 有网络
- [ ]  点击下载中的课程可进入该课程的下载章节列表
- [ ]  点击返回可进入到我的页面
- [ ]  点击已下载或右滑可进入下载中的页面
- [ ]  正在下载的课程处于下载中的状态，下载完的课程会从当前页面移除
### 11.1 无网络
- [ ]  点击下载中的课程可进入该课程的下载章节列表
- [ ]  点击返回可进入到我的页面
- [ ]  点击已下载或右滑可进入下载中的页面
- [ ]  正在下载的课程暂停下载，并提示“获取失败，请检查网络状态”
### 11 已下载章节目录
- [ ]  点击 lesson 可进入对应的视频播放界面
- [ ]  长按 lesson 或章节会弹出“您要删除已下载的文件么？”点击确定可删除对应的lesson 或章节，点击以后删除可取消删除
### 12 正在下载章节目录
### 12.1 有网络
- [ ]  在此页面中只有一个lesson处于正在下载状态，其他处于等待下载的状态
- [ ]  点击编辑-选中需要删除的lesson或点击全选-点击删除可删除对应lesson或点击取消-回到正在下载的页面
- [ ]  点击lesson上的“下载中”可暂停下载；点击lesson上的“已暂停”可开始下载；
- [ ]  已下载完的lesson会从当前页面移除
- [ ]  点击返回可进入到我的下载-下载中页面
### 12.2 无网络
- [ ]  所有正在下载的课程都暂停下载，并提示“获取失败，请检查网络状态”
- [ ]  点击编辑-选中需要删除的lesson或点击全选-点击删除可删除对应lesson或点击取消-回到正在下载的页面
- [ ]  点击返回可进入到我的下载-下载中页面

**Comment by zhuyichun** [comment]
- 16 注册
- 16.1 有网络
- [ ]  点击“国家/地区”选择注册手机号所属地区-点击“请输入您的手机号”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个手机号”-点击确定（如果该手机号已注册弹窗提醒“该手机号已注册，请选择立即登录或忘记密码”-点击立即登录则进入登录界面；点击忘记密码则进入重置密码界面）-进入输入验证码页面
- [ ]  点击“我要用电子邮箱注册”进入邮箱快速注册页面-点击“请输入您的电子邮箱”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个邮箱号”-点击确定（如果该邮箱号已注册弹窗提醒“该邮箱号已注册，请选择立即登录或忘记密码”-点击立即登录则进入登录界面；点击忘记密码则进入重置密码界面）-进入输入验证码页面
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  如果“国家/地区”未选择则默认中国
- [ ]  如果输入空或错误的手机号则提示“输入正确的手机号”
- [ ]  点击返回进入登录界面
- [ ]  点击右上角“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击《善恩英语软件许可及服务协议》和《善恩隐私政策》可进入相应的说明页面
- 16.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
- 17 重置密码
- 17.1 有网络
- [ ]  点击“国家/地区”选择注册手机号所属地区-点击“请输入您的手机号”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个手机号”-点击确定（如果该手机号未注册弹窗提醒“用户不存在”-回到重置密码界面重复从第一步开始）-进入输入验证码页面
- [ ]  点击“我要用电子邮箱注册”进入邮箱快速注册页面-点击“请输入您的电子邮箱”-输入需要注册的手机号-点击下一步-弹出“我们将发送验证码到这个邮箱号”-点击确定（如果该邮箱号未注册弹窗提醒“用户不存在”-回到重置密码界面重复从第一步开始）-进入输入验证码页面
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击返回进入登录界面
- 17.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
-18 填写验证码
- 18.1 有网络
- [ ] 输入正确的验证码-点击下一步-进入设置密码页面
- [ ] 输入错误的验证码-点击下一步-弹窗提示“验证码输入错误”-点击确定-重新输入验证码
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击返回进入登录界面
- [ ]  18.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
-19 设置密码
- 19.1 有网络
- [ ]  两次输入的密码一致则弹窗提醒“密码重置成功”-点击确定-回到登录界面
- [ ]  输入的密码不足6位或没有同时包含字母和数字则弹窗提醒“输入的密码需要是6位数同时包含字母和数字”-点击确定-重新输入密码
- [ ]  两次输入的密码不一致则弹窗提醒“两次输入的密码不一致”-点击确定-重新输入密码
- [ ]  点击“帮助”弹出“如果您遇到任何使用问题，请联络管理员咨询 BSTCINE01”
- [ ]  点击“已有账号？点击登录”进入登录界面
- [ ]  点击返回进入登录界面
- 19.2 无网络
- [ ]  点击下一步提示“当前无网络，请检查后重试”
- 20 课程播放目录
- 20.1 有网络
- [ ]  点击任意lesson可播放相应的视频
- [ ]  点击lesson上的下载按钮可下载对应的lesson且下载按钮如果读取成功变为正在下载状态的按钮；如果未读取成功则下载按钮变为正在读取状态；点击下载中的按钮可以暂停下载且下载中的按钮变为暂停下载按钮
- [ ]  当账号被其它设备登录时，弹出提示框“你的账号已经被别的设备登录，请检查确认后重试”，点击确定后跳转至我的未登录页面
- 20.2 无网络
- [ ]  如果当前课程存在已下载的lesson，则已下载的lesson显示为可播放状态，未下载的均为不可播放状态
- [ ]  点击已下载的lesson可播放对应的lesson，点击未下载的lesson则提示“获取失败，请检查网络后重试”
- 21 播放界面
- 21.1 有网络
- [ ]  课程播放界面的标题要与lesson相对应
- [ ]  点击←/→可切换视频的下一节/上一节；暂停、全屏和目录按钮都可正常点击；拖动进度条时视频会随着进度条拖动地时间而变化；双击播放界面可切换视频的暂停/播放状态
- [ ]  点击播放界面阴影条上的“结束本次学习，立即打卡”可跳转至微信朋友圈编辑页面，点击发表回到我的页面并弹出打卡成功提示框，点击“我知道了”进入学习广场页面
- [ ]  一个lesson播放完成会弹出“学习过程打卡框”-点击“继续学习”会自动跳转到下一个lesson的播放界面；点击“结束本次学习，打卡”会跳转至微信朋友圈编辑页面，点击发表回到我的页面并弹出打卡成功提示框，点击“我知道了”进入学习广场页面
- 21.2 无网络
- [ ]  如果当前播放的lesson是已下载的课程则可以继续播放；如果是未下载的课程则提示用户“获取失败，请检查网络后重试”
- 22 课程搜索
- 22.1 有网络
- [ ]  输入关键词-点击搜索-如果关键词可以找到相对应的课程（如果关键词不符合则提示搜索无结果）会出现对应的课程列表-点击课程可进入对应课程详情页
- [ ]  点击返回进入商城页面
- 22.2 无网络
- [ ]  点击搜索提示“当前无网络，请检查后重试”

**Comment by zhuyichun** [comment]
更新升级：
覆盖安装

**Comment by zhuyichun** [comment]
# 私塾模块
## 步骤一：登录老师账号，导入习题。
```
习题要求：
        主观题：5道主观题标识为私塾（其中4道需要批改）、5道主观题普通。
        客观题：5道选择私塾。5道普通选择题
习题题目数：10题
```
## 步骤二：给私塾学生分配任务-纳尼亚lesson1
### case 1：私塾学生账号登录-如：ssJerry
步骤1：进入我的学习。

- [ ]  1.1.1：本周作业任务显示列表有“纳尼亚1 Chapter 17/Lesson 36习题”和“纳尼亚1 Chapter 17/Lesson 36”视频任务。
 - [ ]  1.1.2：点击任务跳转正确

步骤2：点击“纳尼亚1 Chapter 17/Lesson 36习题”进入习题，别做题、别点击提交。

 - [ ]  1.2.1：查看试题题目是否为5道私塾主观题和5道私塾选择题

步骤3：退出步骤2，修改私塾题题干，并导入

步骤4：登录私塾学生“ssjerry”进入我的学习，点击“纳尼亚1 Chapter 17/Lesson 36习题”进入习题

 - [ ]  1.4.1：查看试题题目是否为5道私塾主观题和5道私塾选择题，且题干为修改后的题目。

步骤5：完成非必须批改的那道主观题，完成后点击“提交答案”按钮。

 - [ ]  1.5.1：检查弹出框提示文字：剩余多少题、哪些题目未完成。查看提示是否正确。

步骤6：点击弹出框“确定”按钮，提交。

 - [ ]  1.6.1：页面自动刷新

步骤7： 批改状态 
#### case 1：未批改
 - [ ]  1.7.1：非必须批改题目，答案正确灰色显示默认解析和得分
 - [ ]  1.7.2：非必须批改题目，答案错误红色色显示默认并提示错误
 - [ ]  1.7.3：必须批改题目，仅仅显示学生答题.

####  case 2：保存批改
 - [ ]  1.7.4：非必须批改题目，答案正确灰色显示默认解析和得分
 - [ ]  1.7.5：非必须批改题目，答案错误红色色显示默认并提示错误
 - [ ]  1.7.6：必须批改题目，仅仅显示学生答题.
####  case3 ：已批改
 - [ ]  1.7.7：答案正确显示得分、并灰色显示老师解答，无解答显示默认解析。
 - [ ]  1.7.8：答案错误提示错误并红色显示老师解答，无解答显示默认解析。




## 步骤三：老师登录批改


## 步骤四：学生登录批改
### case 2：已经开通“纳尼亚精读课程”的普通学生账号登录-如：jerry_test
步骤1：点击进入纳尼亚精读课程学习lesson1,打开测试tag.
 - [ ]  2.1.1：查看试题题目是否为5道非私塾选择题
