### ISSUE TITLE
iOS-购买与支付:  添加内购功能

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#14]

**Comment by AaronLiDangkun** [comment]
ios添加内购功能描述：1.在商城界面，展示可用于内购的课程。当用户点击购买按钮，可内购课程会弹出苹果用于内购的弹窗，执行内购流程。2.当用户通过内购方式购买了课件，用户可以在学习广场看到购买成功的课程，并正常的播放课程
