### ISSUE TITLE
IOS：优惠券添加无法点击进去选择优惠券页

### ISSUE THREAD

**Issue by daweilv** [bstcine/cine-tasklist#142]
优惠券添加后，但是使用的时候没有任何提示信息，就是用不了
---小助手
![wechatimg1659](https://user-images.githubusercontent.com/7405300/32685650-24f4e3fc-c65b-11e7-9fd9-3f44f818a5e9.jpeg)

**Comment by itwangxiang** [comment]
不是安卓问题

**Comment by joelin109** [comment]
## Reason
- ？

## Solution：
- ？

**Comment by joelin109** [comment]
在iOS 2.0.1版会提示 ‘该优惠券已失效’
