### ISSUE TITLE
PC：未支付订单里的课程名称过长时，会与应付金额重叠

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#147]
![image](https://user-images.githubusercontent.com/32290407/32717516-e0fad972-c894-11e7-8a55-c751391d47fe.png)

**Comment by zhuyichun** [comment]
- Solution：
限制显示2行，超出部分省略号显示

**Comment by zhuyichun** [comment]
已经更改
![3 pic](https://user-images.githubusercontent.com/20130469/32768914-c16b8fd2-c954-11e7-9dce-b4324633a078.jpg)
