### ISSUE TITLE
iOS-学习系统-课程播放界面控制操作

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#15]
1.暂停按钮、播放按钮、进度条游标尺寸调大（由ana提供UI）；
2.点击暂停按钮后界面上下两条阴影不消失；
3.课程暂停播放时，播放界面中间的暂停按钮不显示（由ana提供UI）；
4.双击播放界面可切换播放暂停状态。
交互图打开链接 https://modao.cc/app/Ym635uhCHcUstTgS5vk1yo3kVKoXsvG 进行查看
UI查看 [ftp://192.168.1.134/www/bstcine/ui-v1/courseplayshare](url)

**Comment by limingLiuBaBa** [comment]
点击暂停按钮后界面上下两条阴影不消失,这一条指的是一直不消失,还是说自动隐藏时间到了,依然消失.?@MaryLinker

**Comment by limingLiuBaBa** [comment]
comlete and close (alerady check by myself)

**Comment by joelin109** [comment]
## Problem
- ？
