### ISSUE TITLE
H5-商城：首页- 添加课程筛选功能

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#152]
- 1.第一个栏目：新概念，其中：已上线的《新概念第二册》1-24课程，图片用正常颜色，其它待推出的新概念课程（新概念1，3，4）图片用一层表面的磨砂感处理一下，表示当前还没有推出

- 2.首页用两个tab页，第一个默认tab页名称“视频课程”，该tab页里就是我们现在的所有视频课程，第二个tab页名称“教材教辅”，里面放置教材实物书、学习机、练习册等等

- UI设计
  - Pad：PC-H5：新版的首页-添加课程筛选功能 - UI.Pad （#193）
  - APP：?
  - PC：see UI.PC

**Comment by joelin109** [comment]
![361512120116_ pic_hd](https://user-images.githubusercontent.com/23466882/33476295-7236f256-d6bc-11e7-94ff-59f8f263dc03.jpg)

**Comment by daweilv** [comment]
## _**上线前需要提供的数据**_

1. 所有课程对应的标签
2. 顶部 banner 需要的两种尺寸图片
