### ISSUE TITLE
Android-学习系统-课程播放界面控制操作

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#16]
需求描述：
1.暂停按钮、播放按钮、进度条游标尺寸调大（由ana提供UI）；
2.点击暂停按钮后界面上下两条阴影不消失；
3.课程暂停播放时，播放界面中间的暂停按钮不显示（由ana提供UI）；
4.双击播放界面可切换播放暂停状态。
交互图打开链接 https://modao.cc/app/Ym635uhCHcUstTgS5vk1yo3kVKoXsvG 进行查看
UI查看 [ftp://192.168.1.134/www/bstcine/ui-v1/courseplayshare](url)

**Comment by itwangxiang** [comment]
@MaryLinker 
关于第3点，课程暂停播放时，上一章和下一章按钮需要隐藏吗

**Comment by YangKaiqiCine** [comment]
-  @AaronLiDangkun @limingLiuBaBa @joelin109 暂停播放时，屏蔽掉上一章和下一章功能，
- @limingLiuBaBa @AaronLiDangkun @itwangxiang @joelin109 用户主动在阴影上点击“结束本次学习，打卡”   按钮时，不再出现打卡界面，直接分享到朋友圈
- 不全屏，两边留白一点，具体留白大小，请 @itwangxiang @MaryLinker  @joelin109  确定

**Comment by itwangxiang** [comment]
已经完成
@MaryLinker

**Comment by MaryLinker** [comment]
拖动进度条游标时，游标部分的圆形灰色阴影显示不全，如下图红色框标注所示，这个需要修改吗？@YangKaiqiCine @itwangxiang@joelin109
![image](https://user-images.githubusercontent.com/32290407/31003023-123f0c44-a520-11e7-81e4-bc9f6d9977c1.png)
