### ISSUE TITLE
Android-H5: 词汇量测试设计

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#169]
## 检验2个Case
- 直接调用`词汇量测试H5-网页`，然后交互
- 把`词汇量测试H5-网页`所需的JS预先放在本地，然后交互 （看看性能有没有提升）

**Comment by joelin109** [comment]
## Android V5以下不支持H5

**Comment by itwangxiang** [comment]
- 分享成功需要H5模块完成
- 离线缓存需要H5模块完成

**Comment by joelin109** [comment]
## Problem
- 没有登入，点击`登入系统`，提示异常
