### ISSUE TITLE
Android-个人设置：在我的页面添加我的词汇测试报告入口

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#175]
为了记录“词汇测试结果”，在“我的”页面添加一个“我的词汇测试”栏目

#218

**Comment by itwangxiang** [comment]
是在“我的学习”页，还是“我的”页面？ @MaryLinker

**Comment by MaryLinker** [comment]
问题：
- [ ] 1.测试时长单位是秒还是分？是否要标注？
- [ ] 2.在测试报告页面点击推荐的图书无法跳转至相应课程详情页
- [ ] 3.在测试报告页面点击分享没有反应
- [ ] 4.从测试报告页面点击返回按钮回到了我的页面，应该回到测试列表页面
- [ ] 5.无网络时，点击我的测试和测试列表，分别如下图，没有无网络提示信息，点击再测一次也没有提示信息，页面显示空白
![image](https://user-images.githubusercontent.com/32290407/34755158-3e8c0472-f5fd-11e7-8ee3-16529fc2e13d.png)
![image](https://user-images.githubusercontent.com/32290407/34755185-636f995c-f5fd-11e7-92e3-825779b364d2.png)
- [ ] 6.无测试时的页面是否需要重新设计？
![image](https://user-images.githubusercontent.com/32290407/34755258-e440418a-f5fd-11e7-9d4a-68b7ab464324.png)
