### ISSUE TITLE
iOS-个人设置： 一键分享APP

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#19]
## 需求描述
------
### 1.入口位置
放置在我的页面底端
### 2.按钮描述文字
分享APP，就得积分
### 3.UI
>* “分享APP，就得积分”按钮
>* “分享成功”获得积分奖励提示框
>* “分享成功”未获得积分奖励提示框
查看UI [ftp://192.168.1.134/www/bstcine/ui-v1/appshare](url)
切图图片 [ftp://192.168.1.134/www/bstcine/ios/appshare](url)
### 4.积分奖励规则
>* 用户每日通过分享APP获得的积分数由后台做成可配置的，默认每日可获得3个积分，每日打卡总次数不限
>* 用户每次分享APP可获得1个积分
>* 用户分享APP可累积获得总积分=用户购买的所有课程累积的实付总金额*1%
### 5.步骤
> (1) 打开APP点击“我的”页面，在页面底端可以看见“分享APP，就得积分”按钮；
> (2) 点击“分享APP，就得积分”按钮，进入微信分享编辑页面；
> (3) 点击微信分享编辑页面的“发送”按钮，APP分享成功，自动返回善恩英语APP“我的”页面并弹出“分享成功”窗口；
> (4) 点击“分享成功”窗口上的“X”按钮，“分享成功”窗口消失。
交互图打开链接 https://modao.cc/app/VWWAbf7dnJueqRlzwkeVpqsP01rtIrV 进行查看

**Comment by limingLiuBaBa** [comment]
完成(因目前iOS 播放界面依然可以竖屏,所以打卡及打卡成功的界面依然是竖屏,但 设计师给出的是横屏UI ,所以,UI依据横屏做的竖屏适配)

**Comment by MaryLinker** [comment]
因在verified之后需求变更，打卡成功页面最底端的“打卡拼手气赢积分，1积分=1块钱”文字去除。

**Comment by limingLiuBaBa** [comment]
界面重新修改完成

**Comment by joelin109** [comment]
- 问题如下：
```
Step 1： 点击 “我的”， 显示个人详情页面
Step 2： 个人详情页面， 点击 “分享APP， 就得积分” 按钮
Step 3 （错误）：在微信分享页，显示信息空白

正确：应该会有一些信息显示
```


<br>

```
iphone 7 - iOS11 - 正式环境
```

**Comment by joelin109** [comment]
![img_1514](https://user-images.githubusercontent.com/23466882/31044242-30be8e62-a591-11e7-9de0-88b539713248.PNG)

**Comment by limingLiuBaBa** [comment]
分享唤醒微信后界面,显示空白修复.
