### ISSUE TITLE
iOS-更新: 规范app需要更新时弹出的UI

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#192]
Ana会提供一个app更新时弹出的UI

**Comment by Anawangqi** [comment]
APP版本更新提示UI
切图和标注：
ios: ftp://192.168.1.134/www/bstcine/ios/update
Android: ftp://192.168.1.134/www/bstcine/android/update

**设计图**
![app-](https://user-images.githubusercontent.com/32318334/33601850-6feaf752-d9e8-11e7-9707-e810dfd4ee1b.png)
