### ISSUE TITLE
H5-商城：首页 - 添加课程筛选功能  - UI.Pad

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#193]
## 新版首页的需求 #152

<br>

## Pad版-UI -商城首页
<注：帮我选课功能此次还没有出，将在后续版本中更新>
<br>

- 竖屏
![02 -0](https://user-images.githubusercontent.com/32318334/34040353-43b5019e-e1ce-11e7-93e3-8493a32addb8.png)

<br>
<br>

- 横屏
![02 -1](https://user-images.githubusercontent.com/32318334/34040447-b15b73ae-e1ce-11e7-9086-70ec4ee6b130.png)

<br>

#219

**Comment by Anawangqi** [comment]
Pad版 商城首页UI

竖屏
![02 -0](https://user-images.githubusercontent.com/32318334/34032062-4f3902e6-e1af-11e7-99fa-106c099063b1.png)

横屏
![02 -3](https://user-images.githubusercontent.com/32318334/34032080-607f58a2-e1af-11e7-9d40-9f8ab611737d.png)

**Comment by daweilv** [comment]
建议加一个选择课程时的 loading 过渡

**Comment by daweilv** [comment]
标签右上角的小tip `免费` 需要业务想清楚可能有哪些，只有文字还是图片也有可能，避免活动上线前才临时提供，避免不必要的 css 和 img 文件更新

**Comment by daweilv** [comment]
教辅 tab 页需要出图

**Comment by daweilv** [comment]
`阶段` - `高考` 右侧的 `>`  代表什么意思

**Comment by daweilv** [comment]
PC 官网的公告栏取消还是做成 banner 的形式合并进 banner 内？
<img width="1058" alt="123" src="https://user-images.githubusercontent.com/7405300/34078355-93f8c6d2-e353-11e7-9c7f-d38bc42ff552.png">
