### ISSUE TITLE
PC-注册与登录：取消邮箱注册入口

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#198]
关于注册和登录，把手机号注册作为唯一注册入口，取消邮箱注册入口
![image](https://user-images.githubusercontent.com/32290407/33752003-d0514f64-dc19-11e7-894a-1075cc0e992d.png)

**Comment by joelin109** [comment]
## 没有手机号的用户：登入
1、原先用邮箱注册的用户，在登录时，强制要求其输入手机号绑定本账户，并用“验证码”验证其手机有效性
2、绑定手机号之后，后续登录过程中，依然允许其用邮箱号登录，但是在使用“找回密码”功能时，必须用绑定的手机号去找回密码，而不是用邮箱找回密码。

```
只有PC端提供“找回密码”功能
```
