### ISSUE TITLE
pc-H5: 词汇量测试反馈列表

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#209]
- [x]  1.1  5s样式需要调整
![1 pic](https://user-images.githubusercontent.com/20130469/33979841-232ac8b6-e0e1-11e7-8f00-3c02e2dfec3c.jpg)

- [x] 1.2 推荐书籍不正确
![4 pic](https://user-images.githubusercontent.com/20130469/33979728-a8dccece-e0e0-11e7-8eff-fb3aeec948b5.jpg)

<br>

- [x]  1.3. 设置从第1个~N个答对则当前级别满分并调整到下个级别: 

- [x]  1.4. ios5s开始测试界面需要下拉才能看到底部，OPPO 测试结果界面需要下拉才能看到下方按钮: 
- [x]  1.5. 安卓点击banner (type=3闪退)（type=1 提示 lesson_id not found）

<br>

**Comment by joelin109** [comment]
## 问题列表

**Comment by joelin109** [comment]
测试issue，#86、#203、#218

## 问题列表
- [x] 2.1 城市、地区、出生年月显示不对
- [x] 2.2 把T_User表的字段，province、city、area_code建议三个保留一个
- [x] 2.3 测试结果， 点击`推荐课程`，没有跳到APP（ios、Android）的课程详情页
- [x] 2.4 点击`分享`，出现异常（弹出框异常提示）

```
- Fir上最新的app（ios、Android） 
- 2017/12/15
- iphone7
- J
```
