### ISSUE TITLE
PC-后台-课程管理：课件批量录入

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#21]
###PC 后台管理 批量上传课件

1.说明: 目前官网课件上传课件比较原始耗费时间.操作如下图：
![11111](https://user-images.githubusercontent.com/20130469/30960797-bc8e0b2c-a409-11e7-9fed-a4ef61d825d1.jpg)

![22222](https://user-images.githubusercontent.com/20130469/30960806-c1dad27c-a409-11e7-9489-e7229e8b9b91.jpg)

2.要求：现在只能单个上传文件，需要能批量上传。

3.后台提供：一定命名规则的音频和图片文件。如1.MP3对应1.png 、2.MP3对应2.png。 

4.因为我们系统文件类型比较多，所以要保存现有的录入功能。

**Comment by joelin109** [comment]
Deadline：2017-10-27

**Comment by iott** [comment]
仅做音频+图片一对一的批量上传么，请具体批量上传的需求

**Comment by joelin109** [comment]
## 文件命名规范
- mp3:
- mp3 对应的图片：

**Comment by joelin109** [comment]
### 需要支持命名排序：
AF-C1-050.mp3
AF-C1-05101.mp3
AF-C1-05102.mp3
AF-C1-052.mp3

**Comment by zhuyichun** [comment]
### 需要支持对lesson的分段：
目前仅支持导入到lesson节点不能导入到Ch下的lesson节点

**Comment by iott** [comment]
### 文件命名注意事项
AF-C1-001.mp3
AF-C1-050.mp3
AF-C1-052.mp3
```
AF: 课程简写
C1：Chapter 1
001、050：文件编号，需保持文件编号的长度一致，否则上传后的文件排序会发生错乱
```
