### ISSUE TITLE
pc-H5: 词汇量测试-测试记录&词汇量排位图

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#218]
## 测试记录
- [x] 测试记录
http://apptest.bstcine.com/vocabtest/reportlist?token=xxxx

```
入口:  App - 我的 - 我的词汇测试
```

![01 - -1](https://user-images.githubusercontent.com/32318334/33469900-6afcea8e-d6a0-11e7-9a29-6c55c277bcf4.png)

- [ ] 测试记录详情
```
目前就是 report 页面，不是每一个单词的答题详情
```
<br>
<br>

## 词汇量排位图
- [ ] 排位图
![01- -5 - -](https://user-images.githubusercontent.com/32318334/35272000-bad9d63c-006e-11e8-8f9e-b5695f36079f.png)

<br>
<br>

测试反馈列表 #209

### 更新需求
```
1. 如果没有测试数据，显示
没有数据， 赶快测试吧

2. 在底部添加一个`测试`按钮

- 2018-01-15
```

**Comment by Anawangqi** [comment]
无数据显示
![01- -00](https://user-images.githubusercontent.com/32318334/34933294-436dd412-fa11-11e7-88be-b6b776de0b65.png)

图例报告
![01- -5 - -](https://user-images.githubusercontent.com/32318334/34933296-43b15228-fa11-11e7-844a-becc0641399a.png)

**Comment by joelin109** [comment]
## 问题如下：
- [x] 1.推荐课程为空

**Comment by Anawangqi** [comment]
新增UI： 用户未登录时，提示用户登录后再测试
![01- -](https://user-images.githubusercontent.com/32318334/35271296-99ef2c3a-006c-11e8-91d9-c6a7efca0ce5.png)
