### ISSUE TITLE
IOS-学习系统:在播放界面点击课程目录上的下载按钮出现闪退

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#22]
>1.手机型号：iPhone6s
>手机系统：ios11
>bug描述：课程播放几分钟后，在点击课程目录上的下载按钮后，再次点击其他的lesson下载按钮后，出现闪退现象。不能重现，2天内出现了约6次。

>2.手机型号：iPhone6s
>手机系统：ios11
>bug描述：有正在下载的lesson时，课程的图片未加载出来，音频正常播放。

**Comment by AaronLiDangkun** [comment]
#### 点击下载按钮闪退问题
- 原因描述：此闪退问题不是因为点击下载按钮，而是因为播放器在显示播放进度和图片时，定时器每0.5秒获取一次多媒体数组中的对应资源。当一个章节播放完毕切换到第二个章节时，播放器保存的资源下标为上一个章节数组的最后一个资源下标，当用这个下标取新的资源数组的资源时，如果新的资源数组的总量小于上一个资源数组的总量，就会造成新的数组访问越界，造成闪退。
- 解决方案：在获取新资源时，判断下标是否超出新资源数组总量，如果超出，则不访问数组资源。等待下标归零之后，再重新访问。

**Comment by AaronLiDangkun** [comment]
#### 音频播放，图片未显示问题
- 原因分析： 加载图片开始播放判断机制为 SDWebImage 在加载图片进行时暂停播放器，加载图片完成时开始播放。当网络较差时，SDWebImage 在访问 url 时有一段时间延迟，不能及时暂停播放器。此时上一张图片仍存在，但放置图片的 UIImageView 被隐藏，所以仍为播放状态，但显示状态却为加载中.
- 解决方案：增加判断机制，暂停播放器. 当放置图片的 UIImageView 被隐藏时，直接暂停播放器，当 UIImageView 加载完毕开始显示时，开始播放器
