### ISSUE TITLE
H5-商城：课程详情页 - 测试问题反馈列表 - V2.0.2

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#222]
更多问题， https://github.com/bstcine/cine-tasklist/issues/247

  ## 通用问题：
- [x] 1-：课程详情页，授课老师、授课时长分2行显示
<br>

  
<br>

## 测试Demo：
默认立减30改为立减50

- d1.  莎士比亚 ：
http://apptest.bstcine.com/content/course?cid=d011509938661571VgCQV2kadY
```
优惠券类型：默认
是否有介绍视频：是
```

- d2.  神奇树屋1：恐龙谷历险记》英文朗读版：
http://apptest.bstcine.com/content/course?cid=d011503642366597QZ5sWf7xpJ
```
优惠券类型：分享朋友圈立即开通
```

- d3.《神奇树屋》1-4册英文原版书：
http://apptest.bstcine.com/content/course?cid=d011513668589227kQwbd4fBeC
```
优惠类型：无

- 备注：为了测试 - 优惠券类型：98折扣  
```

- d4. 托福课程套餐：
http://apptest.bstcine.com/content/course?cid=d011493260011863cpPcd3kTyu
```
优惠类型：立减30

- 备注：为了测试 - 优惠券类型：立减50，购买后送学习机优惠券
```

- d5. 新概念2教材：
http://apptest.bstcine.com/content/course?cid=d011513669934993t1cvFNVYHr
```

优惠券类型：无
```

- d6. 美国小学Wonders-Reading/Writing Workshop G3课本:
http://apptest.bstcine.com/content/course?cid=d011506496127647VKsufwfU3N
```
优惠券类型：无
```

**Comment by MaryLinker** [comment]
问题：
- [ ] 1.已经购买过的课程不显示“点此分享到朋友圈享95折”“成功分享，已享95折优惠”

**Comment by zhuyichun** [comment]
问题：
- [ ] 1.IOS课程概要和安卓课程概要有内容时候读取各自的内容，为空时候读取PC端的课程概要” - ‘Jerry’
