### ISSUE TITLE
iPad-V2.0.2: 测试问题反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#223]

**Comment by MaryLinker** [comment]
## 1.我的页面
- ### 1.1 我的优惠券
- [ ] 1.1.1 添加已经存在的优惠券没有提示信息，应该提示“该优惠券已存在”
- [ ] 1.1.2 页面顶端导航栏偶尔消失
- [ ] 1.1.3 未使用页面的优惠券不能及时刷新，只能显示一页内容，再次进入此页面才可显示全
- [ ] 1.1.4 未使用页面出现闪退，无法重现
- ### 1.2 个人信息
- [ ] 1.2.1 页面顶端导航栏偶尔消失
- ### 1.3 可用积分
- [ ] 1.3.1 页面顶端导航栏偶尔消失
- ### 1.4 我的订单
- [ ] 1.4.1 页面顶端导航栏偶尔消失
- ### 1.5 我的学习
- [ ] 1.5.1 页面顶端导航栏偶尔消失
- ### 1.6 我的下载
- [ ] 1.6.1 页面顶端导航栏偶尔消失
- ### 1.7 关于我们
- [ ] 1.7.1 页面顶端导航栏偶尔消失
- ### 1.8 分享APP
- [ ] 1.8.1 分享APP至微信端和回到APP时页面会刷新2次
## 2.商城 
- ### 2.1 首页
- ### 2.2 课程详情页
- [ ] 2.2.1 分享成功或取消分享返回至APP时刷新了2次
## 3.注册与登录
- ### 3.1 忘记密码
- [ ] 3.1.1 点击忘记密码输入手机号时，键盘未弹出，发生闪退，无法重现
- [ ] 3.1.2 密码设置成功后没有提示密码设置成功 
- [ ] 3.1.3 未填写手机号时输入框也有X ，重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707694-c7f5d080-f549-11e7-90aa-dfb0255fe54a.png)


- ### 3.2 注册
- [ ] 3.2.1 未填写手机号时输入框也有X 
![image](https://user-images.githubusercontent.com/32290407/34707721-fcb7f7bc-f549-11e7-96de-a5eb2fe0fcc1.png)

- [ ] 3.2.2 重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707425-6bb0b39a-f548-11e7-90d2-05c60c779cb5.png)
- ### 3.3 登录
- [ ] 3.3.1 未填写手机号密码时输入框也有X 
![image](https://user-images.githubusercontent.com/32290407/34707774-328d9da6-f54a-11e7-98a3-fb4e6d0828a3.png)
