### ISSUE TITLE
H5-学习系统: Lesson播放页-Media对应的习题测试

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#225]
## 前提
- API: Lesson播放页-播放过程添加习题测试 #212
```
下列三个 API，添加 quizs 字段，可以获得该Lesson的习题测试数据.

PC: /learn/lesson/:lesson_id
V1: /api/app/lessonlearn
V2: /api/content/lesson/detail

测试分类（条件）：
小节测试: media_url = xxx
本章测试: media_url = -1
```
- PC-后台管理: Lesson播放页-播放过程添加习题测试 #208

<br>

## 需求
- Lesson播放过程中，最多只能请求一次API去拿该Lesson对应的习题测试

<br>

## 测试校验
- PC
http://apptest.bstcine.com/learn/lesson/d011494899752685PaphkjxWVc?content_id=d011494900093721EM1UbFtgfy
```

Lesson1：Tag1, Tag2, 单元测试
```

<br> 

## 提供链接
- Android，#207
- iPad，#232
  
## 状态
- UI 的适配 
   - [ ] PC
   - [ ] iPad
   - [ ] iPhone
   - [ ] Phone
   - [ ] Pad

**Comment by Anawangqi** [comment]
1.开始答题
![default](https://user-images.githubusercontent.com/32318334/34475292-a8728ca0-efc5-11e7-8c7f-7fb0461a0a36.png)

2.文字题型-回答错误
![1](https://user-images.githubusercontent.com/32318334/34475302-bfb67bc4-efc5-11e7-9b2c-80e37d53027a.png)

3.文字题型-回答正确
![2](https://user-images.githubusercontent.com/32318334/34475356-49e72cd0-efc6-11e7-85b4-7a1b47f210b0.png)

4.图片题型-回答错误
![3](https://user-images.githubusercontent.com/32318334/34475362-562fce84-efc6-11e7-8709-26dfa2d58060.png)

5.答题结束
![default](https://user-images.githubusercontent.com/32318334/34475364-5d0a61b0-efc6-11e7-8280-d892a3320a18.png)

**Comment by itwangxiang** [comment]
测试题UI，标注文件
/www/bstcine/web-ui/studytest

切图
/www/bstcine/web/studytest

**Comment by MaryLinker** [comment]
-[ ] 1. tag答题结束后，这里应该显示“继续学习”？
![image](https://user-images.githubusercontent.com/32290407/34658033-8cb314bc-f466-11e7-84c6-a7274f856e74.png)
-[ ] 2. 不选择答案也可以进入下一题，是否合理？
-[ ] 3.全部都选错的或存在没有选择的题目时没有测试结果
-[ ] 4.本章测试答题结束后不再显示“下一题”，应该显示“提交”？或者别的
-[ ] 5.答题过程中拖动页面滑动条后就会定住，到下一题时不会从顶部开始显示
![image](https://user-images.githubusercontent.com/32290407/34659463-edca4718-f473-11e7-83bc-0cba6ea12188.png)
-[ ] 6.浏览器端没有滑动条，也看不见下一题的按钮
![image](https://user-images.githubusercontent.com/32290407/34659509-6cf83964-f474-11e7-852c-4c7e97a80b94.png)

**Comment by joelin109** [comment]
## 测试反馈：
现在的UI不能接受
