### ISSUE TITLE
API-数据统计：数据来源(sitecode) 收集 - 订单、分享、登入

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#229]
## 数据来源
iOS:  iPhone - app/web, ipad - app/web
Android: phone - app/web, pad - app
PC: -
Wechat: 微信内部

```
cine.ios.iphone
cine.ios.ipad
cine.android.phone
cine.android.pad
cine.web.wechat

cine.web.android.phone
cine.web.android.pad
cine.web.iphone
cine.web.ipad
cine.web.pc
cine.web.other
```

**Comment by MaryLinker** [comment]
问题如下：
iOS-iPhone-课程详情页分享：cine.ios.ipad
iOS-web-iPad-打卡分享：空白
iOS-web-iPhone-打卡分享：空白
PC-web-课程详情页分享：空白
PC-web-打卡分享：空白
微信-打卡分享：空白
安卓-pad/iPhone/web-登录/分享/订单：空白
