### ISSUE TITLE
iOS-商城：教材预定栏目中的书籍顺序错误

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#23]
#### bug描述：在商城页面的教材预定栏目中，美国小学Wonders三年级课本（1册）和美国小学Wonders二年级课本（1册）的位置反了
![image](https://user-images.githubusercontent.com/32290407/30998439-0f98a348-a501-11e7-8612-c2937c761790.png)

**Comment by AaronLiDangkun** [comment]
#### 对于课程栏，客户端没有排序字段，不能执行排序，请服务器端检查数据排列是否异常
