### ISSUE TITLE
iPad-APP: 测试问题反馈列表- V2.0.2 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#230]
## Must fix
- [ ] 1- 2.2.8: 课程详情页分享在微信端取消分享返回课程详情页，弹出’分享已取消‘时，产品图显示黑框，两次刷新- bug - Je
```
Status：此现象为 app 通讯间转场动画，与设备性能和系统有关，
        参考同类型可以分享到微信朋友圈的 app，都存在此现象，暂时没有解决方案
```

- [ ] 2- 6.3  -Jerry
 -  step1：点击播放已下载中的课件，打卡分享到朋友圈后返回播放界面。
 -  step2：点击‘我知道了’按钮，返回到已下载文件列表界面没有返回按钮，并且后台声音在播放。
```
Status:fixed
```
<br>

- [ ] 3-5.1 在我的测试报告页面点击返回回到多个页面，很繁琐
```
Status:fixed
```

<br>
<br>

## Nice to have
- [ ] 21-1.1.6. iPad-点击套餐课程的课程概要内的子课程链接会跳转至对应网页版课程详情页 
```
Status:fixed
```

**Comment by MaryLinker** [comment]
## 1.我的页面
- ### 1.1 我的优惠券
- [ ] 1.1.1 添加已经存在的优惠券没有提示信息，应该提示“该优惠券已存在”
- [ ] 1.1.2 页面顶端导航栏偶尔消失
- [ ] 1.1.3 未使用页面的优惠券不能及时刷新，只能显示一页内容，再次进入此页面才可显示全
- [ ] 1.1.4 未使用页面出现闪退，无法重现
- ### 1.2 个人信息
- [ ] 1.2.1 页面顶端导航栏偶尔消失
- ### 1.3 可用积分
- [ ] 1.3.1 页面顶端导航栏偶尔消失
- ### 1.4 我的订单
- [ ] 1.4.1 页面顶端导航栏偶尔消失
- ### 1.5 我的学习
- [ ] 1.5.1 页面顶端导航栏偶尔消失
- ### 1.6 我的下载
- [ ] 1.6.1 页面顶端导航栏偶尔消失
- ### 1.7 关于我们
- [ ] 1.7.1 页面顶端导航栏偶尔消失
- ### 1.8 分享APP
- [ ] 1.8.1 分享APP至微信端和回到APP时页面会刷新2次
## 2.商城 
- ### 2.1 首页
- ### 2.2 课程详情页
- [ ] 2.2.1 分享成功或取消分享返回至APP时刷新了2次
- [ ] 2.2.2 未登录情况下，点击“推荐课程得积分”不应该要求登录
## 3.注册与登录
- ### 3.1 忘记密码
- [ ] 3.1.1 点击忘记密码输入手机号时，键盘未弹出，发生闪退，无法重现
- [ ] 3.1.2 密码设置成功后没有提示密码设置成功 
- [ ] 3.1.3 未填写手机号时输入框也有X ，重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707694-c7f5d080-f549-11e7-90aa-dfb0255fe54a.png)


- ### 3.2 注册
- [ ] 3.2.1 未填写手机号时输入框也有X 
![image](https://user-images.githubusercontent.com/32290407/34707721-fcb7f7bc-f549-11e7-96de-a5eb2fe0fcc1.png)

- [ ] 3.2.2 重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707425-6bb0b39a-f548-11e7-90d2-05c60c779cb5.png)
- ### 3.3 登录
- [ ] 3.3.1 未填写手机号密码时输入框也有X 
![image](https://user-images.githubusercontent.com/32290407/34707774-328d9da6-f54a-11e7-98a3-fb4e6d0828a3.png)

**Comment by joelin109** [comment]
## 4.购买与支付
- ### 4.1 结算中心
- [ ] 4.1.1 新用户购买福克纳经典短篇精度，应付328，系统自动匹配20元对应课程优惠券和100积分后，实付金额显示为188，应该为208
- [ ] 4.1.2 学习机无法使用其专享优惠券直减200   
- [ ] 4.1.3 购买学习机时，系统没有自动匹配其专享优惠券 
- [ ] 4.1.4 新学员购买学习机时，系统匹配了新用户专属优惠券
- [ ] 4.1.5 购买学习机时，通用优惠券也在“可使用优惠券”列表内，但不可用
- [ ] 4.1.6 在使用优惠券页面添加的优惠券不符合使用条件时，没有信息提示 
- ### 4.2 善恩收银台
- [x] 4.2.1 微信和支付宝的图标没有对齐
![image](https://user-images.githubusercontent.com/32290407/34751741-5d2c1f20-f5e9-11e7-8763-ee93eec6a477.png)
- [ ] 4.2.2 无支付帮助可点击，无人工客服
![image](https://user-images.githubusercontent.com/32290407/34753068-e1b99df6-f5f0-11e7-913a-25af2759e84e.png)
- ### 4.3 订单详情
- [ ] 4.3.1 使用95折优惠券，应该减去8.4
![image](https://user-images.githubusercontent.com/32290407/34753695-5bfcc09a-f5f4-11e7-8221-fb183a2ce057.png)
- [ ] 4.3.2 新用户在第一笔订单成交后的24小时之外还可以支付其为新用户时提交的订单，是否合理？ 
- [ ] 4.3.3 点击“立即支付”按钮没有反应

**Comment by zhuyichun** [comment]
## 1.Medio测试反馈
- ### 1.1 PC
- [] 1.1.1 点击批量上传课件操作框中的保存按钮后报错，报错不了
```

**Comment by zhuyichun** [comment]
## 1.我的页面
- ### 1.1 我的积分
- [ ] 1.1.1 没有显示积分明细
- ### 1.2 我的个人信息
- [ ] 1.2.1 地址管理：收货人、联系方式、详细地址等字体最好别采用灰色，用户看到灰色本能认为不能填写
```
```

```

**Comment by joelin109** [comment]
## 1.我的页面
- ### 1.1 我的优惠券
- [x] 1.1.1 添加已经存在的优惠券没有提示信息，应该提示“该优惠券已存在”
```
此种状况服务器认为添加成功，请转交服务端处理
```
- [x] 1.1.3 未使用页面的优惠券不能及时刷新，只能显示一页内容，再次进入此页面才可显示全
```
优惠券 api 数据获取模式为分页获取，暂定每页获取大小为10，已修改为100，
无法完全避免获取问题，请确定需求样式
```
- ### 1.8 分享APP
- [x] 1.8.1 分享APP至微信端和回到APP时页面会刷新2次
```
非刷新造成的现象，是设备因素造成 window 闪现，解决成本较高
```
- [x] 1.8.2 横版分享APP文字看不见 
![image](https://user-images.githubusercontent.com/32290407/34711615-f6ba25d6-f55a-11e7-87af-02ad7f700619.png)
```
请自行滚动到分享位置
```
## 3.注册与登录
- ### 3.1 忘记密码
- [ ] 3.1.1 点击忘记密码输入手机号时，键盘未弹出，发生闪退，无法重现
- [ ] 3.1.2 密码设置成功后没有提示密码设置成功 
- [ ] 3.1.3 未填写手机号时输入框也有X ，重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707694-c7f5d080-f549-11e7-90aa-dfb0255fe54a.png)
- ### 3.2 注册
- [ ] 3.2.1 未填写手机号时输入框也有X 
![image](https://user-images.githubusercontent.com/32290407/34707721-fcb7f7bc-f549-11e7-96de-a5eb2fe0fcc1.png)
- [ ] 3.2.2 重置密码页面是否需要文字“已有账号，点击登录”
![image](https://user-images.githubusercontent.com/32290407/34707425-6bb0b39a-f548-11e7-90d2-05c60c779cb5.png)
- ### 3.3 登录
- [ ] 3.3.1 未填写手机号密码时输入框也有X 
- [ ] 3.3.2 从有网络切换至无网络时，输入密码时出现闪退，键盘没有弹出来
![image](https://user-images.githubusercontent.com/32290407/34707774-328d9da6-f54a-11e7-98a3-fb4e6d0828a3.png)
- [ ] 3.3.3 登录进来出现以下现象：
![image](https://user-images.githubusercontent.com/32290407/34711788-8b7b454c-f55b-11e7-8b80-ea50f0f9861c.png)

**Comment by joelin109** [comment]
## 4.注册与登录
- ### 4.1 忘记密码
- [ ] 4.1.1 点击忘记密码输入手机号时，键盘未弹出，发生闪退，无法重现
- [ ] 4.1.2 密码设置成功后没有提示密码设置成功 
- [ ] 4.1.3 未填写手机号时输入框也有X ，重置密码页面是否需要文字“已有账号，点击登录”
[image](https://user-images.githubusercontent.com/32290407/34707694-c7f5d080-f549-11e7-90aa-dfb0255fe54a.png)

- ### 4.2 注册
- [ ] 4.2.1 未填写手机号时输入框也有X 
[image](https://user-images.githubusercontent.com/32290407/34707721-fcb7f7bc-f549-11e7-96de-a5eb2fe0fcc1.png)
- [ ] 4.2.2 重置密码页面是否需要文字“已有账号，点击登录” [image](https://user-images.githubusercontent.com/32290407/34707425-6bb0b39a-f548-11e7-90d2-05c60c779cb5.png)
- ### 4.3 登录
- [ ] 4.3.1 未填写手机号密码时输入框也有X 
- [ ] 4.3.2 从有网络切换至无网络时，输入密码时出现闪退，键盘没有弹出来 [image](https://user-images.githubusercontent.com/32290407/34707774-328d9da6-f54a-11e7-98a3-fb4e6d0828a3.png)
- [ ] 4.3.3 登录进来出现以下现象：[image](https://user-images.githubusercontent.com/32290407/34711788-8b7b454c-f55b-11e7-8b80-ea50f0f9861c.png)

**Comment by MaryLinker** [comment]
## 5.词汇测试
- [ ] 5.1 在我的测试报告页面点击返回回到多个页面，很繁琐
- [ ] 5.2 报告页面底端文字“本结果为简版测试结果，我们将在2周后….”去除
- [ ] 5.3 分享标题没有

**Comment by zhuyichun** [comment]
## 6.下载
- [ ] 6.1 退出APP后再次进入App,已经下载好的课件被清空了 -Jerry
