### ISSUE TITLE
PC-学习系统：账户需要强制进行手机号绑定

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#233]
## 需求
- 用户进行`课程学习`时，需要确保该账号有手机号
  
```
1. 输入手机号 （国家区号）
2. 输入验证码
3. 界面会显示如下提醒：
“系统检测到您还没有绑定手机号，为了你的账号安全，请绑定您的手机号”，




手机号必须是唯一的
```

<br>

### UI
- .
```
Ana 将提供UI排版
```

**Comment by Anawangqi** [comment]
手机号绑定
![00-3 -new](https://user-images.githubusercontent.com/32318334/34717617-a6956f2a-f56e-11e7-9ff6-72e2fe92e246.png)

验证码输入错误提示
![00- _new](https://user-images.githubusercontent.com/32318334/34717630-ae666204-f56e-11e7-81b9-08291d16e887.png)

**Comment by MaryLinker** [comment]
## 问题：
- [ ] 1. 无法发送验证码
- [ ] 2.界面不美观
![image](https://user-images.githubusercontent.com/32290407/34805179-b1ac1fe0-f6b7-11e7-90bf-31f4a6ac1062.png)
