### ISSUE TITLE
账号安全：人脸识别功能

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#234]
## 需求
- 待定

<br>

#### 参考
人脸识别功能描述：https://cloud.tencent.com/product/FaceRecognition?idx=1&fromSource=gwzcw.245245.245245.245245

**Comment by bitcl2** [comment]
哥们，可以试试百度人脸识别。教育行业人脸识别登录典型应用例子是乂学教育，就是中央一套天天播的那个松鼠AI。
另外看到您一个对比各教学平台的issue特别感兴趣，希望能多交流。
email： love1@mail.bitcl.win
