### ISSUE TITLE
Cine-WeChat：微信公众平台服务号-Template Message

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#235]
#### 参考：微信公众平台服务号
- 公众号名称为：`波士顿善恩英语`
- 微信号为：`BOSTON-CINE`
- Wechat Official Accounts Platform:
https://mp.weixin.qq.com/wiki?t=resource/res_main&id=mp1433751277

<br>

## 需求
- 服务号可以进行推送 `Template Message`

**Comment by iott** [comment]
### 需求整理如下：
- 推送一条消息作为订阅的入口
  - 文字表述如下：
    应大家的要求，善恩正式推出由Hans博士主讲的英美报刊讲读，一键订阅，每日推送，磨听力、学口语、提阅读、练思辨、知天下。每天10分钟，与世界同步，就在善恩“每日英美报刊讲读”，点击此处查看详情
    ```
     查看详情跳转到官网现有的详情页：http://www.bstcine.com/lesson/d0115096981477539Jv3vkhCHm
    ```
- 购买与支付
  支付完成后开通课程时需向用户推送购买成功的消息，消息模板添加跳转链接，链接的内容为开通页面
  ```
   注：消息模板待确定
  ```
- 开通页面如下：
  你好，亲爱的用户xxx，感谢您选择善恩英语的“英美报刊每日讲读”，我们会从3.1号开始，每日早上7:00通过本微信号向您推送一篇包含文字和音频的微信文章，同时，也邀请你加入相应的学习群中，您可以在群里向我们的驻群老师提问和探讨，更可以和来自世界各地、五湖四海的同学们一起学习、分享和打卡，真正体会“众阅乐”的愉悦！点击这里查看详情。
（1）每日推送时间：早上7:00
（2）如何加入学习群：请加善恩小助手微信号“bstcine01”
（3）学习步骤：略，待补充
（4）如何打卡：在微信文章中，点击右上角“分享到朋友圈”

- 每日学习计划
  推送一条学习计划提醒的消息，添加跳转链接，链接到一篇微信文章：http://mp.weixin.qq.com/s/YkvfYoSIyS2CJAc9SJYq5w
  ```
  计划模板待定
  ```
