### ISSUE TITLE
Android-APP: 测试问题反馈列表- V2.0.2

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#244]
## Feature
- [x]  学习-Lesson播放页：如果有习题测试的话， 需要显示“测验”
- [x]  商城-课程详情页：使用新的H5
- [x]  商城-结算中心： 对象需要收货地址的课程， 需要添加 “收货地址”
- [x]  我的-我的订单：去掉“待分享”， 添加“已完成”
- [x]  我的：添加“我的测试”
- [x]  我的：我的信息， 添加“地址管理”

## Must fix
- [x] 1- 3： 已经购买过的套餐/书籍/学习机课程详情页去除"去学习"按钮，
```
- 建议: 套餐可跳转至我的学习页面, 

Solution:
- 1. 去除"去学习"按钮
- 2. 转至我的学习页面
```

<br>

## Nice to have
- [ ] 11-13.拖动进度条加载视频时，偶尔会出现没有图片，只有声音的现象
- [ ] 12-12：点击课程详情页里面的课程链接会跳转至外部浏览器 ，华为手机
```
Solution:
建议：课程链接跳转至对应的课程详情页
```

**Comment by MaryLinker** [comment]
测试版本：1.1.8（Build 13 2018-1-22 17:54）
- [ ]1.填写地址时，点击历史输入记录，背景变黄色
- [ ]2.我的订单页面四个收货信息文字为：收货信息，发货时间，快递单号，快递公司
- [ ]3.套餐/书籍/学习机课程详情页去除去学习按钮，其中，套餐建议可跳转至我的学习页面
- [ ]4.试听课程回到商城，试听没有停止，返回关闭，再回到商城仍然有声音
- [ ]5.待付款订单没有到期时间
- [ ]6.缓冲详情页时，页面的课程详情，课程目录，用户评价三个tag会显示成详情，评价
- [ ]7.pad上副标题显示不全
- [ ]8.个人设置页面调出键盘后，返回至我的页面后，键盘仍然存在
- [ ]9.词汇测试时，账号被登录，在词汇测试提示登录页面无法返回（点击手机返回键），点击先测一下看看没有反应
- [ ]10.搜索课程进入了旧版详情页
- [ ]11.密码设置为纯数字也成功了
