### ISSUE TITLE
H5-商城：课程详情页 - 可扫二维码跟踪

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#246]
## 课程详情页 - 扫二维码跟踪
- 10 New Users
```
nickname - login - id
新2-传单01  -   - dxgn201*********
新2-传单02
新2-传单03
新2-传单04
新2-传单05
新2-传单06
新2-传单07
新2-传单08
新2-传单09
新2-传单10
```

- 提供的跟踪Link
## 《新概念英语2》第1单元精讲（1-24课）:
```
http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn201352373746PUzFREst7e

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn2023523738009p2vtbmQxU

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn203352373863nE6DRp9e0G

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn2043523739107ATqCZe8Wp

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn205352373956MHdzt3BCku

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn20635237403803PGbUJxxD

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn2073523740833eZv7WgaxH

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn208352374129sg28ksEfP5

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn209352374175Ge1nTQQWwT

http://www.bstcine.com/content/course?cid=d011506563599590C2UgTnNssz
&channel=marketing&source_user_id=dxgn210352374220acAusnkafs

```

<br>
<br>

- 产出
- [x] 提供10个可跟踪Link
- [x] 测试：可在`log_content_course`表跟踪到相应的数据
- [x] 测试：分享该Link，可领`新人优惠券`
- [x] 测试：新人可以正常购买，xgn20*（如dxgn201352373746PUzFREst7e）可获得10%的积分
```
Deadline： 2018-01-21
```

<br>
<br>

## 遗留问题：
- 线上Android版本：新用户可以使用 “新人95折优惠券” 购买，但是分享的用户无法获得10%的积分

**Comment by zhuyichun** [comment]
[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn201352373746PUzFREst7e](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn2023523738009p2vtbmQxU](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn203352373863nE6DRp9e0G](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn2043523739107ATqCZe8Wp](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn205352373956MHdzt3BCku](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn20635237403803PGbUJxxD](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn2073523740833eZv7WgaxH](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn208352374129sg28ksEfP5](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn209352374175Ge1nTQQWwT](url)

[http://www.bstcine.com/content/course?cid=d0115096981477539Jv3vkhCHm
&channel=marketing&source_user_id=dxgn210352374220acAusnkafs](url)

**Comment by joelin109** [comment]
## 托福口语精讲
```
http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn201352373746PUzFREst7e

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn2023523738009p2vtbmQxU

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn203352373863nE6DRp9e0G

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn2043523739107ATqCZe8Wp

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn205352373956MHdzt3BCku

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn20635237403803PGbUJxxD

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn2073523740833eZv7WgaxH

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn208352374129sg28ksEfP5

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn209352374175Ge1nTQQWwT

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu
&channel=marketing&source_user_id=dxgn210352374220acAusnkafs
```

**Comment by joelin109** [comment]
## 托福口语精讲

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn201352373746PUzFREst7e

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn2023523738009p2vtbmQxU

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn203352373863nE6DRp9e0G

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn2043523739107ATqCZe8Wp

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn205352373956MHdzt3BCku

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn20635237403803PGbUJxxD

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn2073523740833eZv7WgaxH

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn208352374129sg28ksEfP5

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn209352374175Ge1nTQQWwT

http://www.bstcine.com/content/course?cid=A0114848779057234dnkUVbCsu&channel=marketing&source_user_id=dxgn210352374220acAusnkafs

**Comment by joelin109** [comment]
## 托福阅读精讲

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn201352373746PUzFREst7e

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn2023523738009p2vtbmQxU

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn203352373863nE6DRp9e0G

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn2043523739107ATqCZe8Wp

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn205352373956MHdzt3BCku

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn20635237403803PGbUJxxD

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn2073523740833eZv7WgaxH

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn208352374129sg28ksEfP5

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn209352374175Ge1nTQQWwT

http://www.bstcine.com/content/course?cid=41&channel=marketing&source_user_id=dxgn210352374220acAusnkafs
