### ISSUE TITLE
H5-PC：测试问题反馈列表 - V2.0.2

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#247]
## 1 课程详情页 - 正式环境
- [x] 1.1-， PC：把所有课程对应的试听MP4放上去，新详情页，可以点击播放 “试听” @Joe
```
Status: 10几个课程对应的试听连接不对， Willing在提供中
```
- [x] 1.2-， PC：把所有课程对应的评论放上去   @Leo
```
Status: Jenny已提供文档， Leo帮忙导入
```
- [x] 1.3-， PC：使用新详情页， 但把“推荐得积分”&“领取95折新人优惠券”的功能 隐藏
```
传单扫二维码跟踪：
新详情页，针对有Channel的需要显示“领取95折新人优惠券”的功能

http://www.bstcine.com/content/course?cid=42&channel=marketing
&source_user_id=dxgn201352373746PUzFREst7e


-- 等iPhone&iPad审核通过后， 3端统一同时把新功能对外放开
```

- [ ] 1.5-，“WeChat分享按钮” 下方多了一条虚线，视频播放下方有一条黑线， [如图](https://user-images.githubusercontent.com/23466882/35275338-5e259ca8-007a-11e8-8fc5-d468a26b2cf3.png) 
```
http://www.bstcine.com/content/course?cid=d011494383315370pGYd8bbwtZ
视频播放下方的黑线属于图片比例问题，此处的比例为840/472，不是严格的16/9，不一致的比例会造成上下或是左右的黑边
```
- [ ] 1.8-，提供正式的对外测试连接（确保7年级有数据）
http://www.bstcine.com/vocabtest/
```
提供给Larry
```

<br>

## 2 课程详情页 - 测试环境
- [ ] 2.2-， Wechat：领取新人“95折优惠券”，线上“安卓版”使用该“95折优惠券”去购买的话
```
分享人：没有获得10%的积分
```
<br>

## 3 词汇测试
- [ ] 3.1-， 需要提供 “学龄前” 与 “成人” 的词汇区间
- [ ] 3.2-， 当某个区间占 0%， 就不需要显示在饼图中

<br>
<br>

## Nice To Have：
- [ ] 1.21- 1.1.5. 分享至朋友圈返回至课程详情页时，优惠信息刷新了2次 
- [ ] 1.22-1.2.4 分享给朋友的消息需要有文字描述及善恩标志， [image](https://user-images.githubusercontent.com/32290407/34593293-f34fe29a-f204-11e7-8210-c7115614c192.png)

**Comment by joelin109** [comment]
## PC-2.0.2 发布 - 2018-01-19

**Comment by itwangxiang** [comment]
## Android
- 线上版本：分享的用户无法获得新用户95折购买的10%积分

**Comment by iYuanYuan2** [comment]
3.2 H5-商城：课程详情页 - 可扫二维码跟踪
- iPhone（线上版本代码）@Alice

**测试了以下几种情况，没有发现和本次测试主题相关的问题。但是有发现和本次测试主题无关的问题。**
具体见下：
_测试场景：_
1、在我自己分享到微信朋友圈的课程链接，点击详情页，领取95折优惠券；
2、在党坤分享到微信朋友圈的课程链接，点击详情页，领取95折优惠券；
3、卸载微信和支付宝；kim通过微信好友分享课程链接给我，点击详情页，领取95折优惠券。

_测试结果：_
**测试后没问题：**
1、如果是通过我自己分享的课程链接领取95折优惠券，可以享受95折优惠，但是我没法得到10%的积分；
2、如果是通过好友分享（无论是分享到朋友圈，还是微信好友分享）的课程链接领取95折优惠券，可以享受95折优惠，好友可以得到10%的积分；
**测试中发现的问题：**
1、90%的课程详情页无法分享成功；
2、购买成功后（和进入订单页面），点击“立即分享得10%积分”没反应（魔法手指和阅读理解这两门课程有这种情况，而新概念2没有出现这种情况）
3、购买成功后的界面显示的文字和图片不一致：图片为公众号的二维码，而文字会误以为这是小助手的微信二维码。
4、卸载微信和支付宝的情况下，购买成功后（和进入订单页面），点击“立即分享得10%积分”，提示“您尚未安装微信，请安装后重试，或选择支付宝支付”中的“选择支付宝支付”不符合当下的场景，应该去掉。
