### ISSUE TITLE
PC- 安全: 使用第三方云存储可随时为课程图片加水印

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#253]
### 第三方云存储：（`七牛`  or ` 阿里`)
- 阿里云OSS
- 七牛云存储
```
可为课程的图片加水印
```

https://developer.qiniu.com/dora/manual/1316/image-watermarking-processing-watermark
https://www.cnblogs.com/kenshinobiy/p/4286499.html

```
1. 先确认Solution， 选那个云存储
2. 给100张图片加水印，确认时间成本
```
### 价格表
https://www.aliyun.com/price/product?spm=a2c4g.11186623.2.11.3yuY91#/oss/detail

### Step
- 数据迁移
   - [ ] OssImport [安装](https://help.aliyun.com/document_detail/57053.html?spm=a2c4g.11186623.6.1075.xEDO6j) 
   - [ ] OssImport 导入
- [图片处理](https://help.aliyun.com/document_detail/50039.html?spm=a2c4g.11186623.6.758.sPMq8I) ???
   - 图片规格：定义几种分辨率的图片规格
      - 480_272
      - 848_480
      - 1280_720
   - 水印格式：logo 水印、id 水印、等等
- API 支持
   - 集成 [Node SDK](https://help.aliyun.com/document_detail/32068.html?spm=a2c4g.11186623.3.3.qOZRue)
   - [上传](https://help.aliyun.com/document_detail/32072.html?spm=a2c4g.11186623.6.748.4ZW9tS)
      - 生成 `Object key`，上传文件到 `Oss`
      - 保存 `Object key` 到数据库
   - HTTP下载
      - [图片处理](https://help.aliyun.com/document_detail/50039.html?spm=a2c4g.11186623.6.758.sPMq8I)
      - [签名Url](https://help.aliyun.com/document_detail/32073.html?spm=a2c4g.11186623.6.749.AuUkMb)
   - [域名绑定](https://help.aliyun.com/document_detail/32076.html?spm=a2c4g.11186623.6.751.RBXxBx)

<br>

#227

**Comment by itwangxiang** [comment]
# 原图
http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?Expires=1517564198&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=P%2B9hJAjpG3o8ropuWkS6AITrPas%3D
![原图](http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?Expires=1517564198&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=P%2B9hJAjpG3o8ropuWkS6AITrPas%3D)

# 480
http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img480&Expires=1517563967&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=bNwQzCLqZQeprxK7VYJMCcBvjYM%3D
![480](http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img480&Expires=1517563967&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=bNwQzCLqZQeprxK7VYJMCcBvjYM%3D)

# 720
http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img720&Expires=1517563976&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=HBmRSFT%2B%2FwpkGoYIY8rC046H8aQ%3D
![720](http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img720&Expires=1517563976&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=HBmRSFT%2B%2FwpkGoYIY8rC046H8aQ%3D)

# 1080
http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img1080&Expires=1517564210&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=OG3xgFrwqTGkf3S3C5MI4NHvpyU%3D
![1080](http://27go.oss-cn-qingdao.aliyuncs.com/171847890S6CDrCH.png?x-oss-process=style/img1080&Expires=1517564210&OSSAccessKeyId=TMP.AQGo_XbRKTIQvAjb7Hz3uXCie6tgCPKPjTmqc3xEnvG-YE1HZEDwkyYZkPATAAAwLAIUIngQXzdREiPIJqenzDKDLXPCCPwCFHwL48zvay1zJcs-XPX10G6QC_aR&Signature=OG3xgFrwqTGkf3S3C5MI4NHvpyU%3D)

**Comment by itwangxiang** [comment]
## 比较（七牛、阿里）
- 图片清晰度：七牛 > 阿里
- 图片大小：
   - 原图（1.81m）
   - 480_272 (七牛：183kb,阿里：165kb)
- 图片处理时间

**Comment by itwangxiang** [comment]
[七牛](http://p3nqde6cj.bkt.clouddn.com/m1.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m1.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

[七牛](http://p3nqde6cj.bkt.clouddn.com/m2.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m2.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

[七牛](http://p3nqde6cj.bkt.clouddn.com/m3.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m3.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

[七牛](http://p3nqde6cj.bkt.clouddn.com/m4.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m4.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

[七牛](http://p3nqde6cj.bkt.clouddn.com/m5.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m5.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

[七牛](http://p3nqde6cj.bkt.clouddn.com/m6.png?imageView2/1/w/480/h/272/q/75)
![七牛](http://p3nqde6cj.bkt.clouddn.com/m6.png?imageView2/1/w/480/h/272/q/75)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75)

**Comment by itwangxiang** [comment]
## 链接
七牛
http://p3nqde6cj.bkt.clouddn.com/media_image.png

http://p3nqde6cj.bkt.clouddn.com/media_image.png-480_272
http://p3nqde6cj.bkt.clouddn.com/media_image.png-848_480
http://p3nqde6cj.bkt.clouddn.com/media_image.png-1280_720

http://p3nqde6cj.bkt.clouddn.com/media_image.png?imageView2/1/w/480/h/272/q/75|imageslim
http://p3nqde6cj.bkt.clouddn.com/media_image.png?imageView2/1/w/848/h/480/q/75|imageslim
http://p3nqde6cj.bkt.clouddn.com/media_image.png?imageView2/1/w/1280/h/720/q/75|imageslim

阿里
http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png

http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=style/480_272
http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=style/848_480
http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=style/1280_720

http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=image/resize,m_fill,w_480,h_272,limit_0/auto-orient,1/quality,q_75
http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=image/resize,m_fill,w_848,h_480,limit_0/auto-orient,1/quality,q_75
http://27go.oss-cn-qingdao.aliyuncs.com/media_image.png?x-oss-process=image/resize,m_fill,w_1280,h_720,limit_0/auto-orient,1/quality,q_75

**Comment by itwangxiang** [comment]
## 效果图 (1280*720)
[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

[阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m7.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m7.png?x-oss-process=image/format,jpg/resize,w_1280,h_720)

**Comment by itwangxiang** [comment]
watermark,text_d3d3LmJzdGNpbmUuY29t,type_d3F5LXplbmhlaQ,size_40,t_100,color_000000,g_south,y_10,x_10

**Comment by itwangxiang** [comment]
## 原图JPEG
- [m1](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m1.png?x-oss-process=image/format,jpg)

- [m2](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m2.png?x-oss-process=image/format,jpg)

- [m3](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m3.png?x-oss-process=image/format,jpg)

- [m4](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m4.png?x-oss-process=image/format,jpg)

- [m5](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m5.png?x-oss-process=image/format,jpg)

- [m6](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m6.png?x-oss-process=image/format,jpg)

- [m7](http://27go.oss-cn-qingdao.aliyuncs.com/m7.png?x-oss-process=image/format,jpg)
![阿里](http://27go.oss-cn-qingdao.aliyuncs.com/m7.png?x-oss-process=image/format,jpg)

**Comment by itwangxiang** [comment]
watermark,text_d3d3LmJzdGNpbmUuY29t,type_d3F5LXplbmhlaQ,size_40,t_100,color_000000,g_south,y_10,x_10
