### ISSUE TITLE
H5-商城：官网首页 - http://www.bstcine.com/ 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#256]
### 需求
```
PC: 一行显示4个课程
iPad 横版：一行显示4个课程
iPad 竖版：一行显示3个课程
iPhone：一行显示2个课程， 没有“Tag选课模块”

```

<br>

### UI设计
  - PC：see UI.PC
  - Pad：PC-H5：新版的首页-添加课程筛选功能 - UI.Pad （#193）
  - Phone：see UI.Phone
```
Phone UI与原版类似, 调整之处：
- 课程目录：可以先取消不要
- 课程列表：与Phone App类似，2课程间留有间距
```

**Comment by joelin109** [comment]
## UI.PC
![361512120116_ pic_hd](https://user-images.githubusercontent.com/23466882/33476295-7236f256-d6bc-11e7-94ff-59f8f263dc03.jpg)

**Comment by daweilv** [comment]
宽屏 滚动 banner 宽高

视频课程、教材教辅 需后台可配置

手机版 顶部栏半透明，覆盖在banner下，logo去掉

手机版 大红色登录按钮，隐藏到侧边导航中

授课老师、授课时长，全平台统一，要加全加，要去全去

滚动 banner、公告全平台保留
