### ISSUE TITLE
iPad-商城：课程详情页-减少加载时间提升性能

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#268]
## 性能优化
- [ ] 1. 把H5文件放到本地项目中
- [ ] 2. 每次App启动， 确认一下H5文件是否需要更新

**Comment by AaronLiDangkun** [comment]
#### 解决方案：

- 1.H5完整文件预先放置到资源文件包中，并标记该资源包的创建日期（时间戳）
- 2.程序启动时，检测缓存沙盒中是否存在 H5资源
- 3.如果沙盒中不存在H5资源，则拷贝资源文件中的完整文件夹到沙盒中，并将标记时间写入偏好设置
- 4.如果沙盒中已存在 H5资源，则比较沙盒资源和资源包创建时间，
    如果资源包中的创建时间比沙盒资源更新时间新，
    则仍然拷贝资源文件到沙盒中，并更新偏好设置中的时间
- 5.处理完成本地资源包后，访问网络上的 H5资源包，比对网络资源包的更新时间和本地更新时间
- 6.如果网络资源包的更新时间大于本地更新时间，则下载资源包，并一一覆盖对应的资源文件，
    否则不做下载处理，结束资源更新
