### ISSUE TITLE
H5-商城：课程详情页 - 详情内容与Header显示的是否登入状态不一致

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#271]
## 课程详情页
- 详情内容显示需要登入
- header显示我已经登入

```
- 整个网站都有这个问题，某些时刻有的页面显示已经登入，有的页面显示未登入
```

**Comment by daweilv** [comment]
![cookie](https://user-images.githubusercontent.com/7405300/36722634-0058ad10-1be9-11e8-8e6a-a4b81dac0941.png)
