### ISSUE TITLE
H5-购买与支付: 结算中心&提交订单&收银台&支付成功 功能整合

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#274]
## 需求
- 把购买与支付整个流程都替换为React的H5
```
- 目前情况：收银台&支付功能仍然不是React的H5
- 把整个 结算中心&提交订单&收银台&支付成功 都改为 新H5
- 使用V2的API
```

#279

**Comment by daweilv** [comment]
已更新到 apptest，需要覆盖
1. pc web 微信二维码支付
2. pc web 支付宝pc支付
3. ios web 微信mweb支付
4. ios web 支付宝mweb支付
5. android web 微信mweb支付
6. android web 支付宝mweb支付
7. ios 微信浏览器内支付
8. android 微信浏览器内支付
9. ios app 支付
10. android app 支付
