### ISSUE TITLE
web-网站：官网上的善恩logo需要统一，由原来的“波士顿善恩教育”改为“善恩英语”

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#28]
需求未定

```
Status: ?
```

**Comment by joelin109** [comment]
学习首页的网页底部信息最好跟网站首页保持一致
```
All Rights
```

**Comment by zhuyichun** [comment]
![1 pic](https://user-images.githubusercontent.com/20130469/32764569-2cc8e766-c941-11e7-8518-7707b40e358d.jpg)
web首页这个背景图上的文字是否也要更改为善恩英语
