### ISSUE TITLE
 iOS-商城：商城首页-根据后台配置及相应规则, 偶尔会弹框提示

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#292]
#### 功能1
 根据管理后台的配置，有的信息需要展示给所有用户，有的信息需要展示给购买过某些课程的用户

<br>

-  客户端在启动后，首页根据规则弹窗展示信息。
```
  - 最新规则：每8个小时弹1次
```
-  弹窗在每次启动时只展示一条信息。
-  弹窗包含内容和取消按钮， 如UI。
```
  -  弹窗宽度为满屏宽度的80%，居中
  -  用户点击内容按钮，将关闭弹窗，并展示内容信息（跳转H5页面或课程详情）。
  -  用户点击取消按钮，直接关闭弹窗。
```

<br>

#### 功能2 #330
-  首页右上角有一消息入口 （如UI)，包含所有需要提供给用户的消息列表，
    用户可以通过点击消息展示内容信息。
-  消息列表中的内容需要提供删除功能。

**Comment by AaronLiDangkun** [comment]
#### 需求描述：根据一定的配置和规则，弹窗提示用户

**Comment by AaronLiDangkun** [comment]
#### 需求描述：根据一定的配置和规则，弹窗提示用户

- 服务端根据需要，配置弹出频率和弹出范围
- 弹窗内容的处理形式与 banner 相同，
    一种为链接到 H5界面，
    另一种为跳转到课程详情。
- 客户端根据配置参数，决定弹出的频率

**Comment by AaronLiDangkun** [comment]
#### Solution:

- 客户端通过 api 获取需要弹出内容和弹出参数，
    服务端根据一定规则，在该 api 中只会提供一条弹出信息
-  弹窗内容的处理形式与 banner 相同，
    当用户点击弹窗内容时，一种会跳转到响应的链接 H5，另一种跳转到对应的课程
-  根据需要，在弹窗出现后，客户端在一定时间内不再访问 api 获取弹窗信息

**Comment by Anawangqi** [comment]
1.弹窗消息
![-1](https://user-images.githubusercontent.com/32318334/36837405-4567d77a-1d77-11e8-9d24-245379f6ca93.png)

2.消息图标入口
![-2 2](https://user-images.githubusercontent.com/32318334/36837416-4cd4de2c-1d77-11e8-801f-aa0049bb9b40.png)

3.消息列表
![-3](https://user-images.githubusercontent.com/32318334/36837463-6b53063a-1d77-11e8-94bd-fb68579fe45b.png)

**Comment by zhuyichun** [comment]
####  预置条件：
消息模板频率设置为0.00068天一次，换算约1分钟1次
#### 步骤：
打开APP商城首页等待查看
#### 预期结果：
每分钟弹窗
#### 实际结果:
只在刚安装后第一次打开app弹窗
```
消息模板设置：http://apptest.bstcine.com/table/MsgTemplate
```
