### ISSUE TITLE
 API-学习系统: 课程是有有效期的，用户不允许观看已过期的视频课程

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#293]
## 需求
```
- 目前购买毅学小班的课程
  - 如果购买毅学小班前， 已经购买过对应的视频课程，那该课程有效期是永久的
  - 如果购买毅学小班前，没有买过对应的视频课程，那该课程是有有效期的

- 不在有效期范围的课程， 不应该显示在我的学习里面种
- 已购买过，但有效期结束的课程， 在课程详情页应该可以继续购买
```

<br>

#### 更新 - 优先级

- [x] 1. 我的学习: 课程有有效期控制
- [ ] 2. 订单表：如果订单之间有“主-明细”的概念，表中需要有清晰的表达 (#305)
- [x] 3. 对毅学小班：提供批量开通- 购买毅学小班的所有用户的视频订单（有有效期）
```
- 已购买过视频课程的不用生成新订单
- 未购买过的， 生成一个有有效期的视频订单 （类型： 线下学生，金额：原价-升级价）

  - 18-03-02
```

**Comment by iott** [comment]
Url | Desc | Explain
-|:- |:- 
APIURL_Content_Home | 首页| 用户登录标识已购买课程
APIURL_Content_Course_Detail | 课程详情 | 用户登录判断是否购买
APIURL_Content_Lesson_Detail|课内容|学习权限过滤
APIURL_User_Content_Course_Mylist|学习列表|课程过滤
APIURL_Content_Chapter_ListWithMedia|课程目录包含media信息|权限过滤
APIURL_Order_PreCalculatePrice|订单预计算|检查是否已购买
APIURL_Order_Create|创建订单|检查是否已购买

?  订单列表&订单详情

**Comment by joelin109** [comment]
订单表的数据完善放在 #305
