### ISSUE TITLE
PC-后台管理: 课程管理-制作课件- 上传课件存放到OSS

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#295]
#289，#297
## 课程管理-制作课件 需求
- 校验：添加一个新的课程 & 修改一门现有的课程
```
1. 上传课件, 保存到OSS，http://oss.bstcine.com/kj
2. 需要保存图片：
- JPG格式原图 < 1 M
- 及加过水印的图片 <500K



已有信息 - 服务器上的现状：
- PNG格式原图 2~3 M
- 及加过水印的图片 <100K
```

**Comment by kimliss** [comment]
### 准备
- [x] [设置 Oss 跨域规则](https://oss.console.aliyun.com/bucket/oss-cn-shanghai/static-bstcine/cors)
- "基础设置“ > "跨域设置" > "设置" > "创建规则"
   ```
   - 来源
   *

   - 允许 Methods
   all

   - 允许 Headers
   *

   - 暴露 Headers
   ETag
   x-oss-request-id
   ```
- [x] [设置STS](https://help.aliyun.com/document_detail/31935.html?spm=a2c4g.11186623.6.645.UU7iE3)
   - 创建角色(ram-oss-all)并授权(AliyunOSSFullAccess)，获取 Arn
   - 创建策略(AliyunSTSAssumeRoleAccessxxxxxxxxxxx),策略内容:
		```
		{
		  "Statement": [
		    {
		      "Action": "sts:AssumeRole",
		      "Effect": "Allow",
		      "Resource": "Arn"
		    }
		  ],
		  "Version": "1"
		}
		```
   - 创建用户(sts-browser)并授权(AliyunSTSAssumeRoleAccessxxxxxxxxxxx)策略
   - 提供用户(sts-browser)的AccessKeyId、AccessKeySecret、RoleArn
- [x] 上传水印图片，[设置上传样式](https://oss.console.aliyun.com/bucket/oss-cn-shanghai/oss-bstcine/image)
   - [水印图(watermark.png)](https://user-images.githubusercontent.com/7286154/37010889-ad126610-2128-11e8-8d1d-0f6a17b2fb2d.png)

   - 样式 （watermark_cine）
   ```
   image/auto-orient,1/quality,q_90/format,jpg/watermark,image_d2F0ZXJtYXJrLnBuZz94LW9zcy1wcm9jZXNzPWltYWdlL3Jlc2l6ZSxwXzEwMC9icmlnaHQsMC9jb250cmFzdCww,t_100,g_center,y_0,x_0
   ```

<br>

### code
- [x] 新增API - [创建 STS服务 ](https://help.aliyun.com/document_detail/28756.html?spm=a2c4g.11186623.6.676.oRraWy)
- [x] [集成Browser-JS-SDK](https://help.aliyun.com/document_detail/32069.html?spm=a2c4g.11186623.6.763.4gt38D)
- [x] 上传图片-原图需要在前端进行格式转换且相应压缩
```
格式转换为：JPG
压缩大小：< 1M

 - 转PNG > JPG, Size基本保留原来的1/3
```
- [x] 制作课件上传: 单个上传 & 批量上传
```
原图保存 OSS:  `kj/2018/03/06/132910789S4wXUjn.jpg` 
```
- [x] 制作课件上传: 给上传的课件图片加水印处理，并保存在OSS
```
课件保存 OSS: `img/course_id/2018/03/06/132910789S4wXUjn.jpg`
```

**Comment by itwangxiang** [comment]
## status
> 图片加水印，无法监听是否状态 `跨域问题`
