### ISSUE TITLE
iOS：提供一个最新的版本支持iOS 10 及 iOS 11

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#3]

**Comment by AaronLiDangkun** [comment]
此问题已完成，已推送到 https://fir.im/cineEducation

**Comment by AaronLiDangkun** [comment]
问题1: ios11系统打开 app 闪退现象.
    原因：ios11重写UITabBarConroller自动布局方法viewWillLayoutSubviews，对 tabBarItem修改内边距时，系统出现了循环调用viewWillLayoutSubviews，卡住后续任务，并造成内存持续增涨，超出内存警告范围，出现闪退现象。
    解决方法：取消修改tabBarItem的内边距，取消重写UITabBarController的viewWillLayoutSubviews方法。
问题2: 在播放器中，对于章节数量较多(10个以上)的课程，滑动出左侧目录后，点击章节头，打开所有章节列表，在打开到最后几个章节时，出现章节混乱，同一章节出现两次等现象
    原因分析：Xcode9编译器在编译 UITableView 时，会默认打开tableView自动计算行高，组头高度，组脚高度的功能。这样以来，原先固定的行组高度被改变，出现重叠，重复现象。
    解决方案：手动关闭 tableView 的自动计算高度功能，同时检查项目中的所有tableView，对于固定高度单元格的，全部手动关闭自动计算高度功能。
