### ISSUE TITLE
iOS-商城：商城首页-根据API显示相应的Tab（如新增在线小班）

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#302]
## 需求
```
1. Tab List：由API 返回的数据决定的
2. Tab 显示为文字还是图片：由API 返回的数据决定的
```

**Comment by joelin109** [comment]
## Tab 为 图片时的UI：
![1531519813192_ pic](https://user-images.githubusercontent.com/23466882/36829004-1004b5d6-1d58-11e8-9370-f62d556078f4.jpg)

**Comment by AaronLiDangkun** [comment]
@daweilv 请协助配置 api 数据（主题文字和图片）

**Comment by zhuyichun** [comment]
step 1:打开app点击tab云端私塾，
step 2:后台配置云端私塾关联课程‘新概念2第二单元’
step 3:刷新app 没有更新这门课程
```
需要退出app后进入刷新才能加载新添加的课程
```

**Comment by itwangxiang** [comment]
@joelin109 
2. Tab 显示为文字还是图片：由API 返回的数据决定的
Tab 不是必须为文字+图片？
