### ISSUE TITLE
PC-后台管理：管理消息推送与设置（Notification&Message）

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#303]
## 需求描述：
```
根据管理后台的配置，2种类型的信息（Notification&Message）
消息针对的用户：
 A: 所有调用API的用户
 B：购买过某些课程的用户
```

1. Notification
用户点击推送， 在App中打开显示，或可以连接到详情页

<br>

2. Message
-  客户端在启动后，首页根据规则弹窗展示信息。
```
存在几天推一次的信息类型
```
-  弹窗在每次启动时只展示一条信息。
```
  -  用户点击内容按钮，将关闭弹窗，并展示内容信息（跳转H5页面或课程详情）。
  -  用户点击取消按钮，直接关闭弹窗。
```

<br>

3. App商城首页：右上角有一消息入口 （如UI)，包含所有需要提供给用户的消息列表，
```
-  每个用户：可以删除自己消息列表中的消息记录。
```

<br>

### 管理消息推送与设置的进度：
- [x]  1. 数据库表设计
- [x]  2. PC-Admin:  各种消息类型的管理页面
- [x]  3. PC-推送：Notification消息推送功能
- [x]  4. API-消息：商城首页-弹框类型消息
- [x]  5. API-消息：用户的消息列表，包含不同类型的消息
- [x]  6. API-消息：用户删除自己的某条消息

API提供给APP，#292

```
2018-03-12 提供 4 的 Deadline
```

**Comment by zhuyichun** [comment]
针对已购买课程的信息弹框错误；
step 1: 下载app，安装后打开app.
step 2：弹框显示。--bug
```
针对已购买课程的信息应该在用户登录后弹框；
```

**Comment by zhuyichun** [comment]
针对已购买课程的信息应该在用户登录后弹框；
实际结果：
- 安装APP后初次打开App,不弹窗- 对的
- 购买了这个课程的用户登录后没有弹窗 -错误
