### ISSUE TITLE
iOS-上线版本的需求和bug

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#31]
## 待解决的Tasks

- 1
- [ ]  在商城-课程详情-立即购买-输入本次使用X积分时，弹出键盘掩盖住输入的积分；
![image](https://user-images.githubusercontent.com/32290407/31041430-c8d2a0c2-a5c7-11e7-875b-6b53fb8969ae.png)

<br>

- 2
- [ ]   分享已经购买的课程成功之后需要弹窗提醒本次分享获得了X积分；
![image](https://user-images.githubusercontent.com/32290407/31041433-e0afc1a2-a5c7-11e7-8ee6-7c5dcb8b3bdb.png)

<br>

- 3
- [ ]  在商城-课程详情-立即购买-本次使用的积分超过课程实付金额，超过的积分仍然会被扣除

<br>

- 4
- [ ] 没有购买过课程的用户，分享APP也可以获得积分

<br>

- 5
- [ ]  课程播放界面显示的当前播放课程标题需要命名为章节名/lesson名
![image](https://user-images.githubusercontent.com/32290407/31041619-f0749268-a5ca-11e7-9928-33111959c837.png)
![image](https://user-images.githubusercontent.com/32290407/31041603-a7ca1cea-a5ca-11e7-8620-0088cb01e169.png)

<br>

- 6
- [ ]  套餐升级页面中间会有一部分已购课程内容显示，已购买的标志会在整个课程名称后面，但是在手机端由于屏幕比较窄，后面的内容是显示不出来的。建议在这个模块左上角添加一个“已购课程”的大标题
![image](https://user-images.githubusercontent.com/32290407/31041738-0e86762a-a5cd-11e7-9373-0fcf478b5cfb.png)

<br>

- 7
- [ ]  在商城-课程详情-立即购买-优惠券-添加-输入优惠券号码-当输入的优惠券不符合使用条件时需要有相关的提示信息
## bug描述

**Comment by joelin109** [comment]
请创建相应的Task后关闭
