### ISSUE TITLE
API-学习系统: 针对某些学校的不同年级学生，提供某些课程不同章节的免费试听

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#311]
## 需求
- 某学校的不同年级学生：不同时间段内，可以免费试听某课程的不同章节

```
我们现在计划针对国内学校进行“免费课程推广”的营销活动，规则如下：

1、我们给校方推荐我们的课程方案，校方如果接受，
我们让校方提供账号清单，这个账号清单要有一个“统一的学校标识”以及学校的代码

2、我们按照账号清单给该学校开通对应课程的权限，但是这些属于某个学校的“免费课程推广”账号的权限有特殊之处：
（1）在特定时间段内，只有特定章节的访问权限，
      比如，在3.1-3.10之间，这些账号只能访问《动物农庄》的前第一章. 
       3.11-3.20之间，只能访问《动物农庄》的前第二章，等等

（2）如果该账号购买了该课程，则不受以上规则影响
```
```
备注：
不同年级的学生：可通过后台配置，某时间段内，对不同课程的章节有访问权限
```

**Comment by daweilv** [comment]
拟添加一个字段两张表
table:t_user
batch_no

table:access_course
id
course_id
batch_no

table:access_course_lesson
id
course_id
lesson_id
batch_no
effective_at
expire_at


select lesson_id from access_course_lesson
where batch_no='jiyang2012' 
and course_id='42'
and effective_at>= now()
and expire_at<=now()
