### ISSUE TITLE
PC-Tool: 校验Lesson的课件数据是否都存在OSS

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#317]
属于issue, #289

需求：
- [x] Step1  提供一个API：更新每个Lesson的检查校验结果
```
API命名：
exports.APIURL_Tool_Content_Lesson_CheckStatus = "/api/tool/content/lesson/checkStatus"  
or
exports.APIURL_Tool_Content_Lesson_CheckMedia = "/api/tool/content/lesson/checkMedia"   


更新：
UPDATE  `content_lesson`  SET `check_status` = 1 WHERE `id` = Lesson_ID                           
```

<br>
<br>

- [x] Step2  提供一个Tool：根据每个Lesson的课件信息，确认每个课件数据是否都存在OSS
```
每个Lesson校验通过，调用API更新一下数据
```

<br>

```
- Deadline:  2018-03-15
```

**Comment by AaronLiDangkun** [comment]
step1:
  - 已提供"/api/tool/content/lesson/checkStatus" 标准v2 API

**Comment by zhuyichun** [comment]
测试demo：http://apptest.bstcine.com/learn/lesson/18614461034287085904103296?content_id=18614461048568254670195981 在重点target4
