### ISSUE TITLE
H5-测试: 语法和基础阅读能力测试

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#318]
### 原始需求如下:
```
语法和阅读能力测试需求
   a)计时，时间暂定75分钟。
   b)所有的题目在一个web page里，在计时内可以任意修改，也可以随时保存-或者自动保存。时间到了自动终止考试。
   c)判断正误的题目，如果选择“错误”，自动出现输入框，要求测试者输入”如何修改“。
   d)提交后，答案和题目整合成PDF或HTML，由老师人工批改。
   e)老师人工批改后，结果可以录入系统。


需求调整为：
   c)判断正误的题目，如果选择“错误”，要求测试者输入”如何修改“； 如果选择“正确”，要求测试者输入”翻译“
   e)老师通过系统可以直接批改。
 
  - 参考UI


需求更新：2018-04-12
老师要和学生有对应关系，特定的老师只能看到特定的学生对答卷
```

**Comment by Anawangqi** [comment]
1.开始测试
![01 2](https://user-images.githubusercontent.com/32318334/37321467-70e52c00-26b3-11e8-940a-831778edfca9.png)

1.1开始测试-方案2（直接做题页面提示开始测试）
![03](https://user-images.githubusercontent.com/32318334/37324198-01fe30a6-26c3-11e8-8236-f4ccaa8bb8cb.png)

2.学生做题
![02](https://user-images.githubusercontent.com/32318334/37321563-d62b0b16-26b3-11e8-88ba-4fc42ba4b781.png)

3. 老师批改列表
![02](https://user-images.githubusercontent.com/32318334/37321792-e85680da-26b4-11e8-8025-3f91ce69c459.png)

4.老师批改界面
![03 1](https://user-images.githubusercontent.com/32318334/37322142-c9bb6cec-26b6-11e8-87df-421d8fc7db0e.png)

5.批改结果展示
![04](https://user-images.githubusercontent.com/32318334/37323523-53fe430e-26bf-11e8-9b44-d34f6db621fd.png)

**Comment by joelin109** [comment]
### 测试反馈 #361

**Comment by daweilv** [comment]
> 苑老师提出
> 想要把选择题改为点击句子中对应的单词或词组就可选中，不单独显示出ABCD选项，带入感强，节省篇幅。

该需求的问题：这种形式不是通用选择题型，维护试题的时候需要在题干中加入特殊定制，是否实现需要确认。

**Comment by daweilv** [comment]
> 老师要和学生有对应关系，特定的老师只能看到特定的学生对答卷

#### 普通教师
建表 `relation_teacher_student`，使用 teacher_id、student_id 进行多对多关联，根据 teacher_id 检索出对应的 student_id，如果没有匹配的 student_id，则不显示任何试卷。
有批改权限。

```sql
select * from stats_quiz where user_id in (select student_id from relation_teacher_student where teacher_id = ? and delete_by is null ) and delete_by is null
```

#### 督导
`system_config_web_final` 增加 supervisor_ids ，维护特定几个 teacher_ids，拥有督查权限，该 teacher_id 可查看全部试卷。
有预览权限。

```sql
select * from stats_quiz where delete_by is null;
```

#### 默认教师
`system_config_web_final` 增加 default_teacher_ids ，维护特定几个 teacher_ids，拥有默认老师权限，未分配 teacher 的 student 下的试卷会被分配到 default_teacher_ids 下。
有批改权限。

```sql
select * from stats_quiz where user_id not in (select student_id from relation_teacher_student where delete_by is null) and delete_by is null
```

#### 教师账号的优先级为：先判断is默认教师，再判断is督导，再判断is普通教师

**Comment by zhuyichun** [comment]
### Problem:
- 私塾学生没有看到入口
```
Joe：这个链接是直接提供给客户的， 官网没有提供入口
```
