### ISSUE TITLE
PC-OSS: 非课件的Media资源迁移

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#326]
### 后台配置
- [x] 1.1. PC-Admin：后台配置- 图片上传默认都上传到OSS - `Verified in 2019/01/10`
```
Html编辑器里面附件没有上传到OSS
- 如：后台课程编辑
```
- [x] 1.2. PC-Admin：文件上传页面- 提供一个上传入口，资源可上传到`服务器`

### 资源迁移到OSS
- [x] 2.1. 学习系统：课程播放页- PDF习题类型的Lesson对应的PDF文件   -`Verified in www`
- [x] 2.2. 商城：文章 |表：ContentArticle|字段：remark|     -`Verified in www`
- [x] 2.3. 商城：课程详情页-课程概要包含的资源（图片等）-`Verified in www`
```
 |表：content_course |字段：remark|
```
- [x] 2.4. 关于善恩页面：善恩简介 & 管理团队 & 善恩名师 & 私塾导师  -`Verified in www`
- [x] 2.5. 二级页面：私塾导师的头像 & 录课老师的照片 & 精彩文章的封面 & 分级阅读 -`Verified in www`
- [x] 2.6. 商城: 课程相关的资源
```
content_course: share_h5_img varchar(255) h5分享页图片

content_course: featured_videos text 精选视频
- 使用在打卡分享，分享后对应的数据存放在t_sharelog

content_course: video varchar(60) 产品介绍视频 (已经不再使用）
```
```
目前有没有在使用，需要咨询 @daweilv 
by: kim
```
- [x] 2.7.  新闻分类 |表：ContentNewsCategory|字段：img|   - `Verified in www`
- [x] 2.8.  新闻 |表：ContentNews|字段：img|字段：remark|     - `Verified in www`
```
测试反馈：
新闻相关的还有图片没有迁移成功， 如
http://www.bstcine.com/news/70
```

### 遗留待迁移到OSS
- [ ] 3.1. 系统配置表：system_config_web_final
```
建议: 手动迁移 - `Kim`

learn.index - 学习首页 -  2017-07-20 (update_at)
balanceRule- 余额规则页面 -  2017-12-26 (update_at)
webBanner- PC端banner  -  2018-10-23 (update_at)
```
- [ ] 3.2 表：t_sharelog 字段 remark
- [ ] 3.3 表： t_emaillog  字段 body
- [x] 3.4 表：content_quiz_question 字段 steam,options

<br>
<br>
<br>

#### 字段类型为 `text` 
```
-- 已迁移
content_article: remark
content_course: remark,remark_ios,featured_videos
content_lesson:remark
content_news: remark
t_templateemail: body
content_quiz_question: steam,options

-- 未迁移
t_emaillog: body
t_sharelog: remark

- 特殊，建议手动迁移
-- system_config_web_final: remark text 备注
```

#### 字段类型不是 `text` 
```
-- 已迁移
content_course: img,video,share_h5_desc,share_h5_img
content_news: img
content_news_category: img
msg_template: alert_img
t_sharelog: share_imgUrl
t_sharemodaltemplate: slogan_img,next_button,share_button
t_shareparam: share_imgUrl
t_teacher: img,head_img
```

### 澄清解释
迁移的文件规则：`/20[0-9]{2}\/[0-9]{2}\/[0-9]{2}\/.{1,25}\.(gif|png|jpg|jpeg|mp3|mp4|pdf)/gi`

1. 当服务器硬盘撤掉的时候，发给用户带资源的历史邮件会无法访问
```
可以将 www.bstcine.com/f/ 路由重定向到 static.bstcine.com
```
2. t_sharelog、数据量太大，待有空执行
3. t_emaillog 邮件历史数据资源路径无需替换

<br>
<br>

### 澄清- 发布到www流程
- [x] Step1: 运行脚本 （针对2.1 ~ 2.8）
```bash
$node /mnt/web/app.bstcine.com/wwwroot/src/server/test/file_to_oss.js
```

<br>
<br>

### 技术反馈
```
- Status: 
处理中

- Deadline
2019-01-04

- 更新Deadline （2019-01-07）
2019-01-07

- 更新Deadline （2019-01-07 18:00）
2019-01-09
```

**Comment by kimliss** [comment]
## SQL

### 1. 解决图片路径溢出
- [x] WWW
- [x] DEV

```mysql
alter table content_article modify column img varchar(100) ;
alter table content_course modify column img varchar(100) ;
alter table content_news modify column img varchar(100) ;
alter table content_news_category modify column img varchar(100) ;
alter table content_tag_item modify column img varchar(100) ;
alter table t_teacher modify column img varchar(100) ;
```

### 2. 解决文件上传：文件类型太长

- [x] WWW
- [x] DEV

```mysql
alter table t_upload modify column file_type varchar(100);
```
