### ISSUE TITLE
PC-学习系统: 学习首页-手机绑定异常 -紧急

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#329]
预置条件：邮箱注册但未绑定手机的账号

## 重新步骤
step 1:登录www.bstcine.com自动跳转到学习首页，弹出手机号绑定弹窗
step 2:选择手机前缀+81，输入手机号08012345678
step 3:输入验证码5651 系统关闭绑定窗口，后台查询这个账号已经绑定(08012345678)

step 4:系统再次弹出手机号绑定窗口
step 5:选择手机前缀+81，输入手机号08012345678，点击获取验证码提示手机号已经绑定

step 6:选择手机前缀+81，输入手机号08012345679
step 7:输入验证码6153 系统关闭绑定窗口，后台查询这个账号已经绑定(08012345679)

step 8:系统再次弹出手机号绑定窗口

## 问题：
手机号绑定窗口在绑定成功后, 不应该再次弹出
```
测试环境：
MAC : Chrome
win7 : Chrome
```

**Comment by itwangxiang** [comment]
1.  因服务器 session => token 迁移导致
2. 问题发现前已经在测试服务器修复
3. 已同步到正式服务器
