### ISSUE TITLE
api-一键分享app积分逻辑修改

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#33]
积分规则
> * 必须登录才可以分享
> * 用户每日通过分享APP获得的积分数由后台做成可配置的，默认每日可获得3个积分，每日打卡总次数不限
> * 用户每次分享APP可获得1个积分
> * 用户分享APP可累积获得总积分=用户购买的所有课程累积的实付总金额*1%(用户购买的所有课程累积的实付总金额低于1000元，分享可获积分上限为10个积分)
> * 没有购买记录的用户，登录后也可以分享，分享可获积分上限也为10个积分

**Comment by iott** [comment]
1.“每天控制2次分享上限”，的意思是不是每天只能分享2次
2.“没有购买记录的用户，登录后也可以分享，分享可获积分上限也为10分”，未购买的登录用户，积分上限为10分。对于购买的用户如果总积分不足10分时，积分上限为实际积分值还是10分
3.如果该用户可获得的积分已经全部领取完毕，是否允许分享，如果可以分享是否还要对“每天控制2次分享上限”做限制
