### ISSUE TITLE
PC-后台管理: 课件迁移&上传OSS- 遗留问题

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#337]
### 11. 课件原件迁移： 课件原件<1M的.JPG 文件迁移到OSS  -`Kim`
- [ ]   OSS课件资源- 课件原件格式：.JPG  （< 500 K)
- [x]   OSS课件资源- 不应该存在 PNG 文件    -`P1`

<br>

- [ ] 12. 课件上传时： 课件原件>1M的.JPG 文件， 未转换为合理Size
```
- 上传文件为大SizeJPG类型文件时， 未做转换与压缩处理
```
<br>

- [ ] 13. 课件上传时：图片加水印, 无法确认是否添加成功
```
无法监听是否状态 `跨域问题`
```

**Comment by zhuyichun** [comment]
-[ ] 学习页面使用的课件播放图片路径是阿里返回来路径，需更改为域名路径
