### ISSUE TITLE
iOS-学习系统：播放界面课程标题

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#34]
#### 课程播放界面显示的当前播放课程标题需要命名为章节名/lesson名</br>
![image](https://user-images.githubusercontent.com/32290407/31041619-f0749268-a5ca-11e7-9928-33111959c837.png)
![image](https://user-images.githubusercontent.com/32290407/31041603-a7ca1cea-a5ca-11e7-8620-0088cb01e169.png)

**Comment by limingLiuBaBa** [comment]
是否会显示chapter 是由后台配置,换句话说,就是目前的目录里的名称有的直接是lesson,有的是chapter/lesson. @joelin109
