### ISSUE TITLE
iOS-APP：测试问题反馈列表 - V2.3.1

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#341]
## Must Fix
- [ ] 1.  iOS-商城:  课程详情页- “新概念2 1-24课”，在课程概要点击链接，出现白屏 @AaronLiDangkun @daweilv 
```
status:fixed
solution：使用H5 url
```

- [x] 2.  iOS-学习:  分享-学习新上架测试网新上传的上架课程‘测试课程’,点击学习也分享，闪退
```
API待改进， 如果后台没有配置直接拿封面
```
 - [x] 3. iOS-登录与注册: 香港手机号和美国手机号设置密码时都无法成功 #308 
```
- 正式网正常支持， 测试网有问题
- 为什么？
```

```
status:无法重现
```

 - [ ] 4. ipad 版 APP 下载课程后，在“我的下载”点击进入课程学习，播放完一张ppt后不能自动播放到下一张
```
Status: 无法复现此问题
```

<br>
<br> 

## Nice to have
- [ ] 3.1  iOS-下载：下载列表一直显示正在下载，但下载不了文件  --bug
```
step 1 : 点击树屋2下载lesson1,lesson2,lesson3,lesson4
step 2：进入我的下载 查看下载中列表显示lesson1 已下载60%，其余的3个lesson正在下载
step 3 : 删除正在下载的lesson1，暂停马上开始下载的lesson2
step 4 : 显示下载中， 但无法下载 （问题）
结果：
    1、后续的下载文件显示下载中，但不下载 
    2、已下载列表中显示lesson1，点击播放一直加载中
    3、我的学习目录结构中树屋2lesson1是否下载的状态不对
```

- [ ] 3.2  iOS-下载：下载文件下载到90%时候删除该下载，这个Lesson会出现在意下载文件列表中，学习界面的目录结构显示状态也为已下载。但不能播放。 --bug

**Comment by zhuyichun** [comment]
##  iOS-学习中心
- [ ] 1.  iOS-学习:  分享-学习新上架测试网新上传的上架课程，课程名称 ‘测试课程’,点击学习也分享，闪退
- [ ] 2.  iOS-学习:  无效账户点击学习节点提示错误
```
step 1：设备A登录账户jerry_test/q111111，进入我的学习找到'新概念1'
step 2：打开'新概念1'菜单目录
step 3：设备B登录账户jerry_test/q111111
step 4：点击设备A的‘新概念1课程目录节点’，提示信息错误
```

**Comment by zhuyichun** [comment]
## 1.H5-支付
- [ ]  1.1 支付宝支付异常
```
step 1: 手机浏览器访问官网并登陆账号A
step 2:微信浏览器登陆账号B购买课程，支付方式选择‘支付宝支付’
step 3:微信选择支付宝支付需要跳转到浏览器支付，跳转到浏览器弹窗提示‘order_not_belogin’--错误
step 4:关闭弹窗，选择‘微信支付’或‘支付宝支付’，弹出‘正在支付...’页面，后续没有反应 --错误
```

**Comment by Anawangqi** [comment]
PC：我的图标显示不全，书籍已购买后，书籍详情无显示“已购买”状态
![wechatimg35](https://user-images.githubusercontent.com/32318334/38721551-47e257dc-3f2d-11e8-9f73-4fca9ed1a8cc.jpeg)
