### ISSUE TITLE
Android-APP：测试问题反馈列表 - V2.3.1 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#342]
## 遗留问题
- [x] 5.1 课程详情页:  试听  app切换到后台，还是正常播放
- [x] 5.2 课程详情页:  分享按钮能连续多次点击弹出多个分享微信界面

<br>
<br>
<br>

## Android发布前（iOS提交审批）
- [x] PC-OSS：2018-03-10后，课件有过调整的的课程需要重新迁移课件
- [ ] PC-Admin：设置Tab与课程的关联关系

**Comment by zhuyichun** [comment]
- [ ] 2.  iOS-学习:  无效账户点击学习节点提示错误
```
step 1：设备A登录账户jerry_test/q111111，进入我的学习找到'新概念1'
step 2：打开'新概念1'菜单目录
step 3：设备B登录账户jerry_test/q111111
step 4：点击设备A的‘新概念1课程目录节点’，提示信息错误，不应该‘提示网络异常，请点击重新加载’

**Comment by joelin109** [comment]
## Android发布前（iOS提交审批）
- [ ] PC-Admin：设置Tab与课程的关联关系
- [ ] PC-OSS：2018-03-10后，课件有过调整的的课程需要重新迁移课件

**Comment by zhuyichun** [comment]
##商城

-[ ]1.商城首页Banner图片被截取了
-[ ]2.商城首页的Tab区块 UI变形了
-[ ]3.商城首页Banner图片跳转到Tab失败

##购买中心
-[ ]1.默认不适用积分购买，点击使用积分的按钮切换状态，会出现正在加载弹窗
