### ISSUE TITLE
API-学习系统: Lesson播放页-树屋3-Lesson13的测验题的答案跟老师提供不一致

### ISSUE THREAD

**Issue by JENNY-BSTCINE** [bstcine/cine-tasklist#349]
树屋测试题部分题目系统的答案跟老师提供的答案不一致。
例如老师给的正确答案是B，但是当选择A选项的时候，系统显示 答案正确。如图所示：
![image](https://user-images.githubusercontent.com/34368941/38069494-4d1e566e-3349-11e8-83a9-c3697f6776f4.png)

**Comment by itwangxiang** [comment]
老师提供的Execl 答案存在空字符
