### ISSUE TITLE
H5-商城：课程试听- 测试问题反馈列表 - V2.3.1

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#350]
## 问题
- [x] 2.  课程试听：希望双击可以暂停
- [x] 课程试听：选集 的这个按钮是不是可以做得明显一点（或者用不同颜色显示）？
```
感觉现在这个版本太不显眼，一眼看过去都没有留意这个 按钮 。
```
新`选集`效果： http://apptest.bstcine.com/content/course?cid=d0114835997465111CS3xyap7H

**Comment by zhuyichun** [comment]
## IOS：
- [ ] 1.课程详情页: 试听 app切换到后台，还是正常播放
## Android：
- [ ] 2.课程详情页: 试听 app切换到后台，还是正常播放

**Comment by JENNY-BSTCINE** [comment]
1、课程试听-IPAD：ipad 版的试听按钮觉得有点小。
2、课程试听：选集 的这个按钮是不是可以做得明显一点（或者用不同颜色显示）？感觉现在这个版本太不显眼，一眼看过去都没有留意这个 按钮 。

**Comment by zhuyichun** [comment]
‘选集’按钮样式要求做的明显
