### ISSUE TITLE
PC-校验: 课件资源- 校验音频&水印图是否正常

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#354]
## P1
- [x] 01 | 《动物农庄》精读课程 | 42
- [x] 02 | 《人类的故事》精读课程 | A011466215703591WQYDRNlWxH
- [x] 03 | 《查理和巧克力工厂》精读课程 | d011453971898316wOnY4sRKIC    -`*****`
- [x] 04 | 核心词汇精讲中级（高考）英语 | d011494899752685PaphkjxWVc
- [x] 05 | 《新概念英语2》第1单元精讲（1-24课） | d011506563599590C2UgTnNssz     -`*****`
- [ ] 06 | 《傲慢与偏见》精读课程 | A011459218776295IcEIrkdZwS       -`*****`
```
共72个Lesson，已查看1-36lesson 。

Jerry
```

<br>

- [ ] 07 | 《夏洛特的网》精读课程 | A0114655235938391eWYkAGPbk      -`*****`
- [ ] 08 | 新SAT阅读精讲 | A011481599400893DAhTPx3J6z
- [ ] 09 | 英语核心文法与写作 | d011501468619447xbQVMHnqJS
- [x] 10 | 新SAT语法精讲 | A011473750883473MfD6eUge7h
- [x] 11 | 《小王子》精读课程 | A011481685662619HkztzzwvxT
- [x] 12 | 托福阅读精讲 | 41
- [x] 13 | 《福尔摩斯探案集-血字的研究》精读课程 | d0114539825439251pL4DiFkem
- [x] 14 | 美国小学Wonders-Reading/Writing Workshop G1精读 | d011504160872085t6qbxdTp6n
```
Ana
```
<br>

- [x] 15 | 英美报刊外教精读-硅谷的江湖 | d0115057906476488ybdGAScTR
- [x] 16 | 英美报刊外教精读-平权法案篇 | d011502846526016MpDBrnsR8p
- [x] 17 | 英美报刊外教精读-美国司法公正篇 | d011504765399556gtA3W7u02U
- [x] 18 | 《新概念英语2》第2单元精讲（25-48课） | d011516617087395ckS4vAhyz8
- [x] 19 | 美国小学Wonders-Reading/Writing Workshop G2精读 | d011505784366675ft1rmKg7xE
- [ ] 20 | 《了不起的盖茨比》-前三章精读课程 | 18614461034287085904103296
```
Penny
```
<br>
<br>

## P2
- [ ] 21 | 托福口语精讲 | A0114848779057234dnkUVbCsu
- [ ] 22 | 《老鼠记者1：遗失的宝藏》精读课程 | d011493960367312X8rrxV7huE
- [ ] 23 | 《棚车少年1-棚车少年》精读课程 | d011493784428589kNbpbsMfF6
- [ ] 24 | 莎士比亚戏剧欣赏 | d011509938661571VgCQV2kadY
- [ ] 25 | 《纳尼亚传奇：狮子、女巫和魔衣橱》精读课程 | d011494383315370pGYd8bbwtZ
- [ ] 26 | 《新概念英语1》第1单元精讲（1-36课） | d011517908975849MRCkWFNEJ9
- [ ] 27 | 美国小学Wonders-Reading/Writing Workshop G3精读 | d011516590268195CUG1x3UMkE
- [ ] 28 | 《神奇树屋1-恐龙谷历险记》精读课程 | A011481356690908FzSf3w6uWp
- [ ] 29 | 《神奇树屋2-迷雾中的骑士》精读课程 | d011489544828252C98UhVm1x5
- [ ] 30 | 《神奇树屋4-海盗的藏宝图》精读课程 | d011500278732891DXFVjw2D47
- [ ] 31 | 《神奇树屋3-木乃伊之谜》精读课程 | d011495510153856gjacku3cUa

## P3
- [ ] 32 | 英美报刊外教精读短篇合集 | d011516845223528q5HesnnRWP
- [ ] 33 | 《魔法手指》精读课程 | d011511510232923n3wnQ4q9R4
- [ ] 34 | 《神奇树屋5-忍者的秘密》精读课程 | A011481593478350BKERXB5gYq
- [ ] 35 | 《神奇树屋6-亚马逊大冒险》精读课程 | d011489544924565QYbxA1ACU6
- [ ] 36 | 高级英语长难句精讲 | d011512542079418DSDrG52yd8
- [ ] 37 | 英美报刊双语精读（2017下半年） | d011503974382830Tcne3UQckf
- [ ] 38 | 托福写作精讲 | d0114835997465111CS3xyap7H
- [ ] 39 | 福克纳经典短篇精读 – A Rose for Emily | d011510214825450dA0Q4mQXjs
- [ ] 40 | 英美报刊外教精读-芝加哥经济学派的瞻前与顾后 | d011508481608443pbrU5Zk01N

**Comment by Anawangqi** [comment]
《小王子》-Chapter 4- Lesson4- 14 无音频

**Comment by itwangxiang** [comment]
### 工具检测结果：
``` log
ECS 上数据损坏
CourseId: A011481685662619HkztzzwvxT ; LessonId: A011486538052553gceBXCdhgy ; OSS：kj/2017/02/23/170605117Szg4JpZ.mp3 ; ECS：http://gcdn.bstcine.com/mp3/A011481685662619HkztzzwvxT/f/2017/02/23/170605117Szg4JpZ.mp3 ;SIZE: 1137B ; ERROR: <nil> ; DEL
CourseId: A011481685662619HkztzzwvxT ; LessonId: A011486539500654Rvj9wAS7wr ; OSS：kj/2017/02/23/170605117Szg4JpZ.mp3 ; ECS：http://gcdn.bstcine.com/mp3/A011481685662619HkztzzwvxT/f/2017/02/23/170605117Szg4JpZ.mp3 ;SIZE: 1137B ; ERROR: <nil> ; DEL

OSS 迁移失败
CourseId: A011481685662619HkztzzwvxT ; LessonId: A011481781707552f8HwtQBu3G ; OSS：kj/2016/12/15/140816801S6xDjfc.mp3 ; ECS：http://gcdn.bstcine.com/mp3/A011481685662619HkztzzwvxT/f/2016/12/15/140816801S6xDjfc.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found)
CourseId: A0114848779057234dnkUVbCsu ; LessonId: A011484891219855Z1mvymvsRU ; OSS：kj/2017/01/20/151436795SaMx8P6.mp3 ; ECS：http://gcdn.bstcine.com/mp3/A0114848779057234dnkUVbCsu/f/2017/01/20/151436795SaMx8P6.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d0114539825439251pL4DiFkem ; LessonId: d011453986022930N1iZ8oN0Pu ; OSS：kj/2018/01/11/190928565STSe10X.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d0114539825439251pL4DiFkem/f/2018/01/11/190928565STSe10X.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d0114835997465111CS3xyap7H ; LessonId: d011519439122386J4mY1AKMtK ; OSS：kj/2018/02/24/102737380Sc6p4gj.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d0114835997465111CS3xyap7H/f/2018/02/24/102737380Sc6p4gj.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011493784428589kNbpbsMfF6 ; LessonId: d011493800268412Kq4x791Gqg ; OSS：kj/2017/05/03/163822952Se406H9.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011493784428589kNbpbsMfF6/f/2017/05/03/163822952Se406H9.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011493960367312X8rrxV7huE ; LessonId: d011499845199672fqQVDXA4Xe ; OSS：kj/2017/07/12/155431136Spbqsxd.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011493960367312X8rrxV7huE/f/2017/07/12/155431136Spbqsxd.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011494899752685PaphkjxWVc ; LessonId: d011495011914739sS6f29CR1S ; OSS：kj/2017/05/23/102239899SxPnvX0.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011494899752685PaphkjxWVc/f/2017/05/23/102239899SxPnvX0.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011494899752685PaphkjxWVc ; LessonId: d0114981212011523vc7p6GkDX ; OSS：kj/2017/06/27/122648504S1Mg953.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011494899752685PaphkjxWVc/f/2017/06/27/122648504S1Mg953.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011505784366675ft1rmKg7xE ; LessonId: d0115076918206660hrnTgGV29 ; OSS：kj/2017/10/25/10045376S3WpDaH.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011505784366675ft1rmKg7xE/f/2017/10/25/10045376S3WpDaH.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011505784366675ft1rmKg7xE ; LessonId: d011507691830518a8huFg2y6Z ; OSS：kj/2017/10/25/101248799SeJctyq.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011505784366675ft1rmKg7xE/f/2017/10/25/101248799SeJctyq.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011509938661571VgCQV2kadY ; LessonId: d0115145387776705BeaKwZqEe ; OSS：kj/2017/12/29/171413484SubKfK0.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011509938661571VgCQV2kadY/f/2017/12/29/171413484SubKfK0.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011512542079418DSDrG52yd8 ; LessonId: d0115125421264093z5eEFjDmU ; OSS：kj/2017/12/07/091600495S7KHhTB.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011512542079418DSDrG52yd8/f/2017/12/07/091600495S7KHhTB.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011512542079418DSDrG52yd8 ; LessonId: d0115125421264093z5eEFjDmU ; OSS：kj/2017/12/07/091601195SQJhFPt.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011512542079418DSDrG52yd8/f/2017/12/07/091601195SQJhFPt.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011512542079418DSDrG52yd8 ; LessonId: d011512544446111A5KMFumzkZ ; OSS：kj/2017/12/07/092833500SkWnuzX.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011512542079418DSDrG52yd8/f/2017/12/07/092833500SkWnuzX.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011516590268195CUG1x3UMkE ; LessonId: d0115204882230413MrhmfjspD ; OSS：kj/2018/03/08/140239446SVJBfAc.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011516590268195CUG1x3UMkE/f/2018/03/08/140239446SVJBfAc.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found)
CourseId: d011516845223528q5HesnnRWP ; LessonId: d011516847514103KtkPzhekms ; OSS：kj/2018/01/25/113536623SzEsBym.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011516845223528q5HesnnRWP/f/2018/01/25/113536623SzEsBym.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found) 
CourseId: d011517908975849MRCkWFNEJ9 ; LessonId: d011518336826722D25WfMJpMY ; OSS：kj/2018/02/11/161958770ScYnbwK.mp3 ; ECS：http://gcdn.bstcine.com/mp3/d011517908975849MRCkWFNEJ9/f/2018/02/11/161958770ScYnbwK.mp3 ;SIZE: B ; ERROR: oss: service returned without a response body (404 Not Found)
```

**Comment by joelin109** [comment]
11 | 《小王子》精读课程 | Lesson 4 | 14
21 | 托福口语精讲 | Lesson 3 | 5
13 | 《福尔摩斯探案集-血字的研究》精读课程 | Lesson 12 | 16
4 | 托福写作精讲 | Lesson 1 - The Writing Process 写作步骤 | 12
5 | 《棚车少年1-棚车少年》精读课程 | Lesson 2 | 9
6 | 《老鼠记者1：遗失的宝藏》精读课程 | Lesson 13 | 4
7 | 核心词汇精讲中级（高考）英语 | Lesson 9 | 13
8 | 核心词汇精讲中级（高考）英语 | Lesson 22 | 18
9 | 美国小学Wonders-Reading/Writing Workshop G2精读 | Week 5: Rights and Rules | 13
10 | 美国小学Wonders-Reading/Writing Workshop G2精读 | Week 4: Preserving Our Earth | 9
11 | 莎士比亚戏剧欣赏 | Lesson 10 明喻与暗喻 | 7
12 | 高级英语长难句精讲 | Lesson 1 The King’s Work | 2
13 | 高级英语长难句精讲 | Lesson 1 The King’s Work | 3
14 | 高级英语长难句精讲 | Lesson 7 Haruki’s Memoir | 2
15 | 美国小学Wonders-Reading/Writing Workshop G3精读 | Reading | 17
16 | 英美报刊外教精读短篇合集 | Unit 12 Highway Deaths & Voting? | 20
17 | 《新概念英语1》第1单元精讲（1-36课） | Lesson 20 - Look at them！ | 4
