### ISSUE TITLE
API-购买与支付: 提交订单时- 提示系统超时及订单前后显示金额不一致

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#357]
课程购买-支付：有用户在安卓手机APP上购买课程（查理和巧克力工厂课程），使用了优惠券，点击 提交订单 时， 显示“系统超时”，一直提交不了订单。

-- From Jenny

**Comment by JENNY-BSTCINE** [comment]
课程购买-支付：有用户在安卓手机APP上购买课程（查理和巧克力工厂课程），使用了优惠券，点击 提交订单 时， 显示“系统超时”，一直提交不了订单。

**Comment by daweilv** [comment]
OrderLogic Line 400 : UserLogic.isAgent 方法未定义，isAgent 原为 V2_UserLogic.js 中的方法，合并代码的时候没合到 UserLogic.js 中。
