### ISSUE TITLE
H5-个人设置: 个人主页 & 积分  & 优惠券等

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#359]
- [x] H5-个人设置: 个人主页 - 首页
- [x] H5-个人设置: 我的积分- 显示积分历史记录 & 积分规则
- [x] H5-个人设置: 我的优惠券- 显示优惠券信息 (#340)
- [ ] H5-个人设置: 我的订单- 显示订单信息  （#369）

```
现有
http://www.bstcine.com/user/mypoint


新版：
http://www.bstcine.com/user

http://www.bstcine.com/user/order
http://www.bstcine.com/user/integral
http://www.bstcine.com/user/coupon
```

测试反馈，#367

**Comment by Anawangqi** [comment]
个人主页-我的界面
![wap_0-1 -20180406](https://user-images.githubusercontent.com/32318334/38788061-41e01e26-4164-11e8-8c00-259b352deb52.png)

**Comment by joelin109** [comment]
# 我的积分UI

**Comment by zhuyichun** [comment]
我的订单待完成
