### ISSUE TITLE
H5-商城：课程详情页- 精读&&音频&&书籍3种课程详情

### ISSUE THREAD

**Issue by Anawangqi** [bstcine/cine-tasklist#36]
- ### 需求
```
```
<br>

- PC-H5 （3种课程）
  - 精读课程详情
  - 音频课程详情
  - 书籍课程详情

<br>

- UI设计
  - UI查看 (已确认)：[ftp://192.168.1.134/www/bstcine/web-ui/course-detail](url)
  - 切图和标注：[ftp://192.168.1.134//www/bstcine/web/course-detail](url)
  - APP：pc-H5: 新版的 精读课程详情&&音频课程详情&&书籍课程详情- UI.Phone （#39）
  - Pad：pc-H5: 新版的 精读课程详情&&音频课程详情&&书籍课程详情- UI.Pad （#181）
  - PC：（#36）

<br>

- 目标（希望）：
3端通用。
Android #173 ，iOS #95

<br>

- 进度
- [x]   pc-H5: 课程详情- .Phone 
- [ ]   pc-H5: 课程详情- .Pad 
- [ ]   pc-H5: 课程详情- .PC 

<br>
<br>

API- #160
APP - #219
测试反馈 - #222

**Comment by Anawangqi** [comment]
精读课程-详情页：
1.登录前
![-1 -0](https://user-images.githubusercontent.com/32318334/31042949-11856da8-a579-11e7-8201-acaa5fa58549.png)

2.登录后
![-1 -1](https://user-images.githubusercontent.com/32318334/31042954-2ef47a28-a579-11e7-9977-f90033032ffd.png)

3，标签滑过提示
![-1 -2](https://user-images.githubusercontent.com/32318334/31043005-fa5ec5ce-a579-11e7-81fa-8ab370e7b516.png)


4.左侧视频课程点击弹出播放
![-1 -3](https://user-images.githubusercontent.com/32318334/31042973-8e13ae98-a579-11e7-8533-ea3e10c579cd.png)

5. 弹出分享
![-1 -4](https://user-images.githubusercontent.com/32318334/31042995-da90e79a-a579-11e7-83fd-2a27825c88a4.png)


音频课程-详情页：
1.默认
![-2 -0](https://user-images.githubusercontent.com/32318334/31042968-6a9a8b3a-a579-11e7-8aaf-ba1f1c809d0f.png)

2.标签滑过提示
![-2 -1](https://user-images.githubusercontent.com/32318334/31042970-782c7268-a579-11e7-8cb6-18d95a057e04.png)

3. 音频课程弹出播放
![-2 -2](https://user-images.githubusercontent.com/32318334/31042974-9a66f196-a579-11e7-9b6b-c1199f525cea.png)

书籍-详情页：
1.默认
![-3 -1](https://user-images.githubusercontent.com/32318334/31042984-b74c8bcc-a579-11e7-8263-d0a6f1bdf568.png)

1.弹出分享
![-3 -2](https://user-images.githubusercontent.com/32318334/31042987-c6781ddc-a579-11e7-9271-d3723b9286ef.png)

**Comment by daweilv** [comment]
# _**上线前需要提供的数据**_

1. 副标题：`泛读十本，不如精读一本`
2. 评价
3. 16:9的产品图

**Comment by daweilv** [comment]
## _**Question:**_
1. 新上线课程没有评论的时候的 UI ?

**Comment by MaryLinker** [comment]
需求修改：
- [ ] 学员评价里面的“用户口碑”不加链接，文字改为“”
- [ ] 领取优惠券页面添加文字“请登录APP前往我的-优惠券进行查看”，“善恩英语APP”需要加上双引号
![image](https://user-images.githubusercontent.com/32290407/34663454-e242bd9e-f491-11e7-80e1-0c048042e960.png)
- [ ] ipad端的课程目录放开
