### ISSUE TITLE
H5-测试：核心语法测试- 测试问题反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#361]
## 问题反馈：学生部分
http://apptest.bstcine.com/tgrammar/quiz

### 做题
- [ ] 1.1.1 ...
```

```

<br>

### 等待批改结果
- [ ] 1.2.1. 学生等待老师批改中， UI提醒 如下：
```
```

<br>

### 查看试卷批改结果
- [ ] 1.3.1. ...

<br>
<br>

## 问题反馈： 教师部分
入口：http://apptest.bstcine.com/teacher/dashboard

### 教师控制页面
- [x] 2.1.1. ...

<br>

### 教师编辑页面
- [ ] 2.2.1. ...

<br>
<br>

### 备注
```
试卷有3种状态：
A：做题的状态
B：批改的状态
C：查看的状态

- A & B & C 是否是同一页面，没有限制
```

**Comment by zhuyichun** [comment]
学生页面
1、学生初始界面添加‘试题只能提交一次’类的提醒，避免学生第一次胡乱答题
2、是否支持答完一部题可以提交保存，不必要全部答完才能提交。避免网络不好，刷新过后又要全部重做一遍
3、提交答案时候，未答的部分题最好有个标识。方便学生定位到这些题目
教师页面：
4、翻译题：提供默认的ABCD的答案错误注释，减少教师的人力
5、选择题：系统判断学生答题，并给出得分

**Comment by Anawangqi** [comment]
1. 老师批改列表
![02](https://user-images.githubusercontent.com/32318334/39037110-17c5b2d0-44b2-11e8-8638-a50571acbac4.png)

2.老师批改中提示
![03-1 _](https://user-images.githubusercontent.com/32318334/39037140-2d181466-44b2-11e8-833a-5d015ae5b616.png)

3. 学生提交答卷-未做题提示
![03-1 _ 1](https://user-images.githubusercontent.com/32318334/39037162-41e6ed04-44b2-11e8-83ce-99697ad71eac.png)

3. 1学生提交答卷-未做题具体题目提示
![03-1 _](https://user-images.githubusercontent.com/32318334/39037242-76c91d44-44b2-11e8-87eb-321b358be537.png)

4. 批改结果展示
![08](https://user-images.githubusercontent.com/32318334/39037268-8ab8d68c-44b2-11e8-839a-14e7502c6fb9.png)

**Comment by daweilv** [comment]
开始测试的弹出框文字&题干描述需要更新

**Comment by zhuyichun** [comment]
手机不能自适应

**Comment by zhuyichun** [comment]
http://apptest.bstcine.com/grammar/quiz学生访问蓝屏
