### ISSUE TITLE
H5-个人设置: 新个人主页- 测试遗留问题反馈

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#367]
- [x] 1. 进入个人中心：http://apptest.bstcine.com/user
```
APP: 个人中心
PC: 我的积分 （user/integral）
```
- [x] 2. 代码规范优化
```
A. 把所有路由的代码都放在
https://github.com/bstcine/cine.pwa/tree/master/src/client/entry/user/userRouter.js
```

**Comment by zhuyichun** [comment]
### 
1、进入个人中心，默认选中状态？
2、个人中心左侧账号旁边有笔的可编辑标志，点击没有反应
3、个人中心，切换banner。A界面跳转B界面中的过渡会加载‘我的积分界面’。
```
如当前是‘我的优惠’，点击切换到‘词汇测试’,跳转过程中会加载并显示‘我的积分’界面
```

### 管理员登录
点击首页-我的-老师批改：
1、界面提示错误
2、批改结果列表显示错误

**Comment by zhuyichun** [comment]
###  4 ipa 浏览器
- [ ]  4.1 个人中心优惠券获取不到数据，显示空白。--概率性出现
- [ ]  4.2个人中心积分获取不到数据，显示空白。--概率性出现
- [ ]  4.3个人中心积分规则获取不到数据，显示空白。--概率性出现
- [ ]  4.4个人中心积分明细列表展示区域高度没有铺满屏幕
