### ISSUE TITLE
PC-Tool: 在线学习沟通工具- Zoom Help

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#368]
#### Step1:  下载客户端
PC:  https://zoom.us/download#room_client
iPhone:   到 `App Store` 下载 `Zoom`
Android：到 `应用市场` 下载 `Zoom`

#### Step2:  免费注册 一个账号
```
免费注册： https://zoom.us/signup


- 已注册的测试账号/密码：dev@bstcine.com / bstcine
```
#### Step4:  登录后
-  4.1. 底部菜单栏：点击`会议`(`Meetings`)，确认已选`总在本机上使用个人...`。
  ```
  点选过一次就好，下次就不用选的
  ```
-  4.2. 底部菜单栏：点击`主页`(`Home`),  然后选择`视频会议`(`Start with video`)
-  4.3. 会议的底部菜单：点击`邀请`（`Invite`),  弹出邀请页面选择点击左下角`复制链接`(`Copy URL`)
- 4.4. 粘贴链接，然后发给学生，等待学生自己加入会议
 ```
 粘贴链接: 点击鼠标右键，选择链接（`Paste`). 
 - 粘贴链接如：https://zoom.us/j/472349849

 ```

##### 澄清备注：
```
第2次会议的时候：
如果第一次会议中4.1已做，就不用发新的链接给学生了（因为`Meeting ID`保持不变）
- 即4.3 & 4.4不用做
```

<br>
<br>

#### Step1:  下载客户端, 然后安装
PC:  https://zoom.us/download#client_4meeting
iPhone: 到 `App Store` 下载 `Zoom`
Android：到 `应用市场` 下载 `Zoom`

#### Step2:  上课前向老师要`Meeting ID`
```
- 如果老师提供url：https://zoom.us/j/472349849
   `Meeting ID`就是：472349849
```

#### Step3: 打开`Zoom`App, 输入`Meeting ID`
```
- 打开`Zoom`App
- 点击`Join a Meeting`
- 输入`Meeting ID`
```

**Comment by zhuyichun** [comment]
- [ ] 1.  简会:  https://www.jhmeeting.com/product#whiteboard
```
优点：可以查看学生网速丢包率
缺点：
     1：不能关闭学生发言
     2：售后慢
```
- [ ] 2.  EEO： https://www.eeo.cn/product.html
```
优点：具有课程日历功能，可以提前查看进度
缺点：不能及时联系和需要机构信息才能体验适用
```

**Comment by zhuyichun** [comment]
-[ ] EE0邮件回复
```
朱老师您好：

很高兴收到您的邮件！

欢迎您到https://www.eeo.cn/login.php 注册成为我们的机构用户，提交认证后，将有14天试用期可以免费体验和测试整体功能。
在您注册认证之后，我们会安排专业的客户顾问团队来跟进您的项目（微信+手机的方式）。
在正式签约合作之后也会有专门的客服小助手团队实时解决您使用上的一些突发问题，请不用担心^^

感谢您对ClassIn的关注！
```

**Comment by joelin109** [comment]
## 拓课
- [ ] 3.拓课：http://global.talk-cloud.net   --
```
测试到期时间：2018-05-27
http://global.talk-cloud.net
企业域名：syjykj
帐号:admin
密码:admin
测试链接：
老师地址global.talk-cloud.net/902048906/10663/1/0
学员地址global.talk-cloud.net/902048906/10663/1/2
老师密码：1111   助教密码：2222    学员密码：3333   巡课密码：4444
```
![default](https://user-images.githubusercontent.com/20130469/39681865-4aa566de-51df-11e8-95a1-9f1ba80e5e99.jpg)
```
录制45分钟课时，录制件大约300M
```

<br>

```
优点：
谷歌浏览器用户可以网页直接访问直播间(其他浏览器需要下载app)
免费提供接口对接官网，可以免登陆唤醒app进入直播间
```
### 费用
```
< 15 元/小时
```
