### ISSUE TITLE
iOS-学习系统：播放时竖屏切换横屏时，左右切换箭头（上一章下一章）变小（被缩放）。

### ISSUE THREAD

**Issue by Anawangqi** [bstcine/cine-tasklist#37]
1. 播放时竖屏切换横屏时，左右切换箭头（上一章下一章）变小（被缩放）。
图示：
竖屏
![wechatimg17](https://user-images.githubusercontent.com/32318334/31044980-b34cd2ea-a59f-11e7-8cc0-988d8c3b7520.jpeg)
横屏
![wechatimg18](https://user-images.githubusercontent.com/32318334/31044986-ceef9dd4-a59f-11e7-835a-310fde9a1d8d.jpeg)

2. 初加载课程时视频长宽比大概在4：3， 课程加载到后跳成了16：9的比例。
加载时：
![wechatimg24](https://user-images.githubusercontent.com/32318334/31045001-124652b2-a5a0-11e7-9fbc-a3cdbc598ec1.jpeg)
加载完成后：
![wechatimg23](https://user-images.githubusercontent.com/32318334/31045005-228140d8-a5a0-11e7-888f-51d9b21a61a9.jpeg)

3. 弹出分享背景没有做黑色遮罩，“勤”字被压扁， 学习字段上下间距偏大
（有重新提供竖屏背景和标注，地址：）[ftp://192.168.1.134/www/bstcine/ios/checkin-share-bg](url)
![wechatimg19](https://user-images.githubusercontent.com/32318334/31045024-6e6c1022-a5a0-11e7-8b7c-5d425af7eaf4.jpeg)

**Comment by limingLiuBaBa** [comment]
修改完成,效果见下图.
![wechatimg9](https://user-images.githubusercontent.com/22836046/31373268-fbb9cca2-adcb-11e7-89d0-488ec6f0fe92.jpeg)
![Uploading WechatIMG10.jpeg…]()
![Uploading WechatIMG11.jpeg…]()
