### ISSUE TITLE
PC-后台管理:系统优化

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#374]
- [x] 1. 保存/删除/修改节点的时候自动同步试听章节&全部章节
- [x] 2. 新建课程默认添加版权申明，客户服务的节点
```
添加一个按钮，点击实现快速添加三大节点API，即版权申明、客户服务、资料下载
```
- [x] 3. 上传课件工具支持按自然顺序上传
- [x] 4. 优惠券创建的备注信息需要可预览
- [x] 5. 管理后台缓存的权限过期后自动刷新权限
```
原官网前台登录不会获取权限&原后台登录2天后权限会自动过期，
应自动刷新权限
```
- [x] 6. 取消管理后台多端登录功能

- [x] 7. 按批次号开通课程
    http://dev.bstcine.com/admin/tool/orderLessons
```
1. 支持多选课程
2. 显示开通结果
3. 可选发短信&邮件通知
（暂不实现）
4. 支持按批次号批量开通课程
  (学校ID暂不实现)

测试建议：和8一起测试
模拟场景：批量开通某学校某年级账号并开通多门课程
```
- [x] 8. 批量创建用户优化
    http://dev.bstcine.com/admin/tool/createUsers
```
1. 支持设置手机号、昵称、email、账号、学校、批次号、密码、年级、出生日期、备注
    手机号、email、账号3选1必填
2. 可选发短信&邮件通知
    （目前仅支持自动发短信）
3. 手机号\email\账号查重
```

- [ ] 9. 产品发布维护功能 [https://github.com/bstcine/cine-tasklist/issues/485](https://github.com/bstcine/cine-tasklist/issues/485)
```
需要操作足够简单可用
```

- [ ] 10. 商城TAB、分类维护功能 [https://github.com/bstcine/cine-tasklist/issues/486](https://github.com/bstcine/cine-tasklist/issues/486)

**Comment by zhuyichun** [comment]
优先解决1.1

**Comment by zhuyichun** [comment]
#### 2018优化 优先处理3、4
- [ ] 1.课程管理-课程制作：限制chapter级别补录不能上传课件
- [ ] 2、批量上传功能需要支持批量上传图片或音频（音频图片一对多最好能做）
- [ ] 3、通过上传execl创建目录
```
1、提供course_id，创建Chapter目录和lesson目录 
2、提供chapter_id，创建lesson目录
```

**Comment by joelin109** [comment]
善恩后台-私塾管理-师生对应关系
```
学生ID：显示昵称+ID
比如：苑冰 Betty(A011455875394561ZQg0eKkLV9)
```

**Comment by JENNY-BSTCINE** [comment]
登录后台管理操作时，每隔几分钟不操作了，就被退出后台，需要重新登录才能操作，时间间隔太短，非常不方便。-Jenny

**Comment by daweilv** [comment]
## 1、后台管理优化
-  1.1：活动产品图片及价格可以预先设置  -- 等级高p2
```
活动期间显示活动价格和图片，正常显示默认价格和默认产品图片
```
```
1.在商城后台-课程管理-课程：编辑中选择图片信息table页添加活动图片字段，提供图片上传、预览功能、活动开始时间设置（精确到分）、活动结束时间设置（精确到分）

2、在商城后台-课程管理-课程：编辑中选择基本信息table页中添加活动价格字段，根据需求1中设置的活动期间,产品详情页显示和首页价格改变。

活动开始前：
产品详情页显示和首页价格显示：价格+原价（如果存在原价）

活动期间：
产品详情页显示和首页价格显示：活动价格+原价（如果存在原价）

活动结束后：
产品详情页显示和首页价格显示：价格+原价（如果存在原价）
```



- [ ] 1.2 自动创建微信分享信息  - http://www.bstcine.com/table/ShareParam  --优化
```
1、维护course界面添加分享信息输入框，如‘最经典的英语启蒙教材！’
2、添加按钮自动生成微信分享语句并绑定到这个课程上
3、现有功能不影响。如购买后分享、详情页分享、打卡分享保持可以单独设置的功能
```
