### ISSUE TITLE
PC-网络访问：偶尔从公司内部访问官网， 无法打开官网

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#375]
## 问题：
通过4G：可以访问官网，http://www.bstcine.com/
通过内部WiFi：无法访问官网,  http://www.bstcine.com/

**Comment by daweilv** [comment]
联系阿里云未能提供有效帮助，清空了 www.bstcine.com 下的 nginx log，目前暂未出现该问题

**Comment by daweilv** [comment]
初步定位为Jerry使用工具压测官网的时候触发了阿里云的屏蔽，导致该ip被封，进一步导致公司内部都访问不了官网
