### ISSUE TITLE
For-Ana:  待提供的UI设计

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#384]
### P1
- [ ] 1.1. 购买与支付：支持Stripe跨境支付 - `Phone & Pad & PC` #442 
- [ ] 1.2. 购买与支付: 课程可以选择2年有效或永久有效， 然后对应不同的价格 - `Phone & Pad & PC` 
```
- 可选择页面：课程详情页
- 可选择页面：购买支付页面
```
- [x] 1.3. 学习系统：词汇作业 - 词汇的卡片式学习（2级页面） - `Phone`

**Comment by Anawangqi** [comment]
### 词汇学习-卡片式-手机版

1.开始学习-卡片正面
![ip- -1](https://user-images.githubusercontent.com/32318334/42504726-32630924-846f-11e8-8d10-386af79cdd60.png)

2.词义解释-卡片背面（图片+文字）
![ip- -2](https://user-images.githubusercontent.com/32318334/42504747-4659312e-846f-11e8-9f3e-a16b84d62adc.png)

3. 卡片夜晚模式+背面无图模式
![ip- -3](https://user-images.githubusercontent.com/32318334/42504818-7bfd6c3c-846f-11e8-9f07-8c7300112ad6.png)

4.本组词汇学习结束
![ip- -4](https://user-images.githubusercontent.com/32318334/42504835-8a412590-846f-11e8-9160-f129820520bf.png)

**Comment by Anawangqi** [comment]
### 1. 选择有效期
![pc- -1](https://user-images.githubusercontent.com/32318334/45415530-73513000-b6b0-11e8-9cd0-dd44ab1057ea.png)

### 2. 订单支付
![pc_](https://user-images.githubusercontent.com/32318334/45617589-5ef0a700-baa5-11e8-9db5-70386b0c9bcc.jpg)

**Comment by Anawangqi** [comment]
### 手机版
![app_ -1](https://user-images.githubusercontent.com/32318334/45617614-716ae080-baa5-11e8-81c2-733fb79e37dc.png)
