### ISSUE TITLE
PC-后台管理: 私塾模块 - 老师学生管理&任务管理&任务分配

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#389]
###  1. 私塾老师列表
- .
```
功能：
A.  添加私塾老师
B.  给私塾老师分配私塾学生
C. 给私塾老师设置：负责的课程列表
```

<br>

###  2. 批量导入私塾的任务基础数据
- 2.1.  私塾的课件习题数据
```
功能：
A.  提供规范化的文档，让老师输入
B.  导入习题文档，生成私塾的课件习题

- 需要区分 普通的Lesson习题 还是私塾的课件习题
```

- 2.2.  导入Top10000词汇数据  （#394）

<br>

###  3. 任务管理列表
- task
```
功能：
A.  老师负责的课程对应的任务可以自动生成
B.  老师可删除任务
C.  老师可以创建自己的任务（比如词汇任务）
D.  提供按钮， 可针对某课程重新生成任务

澄清：
任务名称：默认为 课程简写-Lesson简写
```

<br>

###  4. 任务分配管理列表
```
- task-user-schedule
```
- 学生任务分配管理
```
A. 给学生分配任务
    - 选择学生，选择任务进度（时间），选择对应的任务
```
- 课程任务分配管理
```
B. 给课程安排任务进度
    - 选择课程，选择任务进度（时间），选择对应的学生
```
```
澄清：
4.1.1. ‘私塾老师’ 给 ta 的 所有学生分配任务
4.1.2. 任务进度安排：颗粒度为‘天’、‘周’， 默认为周。（‘From - To'）
4.1.3. 老师批改完学生的习题任务，学生在`学习首页`会看到这个习题(批改完)的作业
4.1.4. 学习相同的课程，不同的学生可以有不同的任务进度
```

**Comment by daweilv** [comment]
### 1. 私塾老师列表 table: relation_teacher_student

| key        | 名称         | 备注 |
| :--------- | :----------- | :--- |
| id         | id           |
| teacher_id | 教师 ID      |
| student_id | 学生 ID      |
| course_ids | 负责课程 ids |
| create_at  | 创建日期     |
| create_by  | 创建者       |

### 2. 任务管理列表 table: task

| key              | 名称         | 备注                                                  |
| :--------------- | :----------- | :---------------------------------------------------- |
| id               | id           |
| title            | 标题         | Longman3000 基础词汇 / 《动物农庄》第三课             |
| type             | 对象类型     | 1:视频, 2:习题, 3:习题反馈, 4:单词, 9:其他            |
| object_id        | 对象 id      | lesson_id, quiz_id, stats_id, word_or_some_id, xxx_id |
| word_start_index | 单词开始编号 |
| word_end_index   | 单词结束编号 |
| create_at        | 创建日期     |
| create_by        | 创建者       |

### 3. 任务分配管理列表 table: task_schedule

| key          | 名称        | 备注               |
| :----------- | :---------- | :----------------- |
| id           | id          |
| user_id      | 指定学生 id |
| task_id      | 任务 id     |
| status       | 任务状态    | 0:待完成, 1:已完成 |
| effective_at | 生效日期    |
| expire_at    | 失效日期    |
| complete_at  | 完成日期    |
| create_at    | 创建日期    |
| create_by    | 创建者      |

**Comment by zhuyichun** [comment]
## 交互图：  https://free.modao.cc/app/vLcyyamVsuAgNkY07TisMETxopGh25A

**Comment by daweilv** [comment]
## 私塾模块
###  1. 私塾老师列表
- [x] A.  添加私塾老师
- [x] B.  给私塾老师分配私塾学生
- [x] C.  给私塾老师设置：负责的课程列表


<br>

###  2. 批量导入私塾课件习题 
- [ ] A.  提供规范化的文档，让老师输入
- [ ] B.  导入习题文档，生成私塾的课件习题
 
* 需要区分 普通的Lesson习题 还是私塾的课件习题
 

<br>

###  3. 任务管理列表 
功能：
- [x] A.  老师负责的课程对应的任务可以自动生成
- [x] B.  老师可删除任务
- [x] C.  老师可以创建自己的任务（比如词汇任务）
- [x] D.  提供按钮， 可针对某课程重新生成任务
 

<br>

###  4. 任务分配管理列表
- [x] A. 给学生分配任务
    - 选择学生，选择任务进度（时间），选择对应的任务
- [ ] B. 给课程安排任务进度
    - 选择课程，选择任务进度（时间），选择对应的学生

**Comment by zhuyichun** [comment]
## 老师
问题1：
老师有课程A、学生未开通课程A，老师分配任务列表不应该显示课程A的任务列表
问题2：
老师分配任务列表没有显示Chapter习题

## 学生
问题1：
学习首页-以前作业：显示错误
问题2：
学习首页-习题做作业：显示空白
