### ISSUE TITLE
H5-学习系统: 任务历史页- 查看以前所有任务记录(视频课件&词汇&习题)

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#391]
### 需求
- 查看以前所有任务记录 
- 查看以前所有词汇任务记录
- 查看以前所有习题任务记录
- 查看以前所有习题老师批改记录
```
有筛选过滤功能
```

<br>

### url
```
/learn/task?user_id=* & type=*(task_type)
```

**Comment by Anawangqi** [comment]
## 手机版

1. 词汇学习历史
![- -2](https://user-images.githubusercontent.com/32318334/41453095-03e7f248-70a7-11e8-9260-1baaffeaad23.png)

2. 词汇学习历史-查询
![ip- -](https://user-images.githubusercontent.com/32318334/41453109-0cc973c8-70a7-11e8-956e-ef2d0497185b.png)

## PC版

2. 词汇学习历史
![pc- -](https://user-images.githubusercontent.com/32318334/41453119-17a7880c-70a7-11e8-84df-9f4a340400f6.jpg)

2. 词汇学习历史-查询
![pc- - -](https://user-images.githubusercontent.com/32318334/41453130-201ef768-70a7-11e8-9273-f809d1a2cab1.jpg)
