### ISSUE TITLE
 H5-导师批改:  可以看到私塾学生的本周作业情况

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#396]
## 需求
- [x] 1. 规范代码：把相应的代码迁移到Mentor模块   
```
如：
- 学生测试的component代码迁移到
...src/client/entry/mentor/component/StuQuiz
```
- [x] 2. API-导师批改：导师的所有学生的本周作业列表   @daweilv David  (#418)
```
- 导师列表 
- 10名导师的所有学生的本周作业列表 （提供导师的UserID）
- 某导师的所有学生的本周作业列表 （提供导师的UserID）
- 我的所有学生的本周作业列表 （通过Token）

   --- 学生的本周作业数据结构与学习首页的学生本周作业数据结构 一致
```
- [ ] 3. H5-导师批改：学生作业部分

<br>
<br>
<br>

```
备注：
点击全部, 打开学生的全部作业（Aaron提供的页面）
learn/task?user_id=[user_id]
```

**Comment by Anawangqi** [comment]
## 1.1 PC版-老师批改-学生作业
![04pc- -1](https://user-images.githubusercontent.com/32318334/41886726-3b5606c0-7930-11e8-96ca-8f8b06f5e79f.jpg)

<br>

## 1.1.1 PC版-老师批改-学生作业-习题
[pc- -3](https://user-images.githubusercontent.com/32318334/41453364-0ab56fe6-70a8-11e8-95f8-f9ce20e71383.jpg)

## 1.2 PC版-老师批改-学生历史作业
![04pc- -4](https://user-images.githubusercontent.com/32318334/42668516-b378e5f4-8683-11e8-9dec-586bcfa57a09.jpg)

<br>
<br>

##  2. 老师批改-学生测试
[pc- -2](https://user-images.githubusercontent.com/32318334/41453371-111f83f8-70a8-11e8-9413-d6776e6039b3.jpg)

**Comment by Anawangqi** [comment]
## 老师批改-手机版

1. 老师批改-学生作业
![04 -1 1 -](https://user-images.githubusercontent.com/32318334/41886810-8c227ee4-7930-11e8-943e-2250f53f6b73.png)

2. 老师批改-学生作业-习题
![-2 -](https://user-images.githubusercontent.com/32318334/41453847-d821edaa-70a9-11e8-862e-9e492becf4a1.png)

3. 老师批改-学生历史作业
![04 -4](https://user-images.githubusercontent.com/32318334/41886824-9a8101a4-7930-11e8-8d0c-8dc89d0e502b.png)

4. 老师批改-学生测试
![-3](https://user-images.githubusercontent.com/32318334/41453855-dfbd3308-70a9-11e8-91f4-ef39ecda77e1.png)

**Comment by zhuyichun** [comment]
https://pro.modao.cc/workspace/apps/pC3B9BE17971527563089769/preview
