### ISSUE TITLE
H5-学习系统: 私塾词汇任务- 简易式的词汇学习

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#397]

**Comment by Anawangqi** [comment]
## 手机版

1.词汇学习
![02- -1](https://user-images.githubusercontent.com/32318334/41827218-da13b76a-7860-11e8-9ce3-6a21d6de3c65.png)

## PC版

1.词汇学习
![pc- 1](https://user-images.githubusercontent.com/32318334/41826399-e3d49102-785b-11e8-8850-e242f20593be.jpg)
