### ISSUE TITLE
H5-学习系统: 私塾词汇任务- 学完后词汇测试

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#398]

**Comment by Anawangqi** [comment]
# 手机版

1. 词汇测试-开始测试
![-1](https://user-images.githubusercontent.com/32318334/41452950-9519fd02-70a6-11e8-9ca8-0ee58276b310.png)

2. 词汇测试-鼠标点选状态
![-1 1](https://user-images.githubusercontent.com/32318334/41452979-ae983208-70a6-11e8-8ebe-1b5893994ccb.png)

3. 词汇测试-回答错误
![-2](https://user-images.githubusercontent.com/32318334/41452984-b518fd42-70a6-11e8-98ad-8cf5ac66140b.png)

4. 词汇测试-回答正确
![-3](https://user-images.githubusercontent.com/32318334/41452992-ba57ba64-70a6-11e8-9f46-527de7fb9a4c.png)

5. 词汇测试-测试结束
![-3](https://user-images.githubusercontent.com/32318334/41453007-c2020382-70a6-11e8-9722-f90766553223.png)

**Comment by Anawangqi** [comment]
# PC版

1. 词汇测试-开始测试
![pc- -1](https://user-images.githubusercontent.com/32318334/41452877-4bde89be-70a6-11e8-9214-b4c5ca049876.png)

2. 词汇测试-鼠标点选时状态
![pc- -1 1](https://user-images.githubusercontent.com/32318334/41452881-5864bd34-70a6-11e8-94cf-1f52d8ce33e6.png)

3. 词汇测试-回答错误
![pc- -2](https://user-images.githubusercontent.com/32318334/41452894-647952c4-70a6-11e8-9c63-81b9edd4e31d.png)

4. 词汇测试-回答正确
![pc- -3](https://user-images.githubusercontent.com/32318334/41452901-6d19de58-70a6-11e8-8dd1-21de8de70cc2.png)

5. 词汇测试-测试结束
![pc- -4](https://user-images.githubusercontent.com/32318334/41452904-72d0fb2e-70a6-11e8-9155-3941ccb9a815.png)

**Comment by zhuyichun** [comment]
PC:https://pro.modao.cc/workspace/apps/pC3B9BE17971527563089769/preview
iphone:https://pro.modao.cc/workspace/apps/p86595D669F1526954293925/preview
