### ISSUE TITLE
H5-学习系统: 私塾习题任务- 习题测试（包含客观题和主观题）

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#399]
## 需求
```
私塾学生：
- 习题类型： 私塾习题 + 主观题 + 客观题
- 批改情况：针对需要批改的主观题
                   - 如果是老师分配的作业，老师负责批改
                   - 如果是老师没有分配的练习，老师不负责批改

普通学生：
- 习题类型： 普通客观题

更新需求 - 2018-06-25
 - . 习题需要全部做完， 才能提交
```

## Must fix
- [x] 1. 习题需要全部做完， 才能提交   -verified
- [x] 2. 规范对外路径， https://dev.bstcine.com/quiz/  -verified
```
- 核心语法测试  -verified
https://dev.bstcine.com/quiz/grammar?quiz_id = quiz_id
https://dev.bstcine.com/quiz/grammar?stats_content_quiz_id = stats_content_quiz_id

- 课件习题测试
https://dev.bstcine.com/quiz/kj?lesson_id = lesson_id  -verified
https://dev.bstcine.com/quiz/kj?chapter_id = chapter_id
https://dev.bstcine.com/quiz/kj?course_id = course_id
```
- [x] 3. 学生的答题答案应该答案的主体前后去空保存
- [x] 4-2.6 提交后不批改的主观题没有显示默认解析            -verified                 
- [x] 5. 习题测试的Title：与任务作业名一致  -verified
-  6. 课件播放入口：显示Lesson 的 short name 
```
```

<br>
<br>
<br>
<br>

## 习题入口
- [x] 1. 学习首页 - 私塾模块 - 习题作业
```
http://apptest.bstcine.com/quiz/kj?lesson_id=xxxx
```
- [x] 2.  课件播放页 - 习题练习 （针对老版移动端）
```
http://apptest.bstcine.com/cquiz?*******
```
- [x] 3.  课件播放页 - 习题练习 （针对新版本）
```
http://dev.bstcine.com/quiz/kj?lesson_id=xxxx
```
- [x] 4.  导师批改 - 学生作业- 学生习题作业
```
如果导师批改页面未完成，可通过url 打开（临时测试）
http://dev.bstcine.com/quiz/kj?user_id=xxxxx&lesson_id=xxxx&cmd=check
```
- [x] 5.  用户模块 - 核心语法测试（需要正常进行）
```
http://dev.bstcine.com/quiz/grammar
```

<br>
<br>
<br>
<br>

## 清空课件习题历史数据
``` sql
-- 清空课件练习的答题记录明细表
select a.id,a.stats_content_quiz_id,b.content_quiz_id,c.name,c.type from stats_content_quiz_detail a,stats_content_quiz b,content_quiz c where a.stats_content_quiz_id = b.id and b.content_quiz_id = c.id and c.type in ('1','3');
delete from stats_content_quiz_detail where id in (select * from (select a.id from stats_content_quiz_detail a,stats_content_quiz b,content_quiz c where a.stats_content_quiz_id = b.id and b.content_quiz_id = c.id and c.type in ('1','3')) as p);

-- 清空课件练习的答题记录表
select a.id,b.name,b.type from stats_content_quiz a,content_quiz b where a.content_quiz_id = b.id and b.type in ('1','3');
delete from stats_content_quiz where id in (select * from (select a.id from stats_content_quiz a,content_quiz b where a.content_quiz_id = b.id and b.type in ('1','3')) as p);

-- 清空课件练习的试卷表
select * from content_quiz where type in ('1','3');
delete from content_quiz where type in ('1','3');
```

测试反馈，#417

**Comment by Anawangqi** [comment]
## 手机版

1.做题
![- -1](https://user-images.githubusercontent.com/32318334/41227744-7e97d7b2-6da8-11e8-9194-b45b24bcc97c.png)

2.答题未做完提示
![- -2](https://user-images.githubusercontent.com/32318334/41843835-1858f2a2-78a1-11e8-913b-5b5f5e0d378d.png)

3.查看答案页面-普通学生
![-3 -](https://user-images.githubusercontent.com/32318334/41452660-77718a28-70a5-11e8-922b-169b3cc5083d.png)

3.查看答案页面-私塾学生
![-4 -](https://user-images.githubusercontent.com/32318334/41452667-806a0164-70a5-11e8-8675-4c8c356c1b14.png)

**Comment by Anawangqi** [comment]
## PC版

### 学生

1.做题
![pc- -1](https://user-images.githubusercontent.com/32318334/41452729-c03b6076-70a5-11e8-8489-185561a897fc.png)

2.提示-答题未做完
![pc- -2](https://user-images.githubusercontent.com/32318334/41843912-444790b2-78a1-11e8-8139-e8d7844b87c2.png)

3.查看答案页面-普通学生
![pc- -3 -](https://user-images.githubusercontent.com/32318334/41452745-cfad8872-70a5-11e8-89fe-25d5e06edda5.png)

3.查看答案页面-私塾学生
![pc- -4 -](https://user-images.githubusercontent.com/32318334/41452751-d6bc91c6-70a5-11e8-835e-6411a7d55b97.png)

**Comment by zhuyichun** [comment]
## 老师
问题1：
老师有课程A、学生未开通课程A，老师分配任务列表不应该显示课程A的任务列表
问题2：
老师分配任务列表没有显示Chapter习题
问题3：
老师批改作业查看到的默认解析内容空

## 学生
问题1：
学习首页-以前作业：显示错误
问题2：
学习首页-习题做作业：只有选择题，没有简单题。且部分选择题来源不是录入的数据。
问题3：
学习首页-习题做作业：客观题-学生答完提交后，再次进入看不到默认解析答案。

**Comment by itwangxiang** [comment]
- 清空历史测试数据
``` sql
-- 清空课件练习的答题记录明细表
select a.id,a.stats_content_quiz_id,b.content_quiz_id,c.name,c.type from stats_content_quiz_detail a,stats_content_quiz b,content_quiz c where a.stats_content_quiz_id = b.id and b.content_quiz_id = c.id and c.type in ('1','3');
delete from stats_content_quiz_detail where id in (select * from (select a.id from stats_content_quiz_detail a,stats_content_quiz b,content_quiz c where a.stats_content_quiz_id = b.id and b.content_quiz_id = c.id and c.type in ('1','3')) as p);

-- 清空课件练习的答题记录表
select a.id,b.name,b.type from stats_content_quiz a,content_quiz b where a.content_quiz_id = b.id and b.type in ('1','3');
delete from stats_content_quiz where id in (select * from (select a.id from stats_content_quiz a,content_quiz b where a.content_quiz_id = b.id and b.type in ('1','3')) as p);

-- 清空课件练习的试卷表
select * from content_quiz where type in ('1','3');
delete from content_quiz where type in ('1','3');
```
