### ISSUE TITLE
iOS: 已下载中需要有章节目录

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#4]

**Comment by MaryLinker** [comment]
首先在课程播放界面下载课程，然后，在“我的”页面点击我的下载进入已下载页面，点击已下载的课程跳转至课程目录，要求课程目录可同时显示章节名和lesson，默认二级目录展开

**Comment by AaronLiDangkun** [comment]
此问题已解决，新版本地址： https://fir.im/cineEducation
