### ISSUE TITLE
API-个人设置: 优惠券可转让给其它账号

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#401]
## 需求
- [x] 1.  通过User的手机号/账号获得用户的基本信息（来确认用户是否正确）
- [x] 2. 转换后，用户的优惠券转让给某个账号

**Comment by kimliss** [comment]
> [/api/user/query](https://github.com/bstcine/cine-api/blob/master/V2.0/userQuery.md): ``` "data":{"query":""} ```
[/api/user/coupon/transfer](https://github.com/bstcine/cine-api/blob/master/V2.0/user_transfer_coupon.md): ```"data":{"transfer":"","coupons":[]}```
