### ISSUE TITLE
H5-个人设置: 优惠券可转让给其它账号

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#402]
## Need fix
- [ ] 1-1、已查询到指定用户点击确定
```
添加显示信息
```
- [ ] 2-2、转让成功没有提示，点击搜索到的用户点击确认就关闭弹窗返回优惠券列表界面了
- [ ] 3-5、用户名下优惠券多于4张，最后一排优惠券（显示在最末尾的一排）点击转让按钮无效
- [ ] 4-6、优惠券转让图标没有

**Comment by joelin109** [comment]
## 交互图：
https://modao.cc/app/nHS4ruXc3vBL3butulc1ukvSlsHYli8#screen=s54636D1E031527564426340
```
From Jerry
```

**Comment by zhuyichun** [comment]
- [ ] 1、已查询到指定用户点击确定没有再次确定（需要二次确认）
- [ ] 2、转让成功没有提示，点击搜索到的用户点击确认就关闭弹窗返回优惠券列表界面了
- [ ] 3、查询到的用户显示优先级：待讨论
- [ ] 4、用户优惠券界面添加优惠券后，优惠券数量没有联动
- [ ] 5、用户名下优惠券多于4张，最后一排优惠券（显示在最末尾的一排）点击转让按钮无效
- [ ] 6、优惠券转让图标没有
- [ ] 7、在目前大批量的转让卷过期后，建议用户接收到的优惠券有效期最短应该不低于一个时间段这样可以鼓励用户购买  --待讨论
```
如A用户优惠券有效期还剩余1天，转让给B后优惠券有效期变更为一个月
```
- [ ] 8、输入用户手机或者账号检查后的提示文字不协调    --优化

- [ ] 9、安卓APP学习打卡头图变形   --bug
- [ ] 10、赠送优惠券购买使用后的在已使用中显示带有已转让标志  --bug
