### ISSUE TITLE
H5-学习系统: 学习首页-私塾模块：显示 “视频课件”&“习题”&“词汇”作业类型

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#406]
### 1.1 私塾模块
- [x]  1.1.1. 需要调整Lesson简写为规范形式

<br>

- [x]  1.1.2. 本周任务（作业）
```
任务列表
任务类型 - 任务名称 - 任务状态

任务类型：词汇、视频、习题、习题（老师的批改）
任务名称：先默认取 课程简写 + Lesson简写
任务状态：未完成/已完成  

-- App：提供  '展开' / ‘收起’ 功能， 默认只显示5条。  '展开'显示更多
-- PC：全部显示
```

<br>

### 1.2 通用学习模块
- [x]  1.2.1. 无网络：可以正常显示及点击学习
```
支持App端离线学习的功能
```

<br>
<br>

### 学生作业的URL 
- 课件：learn/course/42?lesson_id=A0114544938229828lNxe5JjHO
```
做个重新定向
```
- 习题：/quiz/kj？
```
详细url：
case1: [user_id]&[task_id]
case2: [user_id]&lesson_id
case3: [user_id]&chapter_id
case4: [user_id]&course_id
case5: [user_id]&quiz_id
case6: stats_content_quiz_id
case7: stats_content_quiz_id&cmd=check //老师批改操作

```
- 词汇：/learn/word?
```
详细url：
case1: word_type
case2: task_id&[user_id]&lesson_id
case3: task_id&[user_id]&start_index&end_index
```

- 历史任务： /learn/task?user_id=* & type=*(task_type)

**Comment by joelin109** [comment]
![28381528078986_ pic_hd](https://user-images.githubusercontent.com/23466882/41209754-15ada76a-6d60-11e8-91dc-9add2ada74a4.jpg)

**Comment by Anawangqi** [comment]
## 手机版
1.学习首页-简版
![01- -2](https://user-images.githubusercontent.com/32318334/41714124-e1ee0256-7581-11e8-87cd-cd469fbaec71.png)

2.学习首页-历史作业
![01- -3](https://user-images.githubusercontent.com/32318334/41714135-eeeebbda-7581-11e8-88f4-7a376dd75e43.png)

<br>
<br>

## PC版
1.学习首页
![pc- -1](https://user-images.githubusercontent.com/32318334/41714319-818aa9fe-7582-11e8-8b6a-2ea80919d75b.jpg)

2.学习首页-历史作业
![pc- -2](https://user-images.githubusercontent.com/32318334/41714350-a302483a-7582-11e8-94c8-deba7a5639da.jpg)

**Comment by joelin109** [comment]
1.学习首页-完整版
![01- -1](https://user-images.githubusercontent.com/32318334/41714371-bad4aee4-7582-11e8-8f08-b908491b8fef.png)

**Comment by Anawangqi** [comment]
## Pad 竖版

#### 1.学习首页-本周作业
![pad_ _1](https://user-images.githubusercontent.com/32318334/42026318-685078de-7af9-11e8-9a0f-eedf6fc1dfd3.png)

#### 2.学习首页-历史作业
![pad_ _2](https://user-images.githubusercontent.com/32318334/42026336-75e94a70-7af9-11e8-85b7-f12d3a3987f2.png)

#### 3.学习首页-历史作业-查询
![pad_ _3 _](https://user-images.githubusercontent.com/32318334/42026258-3a577306-7af9-11e8-8012-e8419f10db20.png)
