### ISSUE TITLE
PC-后台管理: 私塾任务基础数据- lesson_quiz历史数据需导入question表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#407]
## 需求：
- [x] 1. content_lesson_quiz的数据导入到 content_quiz_quesion 表
- [x] 2. 支持V2.3.1(目前线上版本）版本的 App
- [ ] 3. content_lesson_quiz的表名改为 delete_content_lesson_quiz
```
测试网已改
```

**Comment by kimliss** [comment]
1. 待 content_quiz_quesion 建表后
2. 运行脚本 ```node src/test/question_migration.js ``` 迁移 content_lesson_quiz 数据
3. 将 content_lesson_quiz 该名 delete_content_lesson_quiz
