### ISSUE TITLE
ios-学习系统：学习过程主动打卡

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#41]
需求描述：
1. 流程：点击学习广场的任意课程-进入课程播放界面-点击播放界面右上角的“结束本次学习，打卡”按钮进入微信朋友圈编辑界面-点击发送-回到课程播放界面并弹出“打卡成功”窗口-点击“我知道了”返回学习广场。
2. UI：“结束本次学习，打卡”按钮，“打卡成功”窗口
交互图点击链接 https://modao.cc/app/afoyfX8Iln11EfweOGbHMugul21QSgl 进行查看

**Comment by limingLiuBaBa** [comment]
目前状况:主动打卡流程及界面已经实现.
出现问题:进入播放界面立即点击右上角打卡按钮,会无法暂停音频.
解决方案:p1:首先实现,进入界面不立即打卡,有缓冲音频之后,点击打卡可以暂停.
               p2:刚进入界面不显示打卡按钮,待有缓冲音频之后,显示.

**Comment by limingLiuBaBa** [comment]
最终采取的解决方案:
       在音频未有缓冲的时候,播放器界面不可交互.右上角立即打卡按钮也就不可点击.
