### ISSUE TITLE
H5-学习系统: 私塾模块 - 测试反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#416]
## 1、后台管理 - 老师分配  - `David`

<br>
<br>

## 2. 学习首页 - `David`
- [x] 2.1. 切换不同的用户登入系统， 有时会一直显示某个用户的信息
```
用户信息显示不对

- 不是每次都能重现

Reason: 
原缓存策略为 Cache First。Service Workers 中的 Caches 不会存 cookie，
导致以 request 为 key 的 cache 区分不了用户，认为都是同一个请求，返回同一个 cache。
修改后的缓存策略为 Network First，优选使用 Network，无网络的情况下才使用 Cache。
```

- [ ] 2.2、本周作业：视频作业，“新概念1U1 Lesson 4 - Is this your…”状态显示错误   -``
```
Step1:   账号（ssjoe/cine), 登入   
Step2:  本周作业：视频作业，“新概念1U1 Lesson 4 - Is this your…” 显示”已完成“ - （错误）

- 该账号没有查看”新概念1U1“视频课件的权限，该视频作业怎么能被完成？

- 目前无法重现
```

<br>
<br>
<br>

**Comment by zhuyichun** [comment]
## 1、后台管理-老师分配
- [ ] 1.2老师分配任务列表没有显示Chapter习题 - `Jerry`
- [ ] 1.3老师单词分配没有显示学生已经学到哪的标识，方便老师分配单词
- [ ] 1.4老师单词分配选项范围应该是0-10000
- [ ] 1.5老师分配任务列表默认收缩已经分配过的任务，显示接下来的20条任务，剩余的默认收缩

<br>

 ## 1B、后台管理-私塾学生
- [ ] 1.B1、后台管理→点击私塾学生→点击学生（SS_Jenny）→点击分配任务→点击编辑→点击单词 from（）to (），老师分配单词学习任务的时候，建议系统上可以把10000个基础词汇表放出来，老师可以在系统上直接选择学习哪部分的单词，或者可以查找对应部分的单词。不然老师每次布置词汇学习的时候，还得另外打开自己的词汇表文件，并且自己逐个找对应的部分，比较麻烦。
```
Solution:  待定...
```
- [x] 1.B2 私塾管理：私塾学生- 可分配“Lesson的PDF习题”
```
澄清：
Step1、学习首页：可点开该PDF类型习题，
Step2、线下：学生下载 -》做完 -》拍照给老师看
Step3、导师批改：老师点击某个按钮，确认学生的该PDF习题作业已完成

pdf习题标准：
- `type` = 3
- shortname 含 “习题” or “Exercise”
- PDF习题作业名称：******* PDF

Status: Done
```

**Comment by JENNY-BSTCINE** [comment]
## 2. 学习系统-学习首页（私塾学生）
### 2.1  学习首页-本周作业
- [x] 2.1.1、点击学习首页→本周作业，建议 视频 学习任务栏前的状态增加一个选框，当学生完成对应视频课程学习后，可勾选对应选框，此时对应任务的状态发生变化，显示"已完成“。- `Jenny`
```
目前需求：学生学习完成后打卡成功，算该作业 - 完成。

大家反馈：都不大愿意打卡
```
-  2.1.2、在学习首页看到老师布置了一个视频作业，但是这个视频课程学生还没买。学生新购买了对应课程后，但是在学习页面没有看到新买的课程，课程没有开通，并且点击对应视频作业也还是学习不了。`P1` <img width="1155" alt="2018-07-02 10 04 16" src="https://user-images.githubusercontent.com/32318334/42141977-525f49fe-7ddf-11e8-9498-1b90af6e32e9.png">
```
- 学习首页不用改
- Alice提供“错误提示的信息”
```
- [ ]  2.1.3 学生反馈任务点击过后状态还是‘未完成’



<br>

### 3 - 学习系统-全部作业
- [ ] 3.1、不同路劲进入作业列表需要有不同标识

<br>

## 4. 词汇学习
- 4.1、点击学习首页→词汇学习，建议在每个单词后面增加一个框框可以打钩，如果是已经学会的单词可以选择打钩，表示已经学会。
```
目前不解决
```
- [ ] 4.2、同一个区间安排单词作业，学生的单词作业状态显示错误
```
step 1：导师给学生在20180702-20180708安排单词101-110
step 2:学生进入学习首页完成101到110的单词作业
step 3:学生返回首页查看101-110单词作业状态已经显示已完成
step 4:导师给学生在20180702-20180708安排单词201-210
step 5:学生登录后进入学习首页查看101-110单词作业标题显示为201-210，单词替换为201-210，状态为已完成，点击进入提示为‘在测一次’

```
- [ ] 4.3、导师布置单词作业可以手动填写负数和超出10000数值（学生进入作业后单词区域显示空白）

<br>

- [ ] 4.4、学生单词测试一定概率出现A、B、C选项中任意两个相同，但点击选择

```
如单词 get  A:得到   B:得到 C:****   A和B选项相同，但点击A正确，编辑B错误

写清楚可重现的步骤！！！！
```

**Comment by zhuyichun** [comment]
## 1、老师分配
- [ ] 1.1老师分配任务列表没有显示Chapter习题

**Comment by Anawangqi** [comment]
### 6 导师批改版块

- [ ] 6.1. 二级菜单栏，图标风格不一致（UI这边可以提供），待批改和学生测试图标重复，学生标题栏，和”本周作业“标题栏间距过近，这一块可以再优化，如图：
![2018-07-02 4 52 51](https://user-images.githubusercontent.com/32318334/42155076-f0df9040-7e19-11e8-8b69-bccf4b3b593a.jpg)

### 7 学习系统版块UI
- [ ] 7.1 学习任务，标签文字太贴顶，如图：
<img width="381" alt="2018-07-02 10 05 05" src="https://user-images.githubusercontent.com/32318334/42142031-a89e0d32-7ddf-11e8-83be-83a2f213ea0e.png">

- [ ] 7.2. 单词学习内容，与底部的测试按钮之前有一条线，没有显示，如图：
<img width="1021" alt="2018-07-02 10 16 32" src="https://user-images.githubusercontent.com/32318334/42142297-24f79dde-7de1-11e8-8ae9-82862e420919.png">

- [ ] 7.3. 词汇学习， 序号，单词，音标，喇叭之间不是特别齐，能否尽量显示在一条水平线上，如图：
<img width="308" alt="2018-07-02 10 18 03" src="https://user-images.githubusercontent.com/32318334/42142368-82bb637e-7de1-11e8-9bb4-40b27f0553cd.png">



### 9 个人中心版块
- [ ] 9.1.积分规则界面，标题与选中状态的蓝线间距略大，可再调小一些，另内容与底部背景之间间距太小，如图：
<img width="1029" alt="2018-07-02 10 24 08" src="https://user-images.githubusercontent.com/32318334/42142550-98cd3920-7de2-11e8-845a-fa2f446f416d.png">

**Comment by joelin109** [comment]
## 4、后台管理-私塾学生
- [ ] 4.1、后台管理→点击私塾学生→点击学生（SS_Jenny）→点击分配任务→点击编辑→点击单词 from（）to (），老师分配单词学习任务的时候，建议系统上可以把10000个基础词汇表放出来，老师可以在系统上直接选择学习哪部分的单词，或者可以查找对应部分的单词。不然老师每次布置词汇学习的时候，还得另外打开自己的词汇表文件，并且自己逐个找对应的部分，比较麻烦。
```
Solution:  待定...
```

**Comment by iYuanYuan2** [comment]
## 2、学习首页
- [x] 2.1 学完视频课程，并完成练习后，无法直接回到“我的学习”页面。重新输入link登录“我的学习”野蛮后，“视频”任务仍然显示“待完成”，练习已显示“已完成”
```
需求待确认
```
-  2.2 词汇测试 - 立即测试：没有小喇叭，这个需求我想确认下。
![image](https://user-images.githubusercontent.com/35132688/42212637-4476359a-7ee9-11e8-9b62-c9a6a841b2e1.png)
-  2.3 词汇测试 - 立即测试：没有词性，这个需求我想确认下。

**Comment by zhuyichun** [comment]
- [ ] 1.注册页面样式混乱
- [ ] 2.修改密码页面，密码输入框是明文，应该用'*'代替
