### ISSUE TITLE
H5-学习系统: 习题测试&导师批改 - 测试反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#417]
## 基础信息
- 导师批改 - 批改学生的习题作业
https://apptest.bstcine.com/quiz/kj?user_id=xxxxx&lesson_id=xxxx&cmd=check

- 核心语法测试 （Alice提供给私塾学生）
https://dev.bstcine.com/quiz/grammar
- 已导入习题课程
![1530756641388](https://user-images.githubusercontent.com/20130469/42299917-5389553c-8040-11e8-89f9-1361cc465d9a.jpg)

```
新概念1U1-lesson2 - 需要老师批改
新概念1U1-lesson4 - 需要老师批改
```

<br>
<br>

### 1. 课件播放 - Lesson 练习（PC更新为新版本）
- [x] 1.1.  课件播放页：App端-练习题目重复    - `Jerry`
```
Status: Fix
```

<br>
<br>

### 5. 学生做题
- [x] 5.1  习题测试：单选题- 提交后，不用显示得分  -ver
```
Status: Fix
```
- [x] 5.2 - 2.6 习题测试-作业：简答题-提交后，没有显示默认解析
```
Step1:  后台管理：导师分配 “纳尼亚1 Chapter14/Lesson 32” 任务给学生
Step2:  学习首页：点击习题作业，“纳尼亚1 Chapter 16/Lesson 32”
Step3:  做完习题，提交
Step4:  默认解析没有显示
正确显示：“待批改......"
目前显示：“老师批改中...”
```
```
Status: Fix
```
- [ ] 5.3  习题测试-作业：学习首页点击某习题作业，url显示为核心语法测试
```
Step1:   学习首页: “某习题作业”，url 如：https://dev.bstcine.com/quiz/kj?lesson_id=1126
Step2：点击 该习题作业，页面显示为为核心语法测试，url 为 https://dev.bstcine.com/quiz/grammar

- 曾经发现过，目前不好重现
- 建议：习题作业的URL不要自动跳转与修改
- 代码：不要写某某Case下，window.href=... 等逻辑代码
```
```
Status: Fix
```

<br>
<br>

### 6. 导师批改
- [ ] 6.1-6.3 导师进入导师批改界面，点击学生没有提交的作业，弹窗提示错误
```
Step 1：登录tjerry/zhuyichun,进入导师批改页面
Step2：选择学生ssjerry，点击全部作业
Step3：点击未完成的习题作业，页面显示错误

建议：
  - S1：可以查看学生未完成的习题作业
   -S2：页面提示学生未提交
```
```
Status: S1 Fix
```
- [ ] 6.2.  导师批改页面 : 学生作业-需要显示任务的Deadline & 提醒按钮为灰 （看[设计UI](https://github.com/bstcine/cine-tasklist/issues/396#issuecomment-396205526)）
```
Status: Fix
```
<br>
<br>

## Nice to have
- [ ] 4.1 -2.4 习题测试：简答题-学生答案输入空格，仍然能够提交
- [ ] 4.2  习题测试-非作业：简答题-提交后，显示”老师批改中...“
```
导师只可能批改布置的习题，非作业的习题不批改

Step1:  购买”纳尼亚1 “
Step2:  点击播放：“纳尼亚1 Chapter 16/Lesson 32”
Step3:  点击”新练习“，做完习题，提交
Step4:  简答题显示”老师批改中...“

正确显示：
                - 显示默认解析
                - 显示“待批改......"

Status: ？
```

**Comment by JENNY-BSTCINE** [comment]
学习系统--学习首页（私塾学生）
1、老师布置一个视频作业，但是这个视频课程学生还没买。新购买了对应课程后，但是在学习页面没有看到新买的课程，课程没有开通，并且点击对应视频作业也还是学习不了。

**Comment by JENNY-BSTCINE** [comment]
# 习题测试页面
- [x] 1.1.1、习题页面的试卷做完并提交后，没有明显返回到学习首页或者本周作业的按钮。
```
通过导航栏
```
- [ ] 1.1.2、老师批改完成后，习题页面的试卷上没有任何批改完成的提示语之类的？

**Comment by zhuyichun** [comment]
## 1、学生做题
- [ ] 1.1.1 学生答案全部输入空格，仍然能够提交

<br>
<br>

- 1.2.1. 老师可以多次批改，但是批改一次后学生就会多生产一条已经批改完成的任务  P1
- 1.2.2. 私塾学生状态更改为休息，通过课件入口第一次点击进入显示私塾试卷
-  1.2.3. 主观题的默认解析目前都显示红色
```
应该是什么情况才显示红色？
case 1:抓取关键字，有关键字显示答对的颜色。没有关键字显示红色
```
- 1.2.4、点击学习首页→纳尼亚课程→Chapter 8Lesson 18→lesson右下角的“新练习", 练习做完提交后，试卷上没有显示 总分 、 重做一遍的按钮以及 结束测试的打卡按钮？如果没有打卡按钮，如果学完对应lesson后如何打卡？ - `Jenny`
```
不用解决
```
-   1.3学习首页显示‘本周作业’，‘历史作业’。叫‘历史作业’不合适

**Comment by zhuyichun** [comment]
- [ ] 目前通用的GHeader 用户头像不能加载

**Comment by joelin109** [comment]
<br>

## 2. 导师批改
- [ ]  2.1.  导师批改学生作业界面，点击‘完成批改’跳转错误
```
进入批改页面https://dev.bstcine.com/quiz/kj?user_id=d011516599171374bTfrWM34bm&lesson_id=t011529923391300WSdEZvb6nP
```

**Comment by zhuyichun** [comment]
- [ ] 学生做题进入习题测试页面，头部导航不应该定位的是‘个人中心’  -P2
```
step 1：私塾学生登录，进入学习首页，头部显示‘学习系统’
step 2: 点击习题任务，进入习题测试，头部导航显示‘个人中心’
```

**Comment by zhuyichun** [comment]
## 4上架前模块测试
- [ ]  4.1学习首页显示‘本周作业’，‘历史作业’。叫‘历史作业’不合适

**Comment by zhuyichun** [comment]
## 6.导师批改
- [ ] 6.1 导师打开学生作业不能批改 （#422）
```
step 1: 老师进入导师批改界面，点击‘全部’，进入全部作业界面
step 2:选择学生完成的习题进入没有批改按钮不能操作
```
- [x] 6.2 导师批改：学生作业 - 没有默认选中样式
```
Step1: ...
```
```
status: Fix
```
- [x] 6.3导师进入导师批改界面，点击学生没有提交的作业，弹窗提示错误
```
Step 1：登录tjerry/zhuyichun,进入导师批改页面
Step2：选择学生ssjerry，点击全部作业
Step3：点击未完成的习题作业，页面显示错误

建议：
  - S1：可以查看学生未完成的习题作业
  - S2：作业导师不能点击
   -S3：页面提示学生未提交
```
