### ISSUE TITLE
H5-个人设置: 我的测试

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#419]
### 需求
- [x] 我的测试 - 词汇量测试列表
- [x] 我的测试 - 核心语法测试列表
```
不显示“批改人”， “待批改”改为蓝色系 （红色系是提醒某人需要做某事）
```
- [x] 我的测试 - 测试词汇量、测试语法
```
针对非私塾学生：
   -  不显示“测试语法” 或 变灰 （点击无效）
```

<br>

- [x] 我的优惠券 - 添加优惠卷
```
调整一下悬浮的位置
    - 与习题测试中的悬浮按钮位置一样（将来网站上悬浮按钮的风格与位置都类似）
```

<br>
<br>
<br>

### 代码规范统一
- 代码路径
```
user/containers/QuizContainer.js
user/reducers/quizReducer.js

- 已经创建
```
- 调整文件名 (如果可以的话）
```
vocabtest  >> quizvocab
```

**Comment by Anawangqi** [comment]
### 我的测试

1.词汇量测试
![pc_ _1](https://user-images.githubusercontent.com/32318334/42028619-52a86d7e-7aff-11e8-8d10-9b4b89fc845b.png)

2.核心语法测试
![pc_ _2](https://user-images.githubusercontent.com/32318334/42252410-11bcf3d8-7f6f-11e8-8ade-ff2705073c83.png)
