### ISSUE TITLE
Realese-v2.3.2.1: 版本发布- 测试问题遗留列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#422]
## 1. 学习系统
- [x] 1.1. 本周作业：词汇测试-  有些单词出现2个重复的中文选项（如301-305）     @Aaron
```
Status:  Fix
```
- [x] 1.2. 本周作业：习题作业-  题目上线数量为25    @Kim
```
APP与PC端题目数量保存一样
```
```
status: fix
```
```
官网测试反馈：
非私塾学生（PC端）-《了不起的狐狸爸爸》精读课程，做练习时只有10道题
非私塾学生（App端）-《了不起的狐狸爸爸》精读课程，做练习时有15道题
私塾学生（PC端）-《了不起的狐狸爸爸》精读课程，做练习时有15道题

操作步骤：
step1：登录学习首页
step2：点击Chapter1-Lesson1-练习


Reason: 没有删除垃圾数据
Status： Done.
```

- [x] 1.3. 课件播放页：左边树结构- 点击的Lesson习题，显示K12语法测试 -   @Kim
```
Step1: 登入 -》学习首页 -》神奇书屋2（已购买）
Step2: 点击 Lesson1 测试，显示K12语法测试 （错误）

正确：应该显示正常的习题测试

规则：
1.  /quiz/grammar
只有这个url入口， 才显示K12核心语法测试


Solution：
1. 将 content_lesson_quiz 表名恢复 @Joe
2. 发布 web + pwa(2.3.2.1) 到正式网 @David
3. node ./question_migration.js 迁移 lesson 测试数据 @kim
4. 即可使用
5. 将 content_lesson_quiz 表名改为Delete_content_lesson_quiz @Joe


```
- [ ] 1.4. 本周作业：习题作业-  右上角显示答对率（客观题）  @Kim
```
正确率：80%      共10题
```
- [ ] 1.5. 本周作业：反馈习题-  打开反馈习题后，状态没有改变还是‘未完成’  - `Nice to have` @Kim

<br>
<br>

## 2. 商城 & 购买

<br>
<br>

## 3. 个人中心 

<br>
<br>

## 4. 导师批改   - `Kim`
- [x] 4.1. 导师批改：学生测试- 核心语法测试批改后会生成一个反馈作业
```
status: fix
```

<br>
<br>

## 8、其它：
- [x]  8.1、官网- 检验&确认跟踪记录用户学习时所使用的设备 (#166)
```
cine.web.android.phone
cine.web.iphone
cine.web.ipad
cine.web.pc
cine.web.wechat
......
```
- [x]   8.2、词汇词汇：如果使用top1000词汇的中文翻译使用来做测试，中文翻译显得有点怪
```
建议：
让几个的老师快速检查一下中文翻译，看看是否需要调整
```
- [x]   8.3、Email-销售报表：日报&月报- “教材与其它产品”小计结果不对
```
- 小计：没有真正统计，只计算一项
- 添加一分类 “在线私塾

Status：Done for Dev
```

**Comment by joelin109** [comment]
## 1. 学习系统（私塾模块）
-  1.2. 学习系统-词汇学习：点击喇叭，应该有喇叭播放的效果  -P4
- [ ] 1.3. 安卓app打卡弹出框头部变形 
- [ ] 1.4 老师批改-学生作业：试卷批改页面添加‘老师必须批改’的标识 ，方便老师批改试卷-jerry
- [ ] 1.5 学习系统-学习首页-历史作业：导航‘学习首页’鼠标悬浮出现的下划线样式不对  -jerry
- 1.6 app上完成的习题任务，状态没有更新  -jerry

**Comment by joelin109** [comment]
## 2. 商城 & 购买
- 2.1 pc端首页加载慢且没缓存
```
step1 ：访问dev.bstcine.com,点击‘合作招商’
step 2:点击‘首页’，加载首页慢，
step 3：点击‘APP下载’加载完毕后
step 4:点击‘首页’，加载慢 
```
-  2.2 wechat浏览器打开支付页面会有2次刷新
```
step1 ：wechat浏览器点击‘立即购买’按钮
step 2:系统自动跳转到支付页面，页面会有2次加载。
```
-  2.3 新人优惠券获取失败   - `P4`
```
step 1:app在课程详情页'点击推荐的积分'分享到朋友圈
step 2：微信访问官网登录账号18516157099/zhuyichun
step 3：点击朋友圈链接进入课程详情页
step 4:app登录18516157099/zhuyichun
step5 :微信课程详情页点击‘立即领取’获取新用户专享卷，弹窗提示优惠券已成功发送至账户‘18516157099’，优惠券码‘49874106’
step 6:后台检查优惠券码‘49874106’，没有绑定userId。登录账号18516157099没有获取到这张优惠券
```

**Comment by joelin109** [comment]
## 3. 个人中心
- [ ] （3）2018-07-19：想要修改密码，但是输入了一个格式正确但是不存在的账号，这个提示语说“系统异常”，用户还以为我们的系统有问题。。
step1：点击登入学习→忘记密码→输入手机号：13848105601；
step2：点击 获取验证码，显示“系统异常，请稍后重试”
建议：把提示语改掉。-Jenny

**Comment by joelin109** [comment]
## 4. 导师批改
- [ ] 4.1 导师打开学生作业不能批改 （#444 1.1）
```
step 1: 老师进入导师批改界面，点击‘全部’，进入全部作业界面
step 2:选择学生完成的习题进入没有批改按钮不能操作
```
```
status: 可以点击进去批改，但页面上没显示状态
```

**Comment by joelin109** [comment]
## 版本发布注意事项：
- [x] 1. 整理习题历史数据整理 （#407）
```
Step1. 建表: content_quiz_quesion
Step2. 服务器上运行脚本 node src/test/question_migration.js 
            - 迁移数据到新表 content_lesson_quiz
Step3. 删除历史表content_lesson_quiz
           - 该名 delete_content_lesson_quiz


- From Kim
```


<br>
<br>
<br>

## 8、待确认需求
-  8.1、学习首页：视频作业的状态
```
需求：以学生打卡为准
反馈：大家都不愿意打卡


- 更新：2018-07-09
  - 以学生打卡为准
```

**Comment by joelin109** [comment]
## 学生全部作业
#### 学生查看模式
![stutasksforstu](https://user-images.githubusercontent.com/23466882/42740558-b66b65fc-88db-11e8-89da-19323cd2eb6f.jpg)
#### 老师查看模式
![stutasksformentor](https://user-images.githubusercontent.com/23466882/42740557-b4b14a92-88db-11e8-9a8e-22d18526036e.jpg)

**Comment by zhuyichun** [comment]
- [ ] 新人优惠券获取失败
```
step 1:app在课程详情页'点击推荐的积分'分享到朋友圈
step 2：微信访问官网登录账号18516157099/zhuyichun
step 3：点击朋友圈链接进入课程详情页
step 4:app登录18516157099/cine
step5 :微信课程详情页点击‘立即领取’获取新用户专享卷，弹窗提示优惠券已成功发送至账户‘18516157099’，优惠券码‘49874106’
step 6:后台检查优惠券码‘49874106’，没有绑定userId。登录账号18516157099没有获取到这张优惠券
```
