### ISSUE TITLE
H5-学习系统: 词汇学习-卡片式

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#426]
## 需求
- [ ] 1. 卡片式学习
- [ ] 2. 词汇测试规则调整
```
- 测试错误的单词不需要重复测试
- 测试需要有准确率数据
- 私塾作业：准确率>90% 才算作业完成
```

#### 交互图
https://pro.modao.cc/app/nHS4ruXc3vBL3butulc1ukvSlsHYli8#screen=s16A807A0991532339006162

测试问题反馈 #448

**Comment by joelin109** [comment]
- [ ] 7.2. 单词学习内容，与底部的测试按钮之前有一条线，没有显示，如图：
<img width="1021" alt="2018-07-02 10 16 32" src="https://user-images.githubusercontent.com/32318334/42142297-24f79dde-7de1-11e8-8ae9-82862e420919.png">

- [ ] 7.3. 词汇学习， 序号，单词，音标，喇叭之间不是特别齐，能否尽量显示在一条水平线上，如图：
<img width="308" alt="2018-07-02 10 18 03" src="https://user-images.githubusercontent.com/32318334/42142368-82bb637e-7de1-11e8-9bb4-40b27f0553cd.png">

```
From Ana
```

**Comment by joelin109** [comment]
## PC 端
**1. 词汇学习入口**
![default](https://user-images.githubusercontent.com/20130469/43300569-8771b0ac-9192-11e8-845d-2114350bef6b.png)

<br>

**2. 卡片式**
![default](https://user-images.githubusercontent.com/20130469/43300642-edc7855c-9192-11e8-8c67-5e49baf83a15.png)

<br>

**3. 单词已认识界面**
![default](https://user-images.githubusercontent.com/20130469/43300648-f06e9f5c-9192-11e8-938a-88f07d799b4e.png)

<br>

**4. 单词鼠标悬浮效果**
![default](https://user-images.githubusercontent.com/20130469/43300650-f67bc5aa-9192-11e8-8062-a1c20b1c13d1.png)

<br>

**5. 单词中文解释**
![default](https://user-images.githubusercontent.com/20130469/43300654-f8dc77ae-9192-11e8-8d39-d74fec754a78.png)

<br>

**5. 单词中文解释鼠标悬浮效果**
![default](https://user-images.githubusercontent.com/20130469/43300658-fcccd9da-9192-11e8-81e5-cf7005058d0d.png)

<br>

**6. 列表式单词学习**
![default](https://user-images.githubusercontent.com/20130469/43300675-207dcdf8-9193-11e8-9130-8d5b5b6c397c.jpg)


**5. 单词学习结束**
![default](https://user-images.githubusercontent.com/20130469/43300681-26d043e8-9193-11e8-8fe6-61686663c8a2.png)

**Comment by zhuyichun** [comment]
## PC
- [ ] 列表式显示单词有问题
```
step 1：进入单词任务，点击列表显示
step 2:关闭显示全部
step 3:把NO.***单词勾选为已认识
step 4:打开显示全部
step 5:预计列表中显示NO.***且标记为已认识。实际没有显示NO.***单词
```

**Comment by joelin109** [comment]
#410

**Comment by zhuyichun** [comment]
未完成部分迁移到#445
