### ISSUE TITLE
H5-营销活动: 让用户通过扫码或者点击链接, 自动领用优惠券功能

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#429]
```
代码路径：
https://github.com/bstcine/cine.pwa/tree/master/src/client/entry/temp
```

**Comment by zhuyichun** [comment]
本次书展活动是下周日，希望最迟2017/07/26能完成

为了配合近期的营销活动，需要增加一个优惠券自动领用功能，能够让用户通过扫码或者点击链接，直接在手机上自动领用优惠券，并且领取后，优惠券能自动发放到用户账户。
领取步骤如下图：
其中Step2的界面可能需要Ana设计一下。
[大致的交互界面](https://pro.modao.cc/app/LIuvD7BySpjpTjNyrZ1VHdvjGbAy1Qe)

**Comment by zhuyichun** [comment]
测试用例：
- [ ] 1.扫码后跳转页面是否正确
- [ ] 1、访问后页自动生成的优惠券是否和后台设置的一致（标题、价格、有效期）
- [ ] 2、登录状态点击‘点击立即领取’按钮是否跳转到我的优惠券界面
- [ ] 3、在我的优惠券界面查看新增加的优惠券是否和访问页面生成的优惠券一致（优惠券码、价格、标题、有效期）
- [ ] 4、优惠券能否转让
- [ ] 5、优惠券能否使用
- [ ] 6、未登录状态点击‘点击立即领取’按钮是否跳转到登录界面

**Comment by AaronLiDangkun** [comment]
api参考: /api/web/createCoupon
