### ISSUE TITLE
H5-学习系统: 学习首页-私塾作业完成后打卡   

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#435]
## 需求
- 学习周数：从老师布置的第一个作业开始
- 生词数量：词汇作业的词汇数量相加
- 语法点数量：课件作业Lesson的语法点数量相加
```
- Lesson的语法点数量: 数据库某列字段提供
```
- 视频课件时间：课件作业Lesson的时长相加
- 英文写作：作文作业数量（新作业类型）

**Comment by joelin109** [comment]
属于 #410 

## PC UI （本周作业不需要下滑线）
![learn-home](https://user-images.githubusercontent.com/23466882/45012521-01427080-b04a-11e8-8138-04dc534a7f42.jpeg)

**Comment by joelin109** [comment]
## 分享后UI - 已取消
![1](https://user-images.githubusercontent.com/23466882/44571634-e0f5f480-a7b3-11e8-8e8c-1d0c8cc579fd.png)

**Comment by daweilv** [comment]
Q1:
二维码跳到什么地方需要想清楚
```
二维码跳到详情页
http://www.bstcine.com/content/course?cid=d0115246233481413BmQb3rHwG
```
Q2:
私塾老师的头像、简介字段缺少，作文、作文篇数、知识点字段缺少

**Comment by Anawangqi** [comment]
### 私塾分享-新版 (2018-09-07) - 取消
![-0903-5](https://user-images.githubusercontent.com/32318334/45068804-c8fb6a80-b0fb-11e8-9947-a2b12a2385fd.png)

**Comment by Anawangqi** [comment]
### 私塾分享-新版 (2018-09-12)

![-0911-3](https://user-images.githubusercontent.com/32318334/45398971-e5a61e00-b678-11e8-8bbf-07561afcceac.png)
