### ISSUE TITLE
IOS-商城：搜索已经购买的课程仍然有立即购买的按钮

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#44]
bug 描述：
在商城-课程搜索-输入一门已经购买过的课程-点击课程-页面底端有立即购买按钮并可以提交订单到支付页面时点击微信支付会有订单获取失败的文字提示

**Comment by limingLiuBaBa** [comment]
修改完成

**Comment by joelin109** [comment]
Reason?

**Comment by limingLiuBaBa** [comment]
status : 修改完成.
bug reason : 原先是以pay_status 作为判断依据,但是搜索接口返回数据中无此字段,现改为以详情展示界面的can_learn 字段为依据判断是否已购买.
