### ISSUE TITLE
API-购买与支付：支持信用卡跨境支付

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#442]
## 需求
```
收款账号：境外

国内用户：可通过Visa信用卡支付 “Cine课程”
```
```
支付宝国际版的技术环节打通之后，立刻进行支付测试，
先用立伟的美国个人账号测试，再用波士顿公司的真实银行账号测试。

- From Email
```

<br>
<br>

### 目前情况, 使用Solution3
```
Solution1. 国际支付宝
Status: 暂停

Solution2.信用卡支付
Status: 暂停

Solution3. 支持集成 Stripe.com 到我们系统
Status: Working

Solution4.  Squareup.com
Status: 手工通过邮件给客户发账单，客户支付
           - 目前可使用，但不够方便 且也没有发现可集成的SDK
```

<br>
<br>

### Stripe收费
https://stripe.com/us/pricing

- 2.4.02

**Comment by daweilv** [comment]
## Solution 1 : 国际支付宝
https://global.alipay.com/products/online

### Settlement
1. Supported currencies
USD, EUR, JPY, GBP, CAD, AUD, SGD, CHF, SEK, DKK, NOK, NZD, THB, HKD
Settlement Mode
2. Settlement per amount: when to-be-settled amount reaches or exceeds 5000USD (the lower limit), the total amount of to-be-settled fund will be transferred to the receiving bank account of the merchant.
Alipay will take care of the remittance fee of the settlement bank and the merchant is responsible for any processing fee charged by the intermediary bank and the receiving bank.

### Standard Cost
1. If the total transaction volume of the preceding calendar month is less than 1 million RMB, the applicable rate of the current calendar month will be 2.2%.
2. If the total transaction volume of the preceding calendar month amounts to or exceeds 1 million RMB but less than 3 million RMB, the applicable rate of the current calendar month will be 2%.
3. If the total transaction volume of the preceding month amounts to or exceeds 3 million RMB but less than 10 million RMB, the applicable rate of the current calendar month will be 1.8%.
4. If Transaction Value of the preceding calendar month amounts to or exceeds 10 million RMB, the applicable rate of the current calendar month will be 1.6%.

```
Status: 暂停
```

**Comment by daweilv** [comment]
## Solution 2 : 信用卡支付
TRY 1：VISA
经电话联系 VISA 客服确认：VISA 不直接跟商家合作，商户希望使用 VISA 需要和银行谈，与银行签约。也就是说，如果希望支持招商银行信用卡，需要去和招商签约。如果希望支持农业银行信用卡，需要去和农业签约。这样信用卡只能支持国内支付，支不支持外汇支付需要和银行方咨询。
苹果官网之所以支持信用卡直接支付，是因为苹果本身就是持牌机构。

**Comment by daweilv** [comment]
## Solution 3 : stripe.com
支持集成到我们系统
#### 注册
https://dashboard.stripe.com/register
#### 完善信息
https://dashboard.stripe.com/account/details
> We need to learn more about you and your business before you can process payments on Stripe. The information you provide will only be visible to the account owner and administrators. 

```
Status: 招行双币信用卡支付 0.5 美元测试通过。
```

**Comment by daweilv** [comment]
## Solution 4 : squareup.com
手工通过邮件给客户发账单，客户支付。未找到第三方集成相关 API

```
Status: 备用
```

**Comment by joelin109** [comment]
#410
#459

**Comment by daweilv** [comment]
Q1：订单统计后台希望以怎样的展示方式把“美元”表示出来？
/admin/tool/queryStatOrders
![image](https://user-images.githubusercontent.com/7405300/45610084-4ffdfa80-ba8d-11e8-8b38-c1c927510763.png)

**Comment by joelin109** [comment]
### 手机版
![app_ -1](https://user-images.githubusercontent.com/32318334/45617614-716ae080-baa5-11e8-81c2-733fb79e37dc.png)

<br>
<br>

### PC版
![pc_](https://user-images.githubusercontent.com/32318334/45617589-5ef0a700-baa5-11e8-9db5-70386b0c9bcc.jpg)

**Comment by zhuyichun** [comment]
- [x] 1、pc&iOS-web&Andr-web好了，APP端没好
- [x] 2、课程详情页面价格应该显示$***,不是￥***

**Comment by daweilv** [comment]
iOS详情页逻辑特殊，暂不支持APP国际支付，改为提示到PC端支付
