### ISSUE TITLE
私塾模块-导师: 导师分配&查看&批改- 待改进问题列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#444]
### P1   
- [x] 1.1 私塾分享：可以配置默认的“学习时间” & “词汇数量” & “语法点” & “Lesson视频时长” & “作文数量” - `Verified`
```
- 原因：有些老师，没有历史任务分配数据
- 默认为 0， 0 ， 0 ， 0， 0
```
- [x] 1.2 PC-Admin：导师分配任务- 添加新任务“线下- 第** 周线下作业汇总”
```
学习首页：添加一种新作业
- 类型：线下
- 主题：第** 周线下作业汇总
- 功能：点击显示 “后台导师输入的具体线下作业汇总的内容”
- 前端：不用显示状态 “待完成” - `P2`
Deadline：2018-09-28
```
![271538116174_ pic_hd](https://user-images.githubusercontent.com/23466882/46193281-2fa52a00-c330-11e8-9677-a7d25b34dc40.jpg)

<br>
<br>

### P2
- [ ] 2.1 任务列表：一级节点只可展开与收起，不可选择打钩
- [ ] 2.2 在新建/编辑任务界面，增加布置作文功能，导师可在线添加作文题目&作文说明。学生可以回传已完成的电子版作业给老师。

- [ ] 2.3 在布置任务界面，增加可以下载的1万词频pdf表。

**Comment by joelin109** [comment]
## 1. 学习系统（私塾模块）
- [ ] 1.1 历史作业：学习首页 -》历史作业；导师批改-》学生作业-》全部作业
```
目前：没有导师查看模式
```
#### 学生查看模式
![stutasksforstu](https://user-images.githubusercontent.com/23466882/42740558-b66b65fc-88db-11e8-89da-19323cd2eb6f.jpg)
#### 导师查看模式
![stutasksformentor](https://user-images.githubusercontent.com/23466882/42740557-b4b14a92-88db-11e8-9a8e-22d18526036e.jpg)

**Comment by joelin109** [comment]
## 4. 导师批改
- [ ] 4.1 导师打开学生作业不能批改 （1.1）
```
step 1: 老师进入导师批改界面，点击‘全部’，进入全部作业界面
step 2:选择学生完成的习题进入没有批改按钮不能操作
```
```
status: 可以点击进去批改，但页面上没显示状态
```

**Comment by zhuyichun** [comment]
- [ ] 1、不能添加作文说明
- [ ] 2、作文作业没有完成状态

**Comment by zhuyichun** [comment]
- [ ] 1、作文标题和线下作业汇总都填写的情况会生成2个任务
```
建议取消作文标题生成作文任务，将作文在线下作业汇总中填写
```

**Comment by joelin109** [comment]
## 老师反馈
- 有的学生2周学习一次
- 有的学生， 可能中间暂停 2-3周
