### ISSUE TITLE
Realese-v2.4: 测试发现新问题反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#445]
## Must fix
- [x] 1.1-6、词汇测试的选项UI错乱[查看图片](https://user-images.githubusercontent.com/20130469/45099271-76509b80-b159-11e8-87e7-6913d154bd51.jpeg) - `David`
```
iPad4
- From Larry

- Verified by Joe
```
- [x] 1.2. 商城：课程详情页- 用户没有登录时，点击分享，分享成功后会提示‘user_not_fonud’   - `David`
```
- Verified by Jerry
```
- [x] 1.3. ipad 个人中心-我的优惠券：添加按钮只显示一点点弧度，都快找不到了 - `David`
```
- Verified by Joe
```

- [x] 1.4、登录官网，在密码重置的页面，输入一个没有注册过的账号，提示语为”系统异常，稍后重试”，建议更换提示文字为“此号码尚未注册，请注册后重试”。- `Jerry`
```
- Verified by Joe
```

<br>
<br>

## Nice to have
- [ ] 2.1

**Comment by zhuyichun** [comment]
- [x] 1、手机web普通学生访问个人中心显示核心语法测试链接
- [x] 2、用户没有登录时候详情页分享提示‘user_not_fonud’
- [x] 3、个人中心-我的优惠券：添加按钮颜色不对
- [x] 4、登录官网，在密码重置的页面，输入一个没有注册过的账号，提示语为”系统异常，稍后重试”，建议更换提示文字为“此号码尚未注册，请注册后重试”。
- [ ] 5、APP课程学习打卡没有成功提示打卡成功
```
step 1:课程学习页面点击‘学习打卡’，进入发表页面
step 2:点击取消，自动跳转回APP并弹窗提示打卡成功
```
- [x] 6、词汇测试的选项UI错乱[查看图片](https://user-images.githubusercontent.com/20130469/45099271-76509b80-b159-11e8-87e7-6913d154bd51.jpeg)
```
iPad4
- From Larry
```
-  8、ipad 4个人中心-我的测试：词汇量测试列表UI-列表分割线颜色混乱，随机的深浅不一致
- [x] 9、ipad4 个人中心-我的优惠券：添加按钮只显示一点点弧度，都快找不到了  -bug p1
```
ipad4 学习首页-历史作业：查询按钮也只显示一点点，类似问题
```
- [x] 10、ipad4 个人中心-我的测试：横屏时候不显示测试语法’&‘测试词汇量’按钮 -bug p2
ipad4 学习首页-历史作业：横屏时候同样显示超出了屏幕可视区域[图片查看](https://user-images.githubusercontent.com/20130469/45206859-bc704100-b2b8-11e8-94af-57c5839750fb.jpg)
  -bug p2

- [x] 11、登录官网，在密码重置的页面，输入一个没有注册过的邮箱账号，点击发送验证码，提示发送成功，应该更改为‘该邮箱未在善恩注册，试试用手机找回？’-bug p4
- [x] 12、商城后台-课程管理-首页tab:点击操作‘关联课程’：进入页面还需要点击‘查询已关联课程’才显示已关联。更改为初始化就显示已关联课程
