### ISSUE TITLE
H5-学习系统: 词汇模块 - 测试反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#448]

**Comment by iYuanYuan2** [comment]
## 1. 词汇课程页
- [ ] 1.1.

**Comment by zhuyichun** [comment]
起点评估颜色背景：#449

**Comment by joelin109** [comment]
## 2. 课程单词起点评估
- [x] 2.1 需求：起点评估的测试范围是1-10000，只需要测一次既可以知道从学习起点。并且直接跳转至需要学习的词汇区域。  - `Alice`

**Comment by joelin109** [comment]
##  3. 词汇学习-卡片式&列表式
- [x] 3.1 显示中文释义的地方，词性和中文解释中间需要空一格 `Alice`
[#click](https://user-images.githubusercontent.com/35132688/44513045-ed644980-a6ee-11e8-998f-bcd2dfe2e20e.JPG)
```
- 词性和中文解释中间需要空一格
- 中文释义中分号请用中文格式
```
-  3.2 卡片式随机播放状态下，点击已认识连续多个情况下页面显示空白（测试点击10个左右吧）-jerry-bug
```
无法重现
```
- [ ] 3.3 箭头颜色需要加深，显示灰色会误以为是不能点击操作- `Alice`
[#click](https://user-images.githubusercontent.com/35132688/44513812-07069080-a6f1-11e8-9625-df025b105de7.JPG)

- [ ] 3.4 1000单词中7&9一样的单词翻译不同，27&12单词和翻译都完全一样 -bug p1 -Jerry
- [ ] 3.5 1000单词中28&29类似近义词的抓取的释义完全不同导致测试错误 - bug -P2 -Jerry

**Comment by joelin109** [comment]
##  4. 词汇学习- 测试 
```
词汇作业测试 90%通过，作业才算完成
```
- [x] 4.1 共11道词汇，答对10道，提示已掌握所有单词   - `Alice`
```
Step 1：点击-10000基础词汇No.1111 ~ No.1122
Step 2：点击-词汇测试
Step 3：测试完成，提示已完成所学任务。

正确：应该是？（Alice提供文字）
已修改为："已完成词汇作业任务，返回学习首页"
```

-  4.2 单词中的干扰项，来源于这10个单词（不确定是否正确，但是测试中看着很怪） - `Alice`
```
Step 1：点击-10000基础词汇No.1111 ~ No.1122
Step 2：点击-词汇测试
Step 3：测试完成，提示已完成所学任务。
```
-  4.3 进入词汇课程页面会两次刷新  账号ssjerry/cine- `Jerry`
```
Step 1：点击词汇课程Top1000词汇：1-3000第60组。
Step 2：点击‘Top词汇: 2951-3000’左边的返回箭头
Step 3：页面默认显示定位在13组，二次刷新定位在60组
```
- [ ] 4.4 词汇测试：选错的选项后，希望停留的时间为5S
```
 step1：点击 我的学习 →背单词；
step2：点击善恩核心单词1-3000；
step3：点击第1组1-50；
step4：点击”词汇测试“→“开始测试”；
优化建议：选错了的词汇希望停留的时间可以长一些。-by Jenny.
```
-  4.5 我的学习 - 词汇课程:‘我的学习’鼠标悬浮状态图片和文字的下划线不一致，不在同一条水平线

**Comment by joelin109** [comment]
### 大家针对需求的反馈
-  5.1、首次进入“背单词”页面，建议显示如何使用 `Alice`
-  5.2 建议学完一遍的时候 设置提醒下已经学完一遍。 `Alice`
-  5.3 需求--UI需要重新调整 `Alice`
[#click](https://user-images.githubusercontent.com/35132688/44513586-55fff600-a6f0-11e8-8ebc-5da600e58d7c.JPG)
- [x] 5.4. 选中“自动播放“按钮：`Alice`
```
待确认
1、是否需要显示中文（如显示需调整速度3秒/个）；
2、没有暂停按钮。
```
- [ ] 5.5 进入背单词页面，无法找到单词的中文释义以及点击下一个单词的位置。
```
step1：点击 我的学习 →背单词；
step2：点击善恩核心单词1-3000；
step3：点击第1组1-50；
step4：点击 “背单词”，进入背单词页面
问题：1）不知道如何查看单词的中文释义，且没有明确提示；
2）不知道在哪个地方点击学习下一个单词，没有明确提示。 -by Jenny.


- 最新确认：
- 提供帮助说明
```

-  5.6
```
step1：点击 我的学习 →背单词；
step2：点击善恩核心单词1-3000；
step3：点击第1组1-50；
step4：点击 “背单词”，进入背单词页面
优化建议：感觉每次点击完“已认识”后，鼠标要再移动到别的地方点击 下一个单词，不停的来回移动，觉得很累。有没有办法点击“已认识”后，自动跳转到下一个单词呢？如果不认识,则需要手动点击下一个单词。-Jenny
```
- [ ] 5.7 建议测试起点在1-500区间添加分段,单词基础差的测试结果都是从1开始不合理 -Jerry
- [ ] 5.8 测试背单词起点的1-1000区间难度有些大 -Jerry
- [ ] 5.9 测试背单词起点的单词来源建议获取‘善恩核心10000词汇’中词汇测试错误率高的单词集合-Jerry
