### ISSUE TITLE
安卓-修复 v1.0.6 版本 BUG

### ISSUE THREAD

**Issue by itwangxiang** [bstcine/cine-tasklist#45]
`v1.0.6`

- 退出播放器异常  IllegalStateException
  - 原因： 该异常表示，当前对客户端的响应已经结束，不能在响应已经结束（或说消亡）后再向客户端（实际上是缓冲区）输出任何内容
  - 解决：将 onBackPressed() 改为 finish()

**Comment by joelin109** [comment]
那个文件的onBackPressed()？

**Comment by itwangxiang** [comment]
com.bstcine.course.ui.aplay.APlayActivity
