### ISSUE TITLE
H5-个人设置: 我的优惠券- 调整显示内容

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#450]

**Comment by Anawangqi** [comment]
### 优惠券版式调整

PS: 优惠券默认描述显示两行（两条），超过两条可点按钮展开。只有两条，则不城显示展开按钮，没有描述则不显示。

### 手机版

**1. 未使用**
![app_](https://user-images.githubusercontent.com/32318334/44254316-070c1980-a235-11e8-8803-b28d6eb470bd.png)

**2. 已使用，已过期**
![app_ -](https://user-images.githubusercontent.com/32318334/44254314-06738300-a235-11e8-9530-0df5f1863a83.png)

### PC版
![pc- - -2](https://user-images.githubusercontent.com/32318334/44254363-36bb2180-a235-11e8-9ed1-90544ea590b9.jpg)
