### ISSUE TITLE
PC-Admin: 习题管理- 知识点&习题维护的测试问题反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#451]
### 知识点
- [x] 1.1. 查询条件：类型（可查询非单词的）& 修改者（账号） -`p1` - `?`
```
默认查询条件：非单词的
测试：目前没有修改者，类型是否可变为CheckBox选择

测试反馈：
默认查询条件：非单词的
开发反馈
需要动框架，暂不默认支持
```

<br>

###  习题导入
- [ ] 2.1 结果列表：显示字段- LessonID、题型、状态、更新时间、题干（固定长度显示），知识点
```
Lesson: 如果可以，最后可以显示 “动物农庄第1课”
题干：如果可以，显示有最长的固定长度
```

<br>

### 习题列表
- [ ] 3.1. 编辑习题：预览放在添加的旁边（可以是文字链接 或 小Button） 

<br>

### 待审核列表
- [x] 4.1-2.10审核通过后，管理员可以修改习题   -`p1`
```
- 修改习题里面的内容
- 把包含该习题试卷状态改为失效
```

- [ ] 4.2. 查询列表：不要文字“勾选”，底部“全选” 与 “提交”Button 分开。
参考 [UI设计](https://user-images.githubusercontent.com/23466882/43699523-af418c8c-9981-11e8-9266-e85096da9bf6.jpg)   
```
```

**Comment by zhuyichun** [comment]
### 2、习题审核
- [ ] 2.1查询结果展示不对，包含知识点查询显示错误
[查询条件不含知识点](https://user-images.githubusercontent.com/20130469/44323664-66606880-a485-11e8-9e1e-37380a9a488b.jpg)
[查询条件包含含知识点](https://user-images.githubusercontent.com/20130469/44323697-90b22600-a485-11e8-8959-bcd83a555025.jpg)

**Comment by joelin109** [comment]
### 1、知识点
- [x] 1.1查询条件：名称、类型（可多选复选框）、时间区间、修改者（账号）-优化-p1
- [x] 1.2所有导入功能页面添加导入模板下载链接，点击下载模板
- [ ] 1.3 规范老师账号信息 -Alice
- [ ] 1.4 知识点查询条件参数错误,点击简答查询会将更多查询中的参数作为条件查询
```
step 1：点击更多查询弹窗输入: 名称"a bit of”，日期：2018-08-20，关闭弹窗
step 2：点击搜索，显示无结果
step 3:点击更多查询弹出弹窗并清除日期输入框的内容，关闭弹窗
step 2：点击搜索，显示出正确结果
```
### 2、习题维护
- [x] 2.1单选题、简答题、填空题，审核页面知识点查询获取不到数据 -bug -p1
- [ ] 2.2 查询条件中将查询按钮大小调到和添加按钮一致 -优化-p3
- [ ] 2.3 习题列表：点击修改将错误的lessonId输入点击保存提示“更新失败，system_error” -优化-p3
```
提示更改为：lessonID错误，请检查
```
- [ ] 2.4 习题列表：点击修改没有对专用做验证，是专用但lessonID为空也能保存 -bug -p2
- [ ] 2.5 习题导入-显示字段：题型、状态、修改时间、lessonID（显示效果：动物农庄第1课）、题干（固定长度显示）-优化 -p2
- [ ] 2.6 习题导入-导入数据量较大时候，导入过程耗时较长是否有UI上标识后台正在处理中 -优化 -p4
- [ ] 2.7 习题添加备注字段接收审核传回来的备注内容，且有内容显示备注，没有内容不显示。
- [ ] 2.8单选题、简答题、填空题，审核不通过时候，老师打开编辑页面状态没有默认值(待提交) -bug -p3
- [x] 2.9单选题、简答题、填空题，审核不通过时候，老师打开习题维护界面查询审核不通过只有全选复选框没有单个题目的复选框-bug -p1
- [ ] 2.10审核通过后，管理员可以将习题修改为失效  需求 -p2
- [ ] 2.11.习题：审核通过的习题允许进行修改
```

```

**Comment by kimliss** [comment]
# Run Sql
### 将知识点自增长初始值设置为 100000
- [x] www
- [x] dev
```sql
DROP TABLE IF EXISTS `content_keypoint`;
CREATE TABLE `content_keypoint` (
  `id` int(11) NOT NULL AUTO_INCREMENT COMMENT '编号',
  `name` varchar(150) NOT NULL COMMENT '名字',
  `type` varchar(1) NOT NULL COMMENT '类型[0:单词，1:短语，2:语法]',
  `parent_id` int(11) NOT NULL COMMENT '父ID',
  `source_type` varchar(1) NOT NULL DEFAULT '0' COMMENT '来源类型[0:默认，1:维护导入，2:抓取导入]',
  `status` varchar(1) NOT NULL DEFAULT '1' COMMENT '状态 [无效:0,有效:1]',
  `create_at` varchar(24) DEFAULT NULL COMMENT '创建日期',
  `create_by` varchar(30) DEFAULT NULL COMMENT '创建者',
  `update_at` varchar(24) DEFAULT NULL COMMENT '修改日期',
  `update_by` varchar(30) DEFAULT NULL COMMENT '修改者',
  `delete_at` varchar(24) DEFAULT NULL COMMENT '删除日期',
  `delete_by` varchar(30) DEFAULT NULL COMMENT '删除者',
  PRIMARY KEY (`id`),
  UNIQUE KEY (`name`,`type`)
) ENGINE=InnoDB AUTO_INCREMENT=100000 DEFAULT CHARSET=utf8 COMMENT='知识点';
```

**Comment by kimliss** [comment]
# Run Sql
### 清空知识点,习题以及关系表 - `dev`
- [x] dev
``` sql
delete from content_keypoint;
ALTER TABLE content_keypoint AUTO_INCREMENT = 100000;
delete from relation_content_keypoint_question;
delete from content_quiz_question where create_at > '2018-08-31 11:00:00';
```

**Comment by joelin109** [comment]
#459

**Comment by zhuyichun** [comment]
## 遗留问题
-  [x] 5.1.需要支持具有不同类型知识点的习题上传  -verified
