### ISSUE TITLE
H5-学习系统: 学习首页- 背单词模块（包含top10000课程 ）           

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#452]

**Comment by joelin109** [comment]
#410

## PC UI
![learn-home](https://user-images.githubusercontent.com/23466882/45012521-01427080-b04a-11e8-8138-04dc534a7f42.jpeg)

**Comment by zhuyichun** [comment]
起点评估颜色背景：https://github.com/bstcine/cine-tasklist/issues/449

**Comment by zhuyichun** [comment]
- [ ] 1.建议测试起点在1-500区间添加分段，
- [ ] 2.测试背单词起点的1-1000区间难度有些大
