### ISSUE TITLE
临时促销: 开学季团购&满赠活动需求 (Deadline-20180829)

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#453]
## 临时促销

- [x] 1.1、我们会在`有赞`渠道销售课程，Jenny会定期提供一个订单的Excel。 
因此需要定期（每天）批量的开通用户的学习权限，包括已有善恩账号的老用户和尚未注册过账号的新用户。- `Kim` - [有赞导入文档.xlsx](https://github.com/bstcine/cine-tasklist/files/2327328/rev3.xlsx) - `Done`

```
提供一个`导入功能`:
- A：批量创建尚未注册过账号的新用户 （是否注册以手机号为判断标准）
- B：批量创建订单，开通用户的学习权限（有短信通知）
- `有赞`来的用户&订单都应该有来源标识


- 提供需要的信息列表
- 用户需要来源标识
- 订单需要来源标识
```
```
Solution: 
1. 校验数据合理性
   1.1 手机号、课程ID、实付金额 非空
   1.2 手机号是否非法
   1.3 实付金额是否纯数字并且大于等于0
2. 查询用户表：手机号是否唯一
3. 查询课程表：课程ID是否存在
4. 查询订单表：订单是否已开通
5. 创建未注册用户
6. 创建订单并发送通知
```
- [x] 1.2、我们会有一个满368元赠90元优惠券的活动。需要在固定日期区间内（比如9/1-9/7）去判断用户在这期间购买课程的实付累积金额是否超过368，如果超过则赠送一张价值90的图书优惠券，并且在发券后用户能够有短信通知。在此期间内每名用户仅限领取一张图书优惠券。- `Kim`
```
满388元赠90元优惠券的活动提供一个UI页面：
- 活动开始时间
- 查询Button （符合条件的）- ’Nice to have‘
- 确认Button
- 用户列表（序号 & 账号 & 手机号 &Email & 实付累积金额）

```

<br>
<br>

### 测试前提供：
- [x] 2.1. 提供测试&操作的位置   - `Kim`
```
- 管理员登入
- 管理菜单-营销活动-派发优惠券

https://dev.bstcine.com/admin/tool/padCoupon
```
- [x] 2.2. 针对1.1，确认Alice需要提供的信息列表 - `Jerry&Kim`
```
phone，course_id，pay_price
```
- [x] 2.3. 针对1.1，提供查询`有赞`渠道的订单的SQL
``` sql
SELECT O.`id` AS 'Order_ID', C.`name`, `lesson_id` AS 'Course_ID',  `pay_price` , `pay_at` ,  `other_sn` , O.`remark` ,
`user_id`, U.`login`, U.`phone`, U.`nickname` , U.`batch_no` 
FROM t_order AS O, `t_user` AS U, `content_course`  AS C
WHERE O.`user_id` = U.`id` AND C.`id` = O.`lesson_id` 
AND pay_type = '11' AND pay_status = '1'
ORDER BY C.`id`, U.`id` , O.`pay_at` DESC 

- From Joe
```

<br>
<br>

#### Deadline : 2018-08-27

**Comment by zhuyichun** [comment]
- [ ] 1.1建议添加查询按钮，点击查询复合调发送优惠券条件的用户  -优化
- [ ] 1.2 等于388的用户没有获取到优惠卷  -Bug

**Comment by itwangxiang** [comment]
1. 校验数据合理性
   1.1 手机号、课程ID、实付金额
   1.2 手机号是否非法
   1.3 实付金额是否纯数字并且大于等于0

2. 查询数据库是否存在手机号对应多条用户

3. 查询数据库是否存在课程ID

4. 查看数据库订单是否重复

**Comment by joelin109** [comment]
### 测试基本用例
- [x] 2.1 新用户添加成功
-  2.2 新用户属性：积分、密码
```
密码为手机后六位  -true
新用户没有获得10分注册积分 -false

```
- [x] 2.3 多次导入，只创建一条订单
```
case 1:：已注册手机 已购买的课程ID
case 2：已注册手机 没有购买过的课程ID 一个不存在的课程ID
case 3：没有注册过的手机 没有购买过的课程ID 个不存在的课程ID
```
- [x] 2.4 收到开通课程短信通知
- [x] 2.5 收到优惠卷短信通知，账号中有该优惠卷
- [x] 2.6 优惠卷只发送一条
- [x] 2.7 优惠卷可以正常使用
- [x] 2.8 优惠券备注信息提示仅用于图书
- [x] 2.9 通知用户课程开通成功的短信错误
- [ ] 2.10 网站统计后台-订单明细报表：有赞订单支付方式错误

**Comment by iYuanYuan2** [comment]
## 测试反馈
- [x] 3.1 新添加的用户（有赞）有个来源标识
```
batch_no = "youzan"
```
- [x] 3.2 优惠券名称要改下，改成："买课赠书活动券"

<br>
<br>

## 发布准备
- [x] 4.1.创建优惠券短信模板
```
INSERT INTO `t_templatesms` (`id`, `type`, `message`, `create_at`, `create_by`, `update_at`, `update_by`, `delete_at`, `delete_by`)
VALUES
	('d011535508315436aePr1UYhUT', '6', '{#coupon_name#}码：{#coupon_no#}，已添加到您的账户，有效期至{#expire_at#}。请至官网或APP中“教材教辅”栏目挑选喜爱的图书。', '2018-08-29 10:05:15', '1', '2018-08-30 09:52:34', '1', NULL, NULL);
```
此次开学季满赠活动的优惠券模板：
【善恩英语】{#coupon_name#}码：{#coupon_no#}，已添加到您的账户，有效期至{#expire_at#}。请至官网或APP中“教材教辅”栏目挑选喜爱的图书。
