### ISSUE TITLE
H5-学习系统：词汇学习模块- 重新调整UI & 整理中文翻译等

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#455]
### 词汇模块重新调整部分
- [x] 1. 学习首页: 词汇课程入口                             - `P2`
- [x] 2. 词汇课程: 善恩核心10000词汇- 分10个大批次（1000一个）    - `P2`
- [x] 3. 词汇学习: 只显示根据词性对应的中文翻译（且只显示2个） - `P2`
- [x] 4. 起点评估: 善恩核心10000词汇- 起点评估测试过程，中文干扰项的词性应该与正确选项的一致                - `p3`
```
把根据词性没有Match到中文的，明显中文翻译异常的（20几个单词）重新抓取一下
```
- [ ] 5.  词汇课程: 善恩核心10000词汇- 起点学习评估-通过`新的算法`来算起点             - `p3` #468

**Comment by joelin109** [comment]
#410

**Comment by Anawangqi** [comment]
## 卡片式学习-PC版

**1.1 词汇学习入口- 无测试成绩**
![pc_ _0 -1](https://user-images.githubusercontent.com/32318334/45086692-61aedc00-b136-11e8-93e2-f6a85dfcfb44.png)

**1.2 词汇学习入口- 有测试成绩**
![pc_ _0](https://user-images.githubusercontent.com/32318334/45086776-9753c500-b136-11e8-8f25-ffd1e5b5d972.png)

<br>

**2.正面英文**
![pc_ _1](https://user-images.githubusercontent.com/32318334/45086662-4fcd3900-b136-11e8-9a6c-a4659d93e664.png)

<br>

**3.背面中文释义**
![pc_ _2](https://user-images.githubusercontent.com/32318334/45086714-6ffcf800-b136-11e8-839c-3e7771be4f77.png)

<br>

**4.学习结束**
![pc_ _4](https://user-images.githubusercontent.com/32318334/45086728-79866000-b136-11e8-9834-7d6c1445d807.png)

**Comment by joelin109** [comment]
### 2. 课程单词起点评估
- [x] 2.2、中文释义:  释义有点奇怪且与 http://www.youdao.com/ 中文释义不一样
```
SELECT id, word, zh FROM `content_dictionary` WHERE zh like '%. ,%' ORDER BY id


目前有21个单词:
01 | 81 | more | adv. 更加；较为 det. ,pron. 更多的,gengdade
02 | 82 | these | det. ,pron. 这些
03 | 99 | many | det. ,pron. 大量的人或事物
04 | 144 | most | adv. 最；非常，极其；最多；几乎 det. ,pron. 大部分，大多数；最多
05 | 145 | another | det. ,pron. 另一个；又一个
06 | 146 | much | adv. 非常，很,更加 det. ,pron. 许多，大量
07 | 148 | own | vt. 拥有；承认 vi. 承认 adj. ,pron. 自己的；自己做的
08 | 183 | such | det. ,pron. 这样的，如此的；这样，非常
09 | 185 | few | det. ,adj. 很少的；几乎没有的 pron. 很少
10 | 192 | each | det. ,pron. 每个；各自
11 | 256 | both | det. ,pron. 双方都；两者都
12 | 257 | little | adj. 小的；很少的；短暂的；小巧可爱的 adv. 不多；稍许；稍微 det. ,pron. 不多的
13 | 311 | several | adj. 几个的；各自的 det. ,pron. 几个；数个；一些
14 | 478 | less | adv. 较少地；较小地；更小地 det. ,pron. 较少的；更少的 prep. 减去，扣除
15 | 528 | whose | det. ,pron. 谁的（疑问代词）；那个人的，那一个的
16 | 548 | half | n. 一半；半场 adv. 一半程度；部分地 det. ,pron. 半数
17 | 559 | either | adv. 也（用于否定句或否定词组后）；而且 det. ,pron. 任一，两方，随便哪一个；两者中的一个或另一个
18 | 777 | whatever | det. ,pron. 任何；一切事物；无论什么 adv. 一点都；丝毫
19 | 1198 | dozen | n. ,det. 十二个，一打
20 | 1804 | neither | adv. 也不 det. ,pron. 两者都不
21 | 1982 | fewer | det. ,adj. 较少的 pron. 较少数


```

<br>
<br>

### 3. 词汇测试
- [x] 3.1. 测试都对：然后显示“完成词汇作业任务，返回学习首页” ， 点 `确定`没反应
```
- 区分3个Case
- 1. 私塾作业-测试得分 >= 90,    `确定` 返回到 “学习首页”
- 2. 私塾作业-测试得分 < 90,    `确定` 返回到 “词汇学习入口”
- 3. Top10000课程 - 每组测试完成， `确定` 返回到 “Top10000课程”
```

**Comment by zhuyichun** [comment]
1、已认识（打钩后，不再显示）

**Comment by joelin109** [comment]
#459
