### ISSUE TITLE
 H5-商城: 课程详情页- 可选择“2年有效或永久有效”不同有效期进行购买

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#461]

**Comment by daweilv** [comment]
目前订单系统的痛点：
1. total_price、price、pay_price 字段定义模糊
> 去除 total_price、discount_price，
> 保留 price、coupon_discount、balance_discount、point_discount、pay_price
> 增加 promote_discount，原优惠活动抵扣未清晰表示出来

> 修改如下，字段是否清晰需要评审。
> price 当前价格
> promote_discount 优惠活动抵扣
> coupon_discount 优惠券抵扣
> balance_discount 余额抵扣
> point_discount 积分抵扣
> pay_price 实付金额

2. discount_price 与 coupon_discount、balance_discount、point_discount 逻辑不清晰，算法复杂
> 同1

3. 金额最小单位元，浮点计算时出现的小数点(分)计算不便
> 考虑单位降级为 分

4. 套餐订单实际被不合理的拆分了多条订单
> 拆分order 和 order_detail

5. 不支持购物车结构
> 同4

6. remark 字段实际提供给业务员使用，但实物订单的情况下又提供给用户使用
> 考虑独立出 remark 和 admin_remark 两个字段

**Comment by daweilv** [comment]
## 旧版特性：
- [x] 1.1. 支持显示优惠价、原价
- [x] 1.2. aa课程+bb课程组成套餐
- [x] 1.3. 信用卡美元购买（不考虑支持任何优惠抵扣），如，私塾课程
- [x] 1.4. 分享后免费开通课程
- [x] 1.5. 是否可用优惠券开关
- [x] 1.6. 是否可用积分开关
- [ ] 1.7. 【TBD】xx课程可补差价升级套餐
- [ ] 1.8. 【不考虑支持】需要购买xx课程才能购买该课程，如，毅学小班
- [ ] 1.9. 【不考虑支持】xx课程在购买了aa课程后再购买会优惠


<br>
<br>

## 新版特性：
#### 新版将支持的特性：
- [x] 2.1. xx课程可选2年、5年或N年有效期
- [ ] 2.3. 未上架产品可以显示在商城首页

#### 新版能支持的特性：
- [x] 3.1. xx课程且可从2年升级到N年(5年）或无限期
```
需要需求定义：有效期时间怎么添加延期
```
- [ ] 3.2. 有效期不同情况延期定义不同的价格
- [x] 3.3. 详情页显示已销售数量等
- [x] 3.4. 库存，如，实体书、xx课程限20人参加
- [ ] 3.5. 某产品限购时，显示用户限购数量，当用户购买达到上限后无法继续再购买。
```
- 视频课程&私塾： 限购1个
- 其它如书本等：不限购
```
- [x] 3.6. 重复购买，如，课程有效期升级、实体书 
- [x] 3.7. 已上架产品，可以参加闪购，已设置闪购的产品可显示还有xx:xx:xx开始抢购，闪购中的产品可显示还有xx:xx:xx结束活动，可设置抢购产品单独价格、图片，到时间自动切换
- [x] 3.8 购物车模块，aa课程+bb课程+xx课程等，加购物车满4000减500
- [ ] 3.9. 【TBD】团购

#### 新版未确定的特性：
- [ ] 4.1. 【不考虑支持】私塾课程支持预定，先付订金
- [ ] 4.2. 【TBD】客户在购买/续费课程的时候可指定生/失效日期
- [ ] 4.3. 【TBD】未上架产品，可以在系统设置上架时间，自动上架，也可在官网预告，并出现倒计时
- [ ] 4.4.  页面某个分组可以给定位链接，或者能有二级页面链接
```
这是其它主题的功能，与该需求及技术设计无关，暂不讨论
```
- [ ] 4.5.  课程转发可以不单一是链接，可以生成带二维码的图片
```
这是其它主题的功能，与该需求及技术设计无关，暂不讨论
```

**Comment by daweilv** [comment]
Q1:客户已购套餐A（一年有效期 360元），想升级套餐B（五年有效期 999元），业务流程如何操作？

升级流程：
a. 按套餐A剩余时间/1年换算剩余可退的金额，先把套餐A订单退掉，然后再补差价购买套餐B；
或者
b. 直接在套餐A的基础上续套餐B的五年

个人倾向 b 方案，续套餐A和续套餐B对于逻辑侧都是续费的概念，逻辑好处理。

**Comment by joelin109** [comment]
![4461539766649_ pic](https://user-images.githubusercontent.com/23466882/47080463-9f754900-d23a-11e8-827d-b19ab3008eb2.jpg)
