### ISSUE TITLE
H5-商城: 2级页面-在线私塾&托福SAT&分级阅读

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#465]
#### 预先准备（依赖）：
- [x] Kim提供相应的API , #473
- [x] Jerry提供真实的配置数据，获得真实的API数据（www）
```
配置情况：
- Dev已准备好


真实的API数据：官网正式上线的展示数据

测试反馈：
数据配置没有达到正式上线的基本标准
```

<br>
<br>

## 需求
- [x] 1.1. 在线私塾 
```
细节澄清：
-核心课程（同托福页面）
-录课老师：私塾老师全部显示，点击“私塾老师”不要链接
-口碑好评（同托福页面）
  - 拿后台“口碑好评”的数据
-精彩文章（同托福页面）
-资料下载（同托福页面）
```

- [x] 1.2. 托福SAT
```
细节澄清：
- 顶部固定：顶部菜单栏及Banner固定，左侧目录固定，页面滚动时只滚动简介以下栏目。
- 左侧目录与右侧内容同步：
   1. 点击左侧目录，右侧内容滚动到相应栏目；
   2. 右侧内容滚动到某个栏目时，目录需显示相应标题。

- 顶部Banner图：Ana提供，注意图片高度

- 核心课程：
   数据来源：系统已上架课程（如果在计划内的可以有“待推出”课程），具体课程选择由Alice确定
   
   UI额外澄清：
   > 单行个数：PC-Pad-phone:4-3-2
   > 最多显示12个，超出部分，点击栏目右上角“更多”，展开全部
   > 如无更多课程，则不显示“更多”按钮


- 录课老师：
   数据来源：核心课程的录课老师（具体老师介绍内容抓取官网“善恩名师”介绍内容）

   UI额外澄清：
   > 单行个数：PC-Pad-phone:5-4-2
   > 单个老师介绍可点击，点击跳转单独的老师介绍页面：例如：http://www.bstcine.com/teacher/2
   > 最多显示10个，超出部分，点击栏目右上角“更多”，展开全部
   > 如无更多老师，则不显示“更多”按钮
   > 老师介绍信息最多显示三行，显示不下的部分打省略号


- 口碑好评：
   数据来源：小助手提供，可随时上传更改
   
   UI额外澄清：
   > 单行个数：PC-Pad-phone:4-3-2
   > 最多显示12个，超出部分，点击栏目右上角“更多”，跳转现有托福好评页面
      -   http://www.bstcine.com/comments
   > 如无更多好评，则不显示“更多”按钮


- 精彩文章：
   数据来源：？

   UI额外澄清：
       1. 带图头条：共2条； 单行个数：PC-Pad-phone:2-2-1
       2. 不带图头条：条数不限，建议最多不超过8条，单行个数：PC-Pad-phone:2-2-1
       3. 点击“更多”弹出跳转微信公众号提示及公众号二维码
            文字内容：扫码进入官方公众号：善恩英语在线私塾，查看更多精彩文章！

- 资料下载：
   托福/SAT相关资料下载，PDF，RAR，Word等格式文件，点击可直接下载
   具体内容：待定

```
- [x] 1.3. 分级阅读 
```
细节澄清：

- 核心课程：
   数据来源：按图片分成六组（绘本，桥梁处，初章书，名著初阶，名著中阶，名著高阶），切分图片由Ana提供

    UI额外澄清：
    分组图片显示： 单行个数：PC-Pad-phone:3-3-2
    每组链接：绘本——首页苏斯课程定位处
                      桥梁书——首页树屋课程处
                      初章书——首页狐狸爸爸定位处
                      初阶——首页名著初阶定位处
                      中阶——首页名著中阶定位处
                      高阶——首页名著高阶定位处

-录课老师（同托福页面，点击“更多”，跳转“善恩名师”）
-口碑好评（同托福页面，跳转口碑好评的“文学阅读”界面）
  - 点击 “更多”，http://www.bstcine.com/comments/reading
-精彩文章（同托福页面）
-资料下载（同托福页面）
```

<br>
<br>

### 交互
http://192.168.1.150:9080/ejym/index.html

**Comment by joelin109** [comment]
### 托福SAT UI
![25911538966129_ pic](https://user-images.githubusercontent.com/23466882/46590791-d8017e00-cae8-11e8-870d-73ea4b8e3fdc.jpg)

**Comment by zhuyichun** [comment]
## 技术任务 - `From Joe`
- [x] 1.1.  数据： 获取真实API的数据  - `Kim`
```
调整PWA的代码：
- src/APIConfig.js
- src/client/action/subPageAction.js
- src/entry/csub/reducer/index.js - (基本不改）
```
- [x] 2.1. UI：Banner 不同的2级页面需要显示不同的图片
- [x] 2.2. UI：核心课程- 课程列表
- [x] 2.3. UI：核心课程- 分级阅读页面
- [x] 2.4. UI：私塾导师 & 录课老师
- [x] 2.5. UI：口碑好评
- [x] 2.6. UI：精彩文章
- [x] 2.7. UI：资料下载

**Comment by Anawangqi** [comment]
### 1. 在线私塾
![1](https://user-images.githubusercontent.com/32318334/46846575-ace19c00-ce12-11e8-9922-5344bab8ed3c.jpg)

### 2.托福/SAT
![sat1](https://user-images.githubusercontent.com/32318334/46846574-ac490580-ce12-11e8-887d-cae8ff1b61ea.jpg)

### 3.分级阅读
![default](https://user-images.githubusercontent.com/32318334/46846572-abb06f00-ce12-11e8-9909-1cc2b9524c7a.jpg)

**Comment by Willingkong** [comment]
### 1. PC 版调整

说明：
1. 目录：调整为横版，页面滚动时在顶端悬停。
2. 分级阅读：核心课程板块——目前对应官网上两个tab(少儿原版阅读和英文名著精读)，图片和下方主标题可点击跳转对应tab。下方小标题——系统自动抓取每个tab下的分级类目，（如果可以的话最好也能跳转）
3. tab页内容：每个tab页内容（核心课程，录课老师，口碑好评，精彩文章，资料下载），单独成为一个页面，不再像之前设计的一样在一页内滚动，点击上方tab页目录，跳转到对应页面。
tab页面中无需再出现小标题，所有内容展开，无需“更多”按钮。
（下图仅供参考，需要切分后放在不同tab页面中，并且删除下方页面中的小标题）。
![-](https://user-images.githubusercontent.com/33111306/48538448-786c6e80-e8ef-11e8-9235-cb3c37ab79c2.jpg)


### 2. 手机版UI

说明：
1. 目录：横排在最上面，并且上翻滑动时停在最上面，如果字太长显示不下，做成可滑动的效果，确保当前点击的tab在中间位置。
2. tab页内容：切分放在每个tab下面，不用在一页内滚动（UI就不单张单张做了）。
                        无需小标题，无需更多，内容全部显示。

私塾手机UI
![-](https://user-images.githubusercontent.com/33111306/48543195-fafb2b00-e8fb-11e8-961b-1321d5c70d29.jpg)


托福手机UI
![- sat](https://user-images.githubusercontent.com/33111306/48543214-08b0b080-e8fc-11e8-9f39-c6ea189a0ffb.jpg)


分级阅读手机UI
![- 1](https://user-images.githubusercontent.com/33111306/48543231-123a1880-e8fc-11e8-87a8-b2b63b9a7a2b.jpg)


个别页面说明：
1. 录课老师与私塾老师：
- 录课老师，私塾老师都全部显示，无需“更多”
- 可统一调用系统中现有的方图，如下图UI，一行2个即可。
- 单个老师介绍文字不超过4行，超过部分省略号，点击老师图片和介绍文字都可以跳转到具体老师的介绍页面。
![wechatimg301](https://user-images.githubusercontent.com/33111306/48542576-7c51be00-e8fa-11e8-8446-783fdde8a7ae.jpeg)

2. 口碑好评：
-一行2个，所有好评都放，无需“更多”

**Comment by zhuyichun** [comment]
- [ ] 1.分级阅读返回的分类缺失排序
