### ISSUE TITLE
IPTV视频合成问题

### ISSUE THREAD

**Issue by Willingkong** [bstcine/cine-tasklist#466]
之前我们提交的TS格式视频，上传到IPTV后台后，在播放的时候会在片头出现30-60S的黑屏。
电视台方面认为是我们的片源合成问题，并且重新提供了更为详细的视频参数，如下图：
![wechatimg51](https://user-images.githubusercontent.com/33111306/46651286-17f06000-cbd2-11e8-9ec7-c6adaeb9d88b.jpeg)

**Comment by AaronLiDangkun** [comment]
根据需求视频，初步合成ts样本
  1. 等级 baselin3.0 及 high5.1
  2. 视频编码器libx264，编码格式 H.264 ，视频取样帧率25fps，取样码率取决于图片质量（无法取到3800k）
  2. 音频编码器mp2/ac3两种，音频取样48khz, 标准取样码率128k
