### ISSUE TITLE
iOS-iPhone：V-2.4.3 小补丁版本

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#470]
### Must fix
- [x] 1.1 有一个用户在IOSapp上点击核心词汇功能，点不开，并且一点就一直快速闪屏。而且视频课程经常打不开，特别是在4G的情况下经常打不开。[视频查看](http://static.bstcine.com/2018/12/12/151330853Sf1gGsN.mp4)
```
用户苹果手机型号：7+；
iOS系统版本：ios 11.2.1 ；
APP版本：2018年12月12号前的最新版本。
详细情况可见用户录制的视频。-Jenny 


status: 访问全部使用https协议，可能已经解决了
```
- [x] 1.2. 学习系统：课程的Lesson目录列表需求待确认   - `Alice` - `待确认` 
```
课程目录：
- 客户服务 和版本申明的格式应跟PC端一致。  
- PDF习题需要显示，点击出现弹窗，
   - 提示语为："请登录网址 www.bstcine.com 下载" ；
   - (适用于所有课程）
   -Alice
```
- [x] 1.3. 数据统计分析：APP 课件播放页面 & 首页 & 课程详情页 的 PV & UV 
```
跟踪页面：
- 商城首页
- 课程详情页 （可能统一加代码在H5页）
- 课件播放页
```
- [x] 1.4 优惠券数量显示异常 - `Eelin`- `Verified 20190103`
```
 step1：点击“我的”个人中心，显示“优惠券数量为8”
 step2：点击“优惠券”，只显示一张（异常），退出登录也还是一样。
```
- [x] 1.5 登录后点击商城 新概念2第一单元 课程→立即购买 →点击 使用优惠券立减，没有显示可用优惠券。但是在个人中心优惠券是可以看到多张未使用的 视频课程通用优惠券。-Jenny -`Verified 20190103 Eelin`

<br>
<br>

### Nice to have
- [x] 2.1 优化：支付成功页面之后，提示“扫码添加小助手微信号”，建议增加一个“去学习”的按钮，点击直接跳转到学习首页，让用户清楚购买后需要到哪里学习。- `Eelin` - `P1` -verified 20190103 Eelin
- [x] 2.2 优化：课程下载问题：正在下载的课程一退出app页面（即使是后台还在运行），下载就停止了，需要重新进入，点击暂停下载再重新开始才能继续重新下载，使用不友好。- `Eelin` - `P1-2`-verified 20190103 Eelin
- [ ] 2.3 优化：点击10000个词汇学习-任选一组-点开右上角列表式学习（未出现“显示全部”的筛选按钮），电脑上，网页版都有的，学生可以选择性背单词，针对性比较好。- `Eelin`
```
status: iPhone尚未增加此功能，此版本暂不解决
```
- [x] 2.4 点击“私塾作业”-点击“新2U2 Lesson25/Exercise PDF” - `Eelin 20181220` - `Verified 20190103 Eelin` 
```         
显示：
“请登录网址：www.bstcine.com下载对应…”（信息显示不全）

优化：
“请登录网址：www.bstcine.com - 下载对应习题”
```

<br>
<br>

### 代码规范
- [ ] 3.1. H5交互配置

**Comment by AaronLiDangkun** [comment]
- [ ] 1.数据统计分析：APP 课件播放页面 & 首页 & 课程详情页 的 PV & UV
```
跟踪页面：
- 商城首页
- 课程详情页 （可能统一加代码在H5页）
- 课件播放页
```

**Comment by joelin109** [comment]
### 1 、IOS 
- 1.3 私塾学生，老师布置了一门课程的任务学习，学生没有购买该课程，课程不能观看，但是可以做练习，逻辑 不对。-Alice - `P3`

**Comment by zhuyichun** [comment]
- [ ] 课件播放-学习打卡成功分享后自动返回播放页面，提示‘你已取消分享’

**Comment by zhuyichun** [comment]
私塾学生学习首页点击打卡跳转到微信的中间有过渡界面-bug p1

**Comment by zhuyichun** [comment]
### 下载模块
-  [x] 1、下载中进度没有，状态要么0，要么已完成，下载过程耗时久 -verified 20190104 Eelin

- [ ] 2、我的下载-下载中：这门课程已经有下载记录的点击下载其他lesson 列表显示的文件大小与这条信息明细中大小不一致 -verified 20190104 Eelin
```
step 0：lesson 1，2下载已完成
step 1：点击下载树屋1Lesson 4
step 2:进入我的下载-下载中：查看到文件：进度：有,下载速度：0.00Kb/S，文件大小：100.5M
step 3：点击列表进入明细：显示进度：0，下载速度：0.00kb/s，文件大小：24.96M
step 4:等待很久（约15分钟）没有下载完成，进度条也没有变化，很久后下载完成。中间进度不更新

技术反馈：
列表显示的文件大小的规则是Shaun定的，不改

```
- [x] 3. 当下载lesson很多时，此时执行删除操作，界面会卡顿在原地，直到删除完成后，才能继续操作 -verified 20190104 Eelin

```
reason: 删除文件是一个耗时操作，当文件数量到达一定程度时，删除文件将会消耗大量的时间
solution: 添加进度指示器，弹出一个进度条，显示删除进度，
         提供一个取消删除按钮，当用户不想继续删除时，点击取消按钮，取消继续删除
```

**Comment by zhuyichun** [comment]
### 学习
- [x] 1、学习页面打卡扫码后没有反应，需要手动点击空白地方提示打卡成功 （手机没安装微信） -verified 20190104 Jenny
-  2、安装微信后：学习页面点击学习打卡。进入微信分享页面
```
step 1:学习页面点击‘学习打卡’。进入微信分享页面：优化1：‘学习打卡’按钮点击不灵敏
step 2:点击取消分享
step 3:返回app.并弹窗。错误1：弹窗显示打卡成功
step 4:错误2：点击弹窗‘我知道了’按钮，退出学习页面直接进入目录树页面
```

- [x] 3、学习首页打卡，连续不停的点击“打卡”按钮,有较低概率出现不能调起微信的现象。 -aaron
```
reason: 连续不停的点击“打卡”按钮，造成资源重复加载，重复调用微信分享，造成未知的bug。
solution: 限制按钮的点击，点击按钮加载分享信息，此时禁用按钮点击事件。
          信息加载完毕后，准备调用微信分享接口，重新恢复按钮点击事件。
```
- [ ] 4、人类故事详情页试听全屏播放来回拖动播放会出现黑屏 -jerry
```
@daweilv 
```
- 5、学习首页-课程学习拖动播放球不能拖到起始位和结束位置 -jerry
```
step 1：播放人类故事lesson1，正常播放后拖动播放球不能拖动到0:00和最后位置
step 2:播放人类故事第一集，正常播放后拖动播放球不能拖动到13秒之前的播放位和最后位置几秒的位置
```

```
status: 
- 正常播放的情况下，拖拽不能快进到最后三秒，但是可以拖拽到起始位置，step2未重现
```
-  6、点击夏洛特的网‘’学习资料下载‘’-'Letter From EB White'节点，也没显示一串文件路劲  - jerry
```
status: 详见下文 调整lesson名称
```

**Comment by zhuyichun** [comment]
### 2018-12-28
- [ ] 1、下载的人类故事MP4类型课件，播放黑屏

**Comment by AaronLiDangkun** [comment]
## 部分lesson名称需要调整：
### reason:  
- 名称不规范，iOS APP 课件目录页会出现提示或显示异常 （详情请看问题6）
### solution: 
- 将下面列出的lesson名称按照约定的规则修改（名称要包含 `下载` or `习题` or `PDF`）
```
A0114655235938391eWYkAGPbk	Letter From EB White	《夏洛特的网》精读课程
d0115039087482962fEyZXxG9s	原文阅读材料	高考英语阅读拓展精讲 – 托福篇
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011504601110368SabQVpd8ME	201709	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201708	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201707	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201710	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201711	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201712	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011509938661571VgCQV2kadY	附录	莎士比亚戏剧欣赏
```

**Comment by joelin109** [comment]
#484
