### ISSUE TITLE
API-商城: 2级页面-在线私塾&托福SAT&分级阅读的后台配置及API

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#473]
## 2级页面的后台配置及API
- [x]  1.1 PC-后台管理: 商城后台-课程管理- 口碑好评上传维护   - `Kim`   #472
- [x]  1.2 PC-Admin: 维护流程   - `From Kim` - 'Verified'
#### step1: 添加 `ConfigSubPage` 维护配置表 [SystemConfigWebFinal](http://dev.bstcine.com/table/SystemConfigWebFinal)
```
name: "ConfigSubPage"
title: "二级页面"
```
#### step2: 配置管理菜单
```
1. 在线私塾： http://dev.bstcine.com/admin/tool/configSubPage?type=zxss
2. 托福SAT： http://dev.bstcine.com/admin/tool/configSubPage?type=tfsat
3. 分级阅读： http://dev.bstcine.com/admin/tool/configSubPage?type=fjyd
```

- [ ] 1.3 PC-Admin: 后台配置  - 'Verified'
```
2级页面：
- 配置路径：商城后台  - “2级页面” 

- "核心课程"： 课程IDs 
- “录课老师”： 老师IDs
- “口碑好评”：JSON格式（img(全路径）- update_at)
- “精彩文章”：JSON格式（cover-title-subtitle-link-type(link|none|qr))
- “资料下载”：JSON格式（title-link-visible)

- “预览”: /csub/?page=zxss|tfsat|fjyd
-  更新时间

content_subpage
(short_name)/course_ids/teacher_ids/comment/article/resource/remark
```
- [x] 1.4 提供2级页面的API：/api/content/subpage  `- Kim` - 'Verified'
```
请求参数：
page: "zxss|tfsat|fjyd"
```
- [x] 1.5 模拟真实实际的数据，确保获得3个API的数据是对的  - `Jerry` - 'Verified'
```
- 检验API是否有问题
dev环境
```

### Deadline
```
开始测试：2018-10-22
部署截止：2018-10-23


时间调整为：
- 开始测试：2018-11-13  17:00
- 部署截止：2018-11-14

Reason：口碑好评数据获取方式调整
```

2级页面 UI， #465

**Comment by joelin109** [comment]
### 测试反馈
- [x] 1. 核心课程: 已选的线上课程, 如果下架或没有PC显示权限的课程将不显示在UI - `Joe` - 'Verified'
- [x] 2. 录课老师: 需要teacher_id, 私塾简介， 老师状态，是否私塾信息 - `Joe` - 'Verified'
- [x] 3. 在线私塾老师获取的不是私塾老师简介 - ‘jerry’- 'Verified'
```
测试反馈：返回的是善恩名师信息
```
- [x] 4.托福sat老师获取不齐全（杨挚（James））没有看到- 'Verified'
- [x] 5. API-商城: 2级页面-分级阅读  - 'Joe' - `P1-- 'Verified'
```
没有拿到正确的核心课程信息
测试反馈：
测试没有通过，返回的数据没有排序
开发反馈：
已做排序
```
- [x] 6. 口碑好评: 图片路径需要是全路径（因为有的图片在Server，相对路径无法做识别）- 'Joe'- 'Verified'
```- 'Verified'
     {
        "img": "*****/2018/09/13/094350745S2ks5ej.jpg",
        "update_at": "2018-09-13 09:43:50"
      }

测试反馈：
路劲前缀没有 仅在编辑页面查看到/f/****

测试反馈：2018-11-19
API还回的格式不是{img(全路径）- update_at}
```
- [x] 7. PC-Admin: 2级页面- 维护页面添加“口碑好评”模块的备注 - `p3` - 'Joe'
```
在线私塾页面：
口碑好评:  数据来源于“口碑图片管理” 的 “在线私塾”类型

其它页面类似
测试反馈：还没有添加
```
- [ ] 8. PC-Admin: 口碑好评上传维护         - `p3` - 'Joe'
```
针对图片需要显示如下信息：
- 显示真实路径
- 图片大小
- 图片所属口碑分类

开发反馈
图片大小 - 暂不支持
```
- [x] 8. PC-Admin:  预览-打开新页面
https://dev.bstcine.com/csub/zxss
https://dev.bstcine.com/csub/tfsat
https://dev.bstcine.com/csub/fjyd

**Comment by zhuyichun** [comment]
#### 二级页面口碑好评获取
分级阅读->文学阅读好评
托福/sat->托福好评+SAT好评
在线私塾->私塾好评（待上架）
