### ISSUE TITLE
Realese-v2.5.0: 测试发现新问题的反馈列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#479]
## P0           - `紧急需立刻解决`
- [x] 01.  学习系统: Lesson播放页-记录用户在每个课程上的实际学习时间异常  - `Kim`
```
Android: 
- 1个lesson只记录一条数据，时长正确 (没有问题，不需解决）

iOS：
- Lesson的每个Media记录有两条或者3条数据
  - 第一条：记录开始时间(创建时间)，没有播放时长 （偶尔有相同的重复数据）
  - 第二条：记录结束时间(创建时间)，tag的播放时长

问题：是否只应该有一条记录

PC：
- Lesson 或 Media 没有播放时长
```
```
iOS通过修改对应api只记录一条，PC已更新
```

<br>
<br>

## P1           - `Must fix`
- [x] 1.1  H5: 添加PV& UV 统计数据 - 2018-11-28 - `David`
```
Status：已解决， 待Verify
```
- [x] 1.2. 登录与注册:  同一账号可以在多端设备登录&学习  - `David`
```
描述：用admin_eelin的账号陆续登录PC，IOS/Andriod APP，都能正常学习，且不被强制退出。
要求：不允许同一账号多端同时登录。
- 20190117 by Eelin

Reason: 
-  ？

Solution:
- ？
```
- [ ] 1.3. PC-OSS: 非课件的Media资源迁移遗留问题   (更多细节看 #326）- `David`
```
遗留未迁移:
- 1.2.1. t_sharelog 字段 remark 
- 1.2.2. t_emaillog 字段 body


t_sharelog:  2018-11-01 以后的数据更新一下 @kim
```

- [ ] 1.4. PC-Admin: 私塾管理-师生对应关系的列表显示  - `Kim`
```
学生ID：显示昵称+ID
比如：苑冰 Betty(A011455875394561ZQg0eKkLV9)
```

<br>
<br>

## P2           - `Nice to have`
- [ ] 2.1.  从wechat点链接后分享链接进去购买，登录以后不能直接选择哪张优惠券抵扣，需要输入优惠券券码，而且输入券码或者对应积分，会一直出现“www.bstcine.com 系统异常”的提示，无法正常使用优惠券和积分；--Eelin/Alice
```
系统异常原因:
- 为 no_login，原因为在微信内登录后，因为看不到优惠券，
在APP上又登录了一次查看优惠券码，导致微信内的账号被登出，
API在验证优惠券和积分的时候提示 no_login。程序合理，流程可讨论优化。
       -- David
```
- [x] 2.2.  用户数据:  更新用户所属学校的信息- `Jerry`
```
目前情况：
- 账号‘jy’ & ‘jiyang’ & ‘lf'开头 的用户已经设置了所属学校
- 宜兴外国语 & 平和高中 的用户还没设置

Solution: ?
```
- [ ] 2.3 PC: UI显示错误。 -20181205 Eelyn
[_20181205100305](https://user-images.githubusercontent.com/44994178/49485618-8c641a00-f876-11e8-805b-8a6f2e54a88b.jpg)
- [ ] 2.4 PC-Admin: 课程管理-课件制作：限制chapter级别补录不能上传课件

**Comment by joelin109** [comment]
## 已解决 in www
- [x] 1.2.  图片配置:  私塾老师的分享头像 都设置为OSS(https)- `David`
```
测试反馈：
- 私塾老师头像分享获取不到OSS图片
- ios:预览和分享都获取不到OSS图片
- Android：预览有图片，分享获取不到oss图片


Solution:
CDN中选择其中一个域名 static.bstcine.com--> 缓存配置 --> HTTP头，设置

| 参数 | 取值 |
| ---  | --- |
| Access-Control-Allow-Origin | * |
| Access-Control-Allow-Headers | Content-Type, Content-Length, Authorization, Accept, X-Requested-With |
| Access-Control-Allow-Methods | PUT, POST, GET, DELETE, OPTIONS |

```


<br>
<br>
<br>

## 学生全部作业
#### 学生查看模式
![stutasksforstu](https://user-images.githubusercontent.com/23466882/42740558-b66b65fc-88db-11e8-89da-19323cd2eb6f.jpg)

**Comment by zhuyichun** [comment]
- [ ] 部分lesson名称需要调整：
#### reason:  
- 名称不规范，iOS APP 课件目录页会出现提示或显示异常 （详情请看问题6）
#### solution: 
- 将下面列出的lesson名称按照约定的规则修改（名称要包含 `下载` or `习题` or `PDF`）
```
A0114655235938391eWYkAGPbk	Letter From EB White	《夏洛特的网》精读课程
d0115039087482962fEyZXxG9s	原文阅读材料	高考英语阅读拓展精讲 – 托福篇
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011503974382830Tcne3UQckf	原文阅读材料	英美报刊双语精读
d011504601110368SabQVpd8ME	201709	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201708	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201707	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201710	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201711	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011504601110368SabQVpd8ME	201712	英美报刊阅读理解精选100篇 - 纯文字版（2017下半年）
d011509938661571VgCQV2kadY	附录	莎士比亚戏剧欣赏
```

**Comment by zhuyichun** [comment]
### 20181219
- [ ] 1、后台管理-商城后台-课程管理-课程：课件制作：课件批量上传失败、课件单个文件上传失败
