### ISSUE TITLE
Android：V-2.4.3 补丁版本

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#483]
### Must fix
- [x] 1.1 AndroidAPP-购买：新购买课程成功后，跳到学习首页，新课程没显示。 - `Kim`  -verified
```
- 需要刷新一下当前的“学习首页”，然后能看到最新购买的课程
```
- [x] 1.2 AndroidAPP-下载： 新课程购买成功后，学习首页点击新课程，然后开始下载课件。但是在“我的下载”里没显示该课程。 - `Kim` -verified
- [x]  1.3 学习系统：课件播放页-如果是已经下载的Lesson课件，没有显示”练习“  -verified
```
测试反馈：
下载后的lesson课程，在没有网络下打开，没有显示“练习”，这个没有完成。
-Jenny 2019/1/7
暂不处理没有网络的情况 - Kim 2019/1/8
```

<br>
<br>

#### 2019-01-04

**Comment by JENNY-BSTCINE** [comment]
- [x] 1.4 AndroidAPP-核心词汇：点击核心10000词汇：1001-2000第21组，点击 立即学习，然后点击返回按钮
”←善恩核心10000词汇“，没有返回到上一级 立即学习和立即测试的页面，而是直接返回到 核心10000词汇：1001-2000 的页面。这种跳级返回，感觉不太合理。-Eelin   --verified
```
顶部返回键：退出当前窗口，
底部返回键：网页后退
by：kim

测试反馈：
这个设置不太合理，希望返回键是返回到上一级页面（显示”立即学习&立即测试“）。
- 目前情况：iOS & PC- 点击返回键都是返回到”立即学习& 立即测试“页面
-Jenny 2019/1/7

已修复- Kim 2019/1/8
点击 返回上一级后，数据没有更新，需要手动下拉刷新后才更新。2019/1/8

```
-  1.5 课程里配套的下载资料和下载的习题，安卓APP上之前一直可以直接点击，然后跳到浏览器上下载了。但是现在测试网点击都打不开下载不了，不清楚是否改了需求还是怎么样？建议还是按原先那样，可以点击下载比较好。-Jenny   verified -Eelin
```
支持 pdf 文件点击跳转   

测试反馈：
pdf文件跳转后没有显示下载
-Jenny 2019/1/7 
- 看1.6
```
- [x] 1.6 学习系统：课程目录页面- 配套的下载资料和下载的习题，无法正常下载且打开 - `Joe`   verified-Jenny
```
Step1：学习首页，点击”新概念2第一单元“课程
Step2：课程目录页面，点击”Lesson 1配套习题“Lesson
Step3：点击”... 下载习题并打印， 开始练习...“链接
Step4：新窗口一直Loading... (错误异常）
- 正确的应该是：可以直接下载该pdf 文件，下载完可以直接打开 （参考线上正式APP）
```

**Comment by eelyn-huang** [comment]
1.6 词汇量测试：有些单词没有对应匹配的释义。-Eelin

**Comment by joelin109** [comment]
#484
