### ISSUE TITLE
技术部门：201901- Separation交接列表

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#484]
### iOS （Deadline：2019-01-11）
- [x] A.1. iPhoneAPP: V-2.4.3 补丁版本 -  `2019-01-10` - Aaron #470  - `Verified`
```
Status: 已发布
- 2019-01-11
```
- [x] A.2. iPadAPP: V-2.4.3 代码正常运行
### Android （Deadline：2019-01-09）
- [x] B. Android：V-2.4.3 补丁版本 - `2019-01-09` - `Kim`  #483  - `Verified`
```
Status: 已发布
- 2019-01-11
```

### 通用
- [ ] 1.1.  APP- PV & UV 的查看文档   - `Kim`     [文档路径] (https://github.com/bstcine/help/wiki/APP%E7%AB%AFPV&UV%E7%9A%84%E6%9F%A5%E7%9C%8B%E8%AF%B4%E6%98%8E%E6%96%87%E6%A1%A3)   - `Failure`
```
Android:
- 没有看到学习首页 & 个人用户首页
- 浏览页
- 学习页 （名字澄清清除指的是什么）

-- v2.5.0
- 分离首页为：学习页、商城页、我的页
- 新增登录页
- H5 页 统一记录

-- 测试步骤
- 澄清：测试时，浏览频率间隔最好不低于10s
- step1: 打开多个页面
- step2: 记录浏览次数、停留时间
- step3: 与极光后台数据作比较

by: kim
20190118

```
```
iOS
- 没有看到 iPad 的 PV & UV
- iPhone最近7天，核心页面的PV数据很低（只有Android的20%）
- 2019-01-10


反馈澄清
- 1. iPhone与iPad使用的是不同的产品，
      在“善恩英语-Phone”产品中，可以查看到iPhone的页面统计信息，
      在“善恩英语-Pad”产品中，可以查看到iPad的页面统计信息。
- 2. iPad（带PV&UV功能）是 ‘2018-12-24’上线
       iPhone（带PV&UV功能）是 ‘2019-01-11’上线.  （注：原先看到的数据：只是还没发布时的测试数据）
```
- [x] 1.2.  视频下载与合成的 说明文档  - `Aaron`     [项目Readme](https://github.com/bstcine/cine.tool)- Failure
```
cine_tools.go无法正常跑起来

该工具可以弃用 - kim
```
- [x] 1.3.  JPush & 开发者账号 快过期需要升级 - `Aaron`   -  [说明文档](https://github.com/bstcine/help/wiki/APP-Certificate-Update)  - `Verified`

<br>
<br>
<br>

## Nice to have
- 2.1. 一个H5 PWA项目Demo，https://github.com/bstcine/cine.pwa/tree/PWA-201901
- [x]  2.2. 提供一个Android项目Demo，https://github.com/bstcine/cine.kth5  - `Kim`
```
Kotlin（10%代码）+H5
```
- [x]  2.3. 提供一个iOS项目Demo，https://github.com/bstcine/cine.iosh5  - `Aaron`
```
Native 比例比 <10%
```

**Comment by joelin109** [comment]
### iOS APP-V2.4.3 发布前测试反馈：
- [ ] 3.1 IOS下载内容删除问题  -20190111  by Eelin
```
step 1：点击“删除”下载内容-出现删除进度条（和提示语“取消下载”）
step 2：点击“取消下载”-出现提示语“您已取消本次删除操作”
（问题：1. 下载内容还是被删除了；2. 既然有“取消下载”操作，那么“删除的进度条”是不是可以不用设置那么快就直接到100%，有时候都来不及点击”取消下载”）
```

**Comment by AaronLiDangkun** [comment]
####  更换 iPhone 项目证书
---
##### 一、检查证书过期时间

1.1. 登录极光开发者平台,查看产品“设置”信息
<img width="1440" alt="1" src="https://user-images.githubusercontent.com/26997820/51225259-b4ba5a80-1984-11e9-9373-c297667f9d9f.png">

1.2. 查看推送设置
<img width="1440" alt="2" src="https://user-images.githubusercontent.com/26997820/51225292-d3205600-1984-11e9-841a-e28b95737215.png">

1.3. 展开iOS，显示推送信息
<img width="1440" alt="3" src="https://user-images.githubusercontent.com/26997820/51225294-d9aecd80-1984-11e9-9b80-eec252f2fe4d.png">

1.4. 检查证书配置，查看证书有效期。如果有效期即将结束，则需要更换新的证书
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/26997820/51225298-e2070880-1984-11e9-823a-9357d69af18e.png">


### 以下，以“善恩英语-Pad”开发者推送证书为例，更换新的证书

#### 二、废弃旧的证书
```
由1.4中检查结果可知，我们需要修改的证书为：
bundleId=xxx.xxxxxxx.xxxxxxxxx，
模式为开发者
```
2.1.登录Apple开发者中心，查看证书
<img width="1410" alt="1" src="https://user-images.githubusercontent.com/26997820/51225318-082ca880-1985-11e9-8d3f-b3c9ef03090a.png">

2.2.找到目标证书
<img width="1410" alt="2" src="https://user-images.githubusercontent.com/26997820/51225328-111d7a00-1985-11e9-9c37-437f2fa863ef.png">

2.3.废弃证书
<img width="1410" alt="3" src="https://user-images.githubusercontent.com/26997820/51225336-17abf180-1985-11e9-8696-55beb91ced05.png">


#### 三、申请新的推送证书

3.1.点击创建新的证书
<img width="1410" alt="0" src="https://user-images.githubusercontent.com/26997820/51225348-285c6780-1985-11e9-9a18-dd61abe090ae.png">

3.2.选择开发者模式，沙盒推送证书，点击继续
<img width="1410" alt="1" src="https://user-images.githubusercontent.com/26997820/51225373-40cc8200-1985-11e9-9301-d559d9289adc.png">
<img width="1410" alt="2" src="https://user-images.githubusercontent.com/26997820/51225377-43c77280-1985-11e9-999c-a0ca74d3d1e4.png">

3.3.选择bundleId，与废弃证书一致（xxx.xxxxxxx.xxxxxxxxx），点击继续
<img width="1410" alt="3" src="https://user-images.githubusercontent.com/26997820/51225393-58a40600-1985-11e9-899f-b6e812e34b12.png">
<img width="1410" alt="4" src="https://user-images.githubusercontent.com/26997820/51225396-5b066000-1985-11e9-806f-322869e34ef1.png">

3.4.需要创建csr文件，详见下文——四、创建CSR文件
创建完成后点击继续
<img width="1410" alt="5" src="https://user-images.githubusercontent.com/26997820/51225419-76716b00-1985-11e9-9406-b4247fb540be.png">

3.5.选择csr文件，选择完成后，点击继续
<img width="1410" alt="9" src="https://user-images.githubusercontent.com/26997820/51225446-96a12a00-1985-11e9-9f29-d74dd9b83aab.png">
<img width="1303" alt="10" src="https://user-images.githubusercontent.com/26997820/51225450-9a34b100-1985-11e9-8621-4b6b044608c7.png">

3.6.下载证书到本地
<img width="1410" alt="11" src="https://user-images.githubusercontent.com/26997820/51225463-af114480-1985-11e9-970e-b67ec93905dd.png">

3.7.安装证书，双击下载到本地的证书，安装到钥匙串
<img width="991" alt="12" src="https://user-images.githubusercontent.com/26997820/51225476-bc2e3380-1985-11e9-8483-1dc4af9f042e.png">


#### 四、创建CSR文件
4.1.打开钥匙串，选择证书助理，从证书颁发机构请求证书
<img width="1043" alt="6" src="https://user-images.githubusercontent.com/26997820/51225502-dcf68900-1985-11e9-89d5-eaf6b96f4ab3.png">

4.2.选择存储到磁盘，点击继续
<img width="618" alt="7" src="https://user-images.githubusercontent.com/26997820/51225505-e253d380-1985-11e9-93b8-30797f564c4b.png">

4.3.选择存储位置，并命名（不能改变扩展名）
<img width="634" alt="8" src="https://user-images.githubusercontent.com/26997820/51225512-e97ae180-1985-11e9-8139-1aec659b8806.png">

4.4.保存完成后，即可供 3.5 使用
#### 五、将新证书更新到极光
```
极光推送需要的证书为个人信息交换证书（.p12）
所以，需要将安装到钥匙串的证书导出为 .p12文件
```
5.1.在钥匙串中找到安装的证书，选择导出
<img width="1241" alt="13" src="https://user-images.githubusercontent.com/26997820/51225545-0f07eb00-1986-11e9-9bd4-df180ef7a468.png">

5.2.文件格式选择“个人信息交换(.p12)”，选择存储位置，重命名后，点击“存储”
<img width="1022" alt="14" src="https://user-images.githubusercontent.com/26997820/51225548-15966280-1986-11e9-8f7e-a4a72e763bdf.png">

5.3.为导出的证书设置密码，为了项目安全，请务必设置并牢记密码
<img width="973" alt="15" src="https://user-images.githubusercontent.com/26997820/51225557-1b8c4380-1986-11e9-9cc8-ea26eb7cc950.png">

5.4.将导出的证书提交到极光推送，如1.4点击编辑
```
请务必查看，是否为废弃证书的项目，本次举例信息:
1.项目名称为善恩英语-Pad，
2.bundleId为com.bstcine.education
3.模式为开发者
```
<img width="1440" alt="4" src="https://user-images.githubusercontent.com/26997820/51225668-92c1d780-1986-11e9-8be4-f9b71154044f.png">
<img width="1440" alt="5" src="https://user-images.githubusercontent.com/26997820/51225717-cbfa4780-1986-11e9-9113-3c45194ae4c5.png">

5.5.选择导出的个人信息交换文件（.p12），点击打开
<img width="1306" alt="6" src="https://user-images.githubusercontent.com/26997820/51225688-a4a37a80-1986-11e9-90ce-bff9144971db.png">

5.6.此时即已更新完成，
如果过期时间已新证书一致，则表示更新完成，
如果更新状态为已验证，则表示证书与APNS链接成功
<img width="1440" alt="7" src="https://user-images.githubusercontent.com/26997820/51225724-d583af80-1986-11e9-99a2-41ea747a1795.png">

**Comment by AaronLiDangkun** [comment]
```
由于iOS的封闭性，开发人员在使用某些功能的时候，往往需要特定的证书，如开发APP需要开发证书，上线APP需要生产证书，推送通知需要推送证书等。
新功能在上线之前需要测试，因此，功能证书又分为开发者模式证书和生产者模式两种。如推送证书，分为Apple Push Services(生产者推送证书)和APNs Development iOS(开发者推送证书)。
所以，在开始更新证书之前，请务必了解开发者模式和生产者模式。
开发者模式：开发者在开发过程中运行和使用的包，其运行环境就是开发者模式。
生产者模式：当开发人员测试运行完毕，将包发布到APP Store或其它环境（如fir.im），供用户下载使用，其运行环境一般为生产者模式。
在使用XCode打包时，选择 APP Store 或 ad-hoc，所获得的包为生产者模式，其余为开发者模式。
```

### 1.查看证书过期时间
---

1.1. 登录Apple开发者中心
https://idmsa.apple.com/IDMSWebAuth/signin?appIdKey=891bd3417a7776362562d2197f89480a8547b108fd934911bcbea0110d07f757&path=%2Faccount%2F&rv=1
<img width="1410" alt="1" src="https://user-images.githubusercontent.com/26997820/51298705-8611b200-1a60-11e9-998f-57b34198e2aa.png">

1.2. 选择Certificates Identifiers&Profile 按钮，查看证书列表，如果有证书即将过期，则需要及时更换新的证书，以免证书过期后造成不便。如果所有证书有效期都足够，则不需要更换证书。
<img width="1410" alt="2" src="https://user-images.githubusercontent.com/26997820/51298723-932ea100-1a60-11e9-8072-96a20effec78.png">

**Comment by AaronLiDangkun** [comment]
2.1.4 创建CSR文件并继续
>  创建CSR文件，如果已经创建过CSR文件，则不需要重复创建，直接跳过这一步骤，继续制作证书。
>> 1.钥匙串访问——>证书助理——>从证书颁发机构获取
>>
>> <img width="1043" alt="csr1" src="https://user-images.githubusercontent.com/26997820/51303492-7d28dc80-1a70-11e9-83a0-1b26e1f9ec19.png">

>>
>> 2.证书选项，选择存储到磁盘
>>
>> <img width="618" alt="csr2" src="https://user-images.githubusercontent.com/26997820/51303512-929e0680-1a70-11e9-8457-dadb3a6d4f27.png">

>> 3.选择存储位置并命名，点击存储
>>
>> <img width="634" alt="csr3" src="https://user-images.githubusercontent.com/26997820/51303522-99c51480-1a70-11e9-9273-72714246517c.png">

> CSR文件创建完成，点击继续
> <img width="1410" alt="5" src="https://user-images.githubusercontent.com/26997820/51303552-b2352f00-1a70-11e9-9465-4ebe3a59c232.png">
