### ISSUE TITLE
安卓-下载：已下载课程目录显示方式

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#49]
> 1. 课程目录页面需要有“全部下载”的按钮：点击“全部下载”可自动下载当前课程的全部章节，不包括本章习题和本章单词，仅包括可播放的视频课件；“全部下载”的按钮设计为可点击效果，需由Ana设计提供UI
> 2. “已下载“、“未下载“和“下载中“的按钮需区分明显：“已下载”按钮可设计为灰色，不可点击效果，“已下载“、“未下载“和“下载中“的按钮具体由Ana设计提供UI
> 3. 有网络和无网络情况下点击课程进入课程目录的显示方式：
(1) 在有网络情况下点击课程进入课程目录-点击每个课程目录均可进入相应的课程播放界面；其中，如果是已经下载的课件，即便在有网络的情况下，依然播放本地文件而不是在线播放。
(2) 在无网络情况下点击课程进入课程目录-点击已下载的课程目录可进入相应的课程播放界面，已下载的lesson目录显示为有颜色可点击效果；点击未下载的课程不能进入相应的课程且未下载的lesson目录显示为灰色不可点击效果.

两种情况下课程目录的显示效果需由Ana设计提供UI，包括未下载lesson目录，已下载lesson目录，“全部下载”的按钮，“已下载“、“未下载“和“下载中“的按钮。
交互图点击链接 https://modao.cc/app/au9gGK7AoKHgjMPb9COmVUbGeAlI171 进行查看
逻辑流程图：
![default](https://user-images.githubusercontent.com/32290407/31481445-e903bed4-af55-11e7-9792-f4cb84ddaaab.png)

**Comment by YangKaiqiCine** [comment]
添加流程逻辑图

**Comment by YangKaiqiCine** [comment]
确认

**Comment by Anawangqi** [comment]
切图和标注：[ftp://192.168.1.134/www/bstcine/android/couselist](url)
UI：
## **1. 无网络**
![- 1-2](https://user-images.githubusercontent.com/32318334/31645115-d99d637e-b2bf-11e7-9942-a201d8f94afc.png)
## **2.有网络**
![- 1-3](https://user-images.githubusercontent.com/32318334/31645116-d9db02ec-b2bf-11e7-8f6e-fb1e2925050a.png)
## **3.全部下载**
![- 1-](https://user-images.githubusercontent.com/32318334/31645118-da0d853c-b2bf-11e7-85de-778970c3e69f.png)

**Comment by itwangxiang** [comment]
1. 目录离线缓存
2. 目录 UI 调整

> deadline 2017-11-02

**Comment by itwangxiang** [comment]
1. 播放时长需要 API 提供
2. 播放进度需要 API 提供

**Comment by joelin109** [comment]
对于每个Lesson，播放进度（时间）先不用提供

**Comment by YangKaiqiCine** [comment]
小宋，更新后的最新安卓版本是否已经测试过？
请把新版本APP的下载地址再发我一下。 
 
------------------ Original ------------------

**Comment by MaryLinker** [comment]
出现的bug：
1.第一次打开课程目录后，在后台对该课程的目录进行更改，再次打开该课程目录，此时，课程目录并没有改变，在手机软件设置中清除APP缓存后，可看见课程目录发生更新

**Comment by YangKaiqiCine** [comment]
这个准备怎么处理？
 
 
------------------ Original ------------------

**Comment by itwangxiang** [comment]
@YangKaiqiCine 这个优化网络请求的一种机制，不算BUG；
APP 打开时获取的课程目录数据会缓存在内存里，缓存的有效期：app 进程被杀掉前。

**Comment by itwangxiang** [comment]
UI，进度微调
