### ISSUE TITLE
PC-背单词：单词功能支持多种词库

### ISSUE THREAD

**Issue by daweilv** [bstcine/cine-tasklist#495]
### 需求描述：
1. 词库分为1、2级：
```
|---- SAT
|    |---- SAT 1-100
|    |---- SAT 101-200
|    |---- SAT 201-300
|---- TPO
|    |---- TPO 1-60
|    |---- TPO 61-200
|    |---- TPO 201-260
|---- 核心10000
|    |---- 核心10000
|---- 动物农庄
|    |---- Chapter 1 
|    |---- Chapter 2
|    |---- Chapter 3
```
```
2级分类中的单词，数量不固定，具体放置多少个单词由业务方灵活处理。

1w词汇无需处理二级分类，特殊处理。
```

示意图：
![image](https://user-images.githubusercontent.com/7405300/56858301-543ab080-69aa-11e9-86b5-a2cdca529745.png)

2. excel 单词导入功能
```
excel字段命名规则为：课程名、一级目录名
根据该规则自动替换掉原有‘本章单词’
```

### 功能入口：
<del>1. web&app 首页banner</del>
<del>2. web 学习首页核心词汇旁边</del>
3. web 学习播放页目录，点击’本章单词‘跳转到新的单词系统

**Comment by daweilv** [comment]
### 现阶段4个功能细节：
1. 词汇量测试
表：cotent_vocab 
字段：source_type=0
一个正确释义+预设的3个混淆项

2. 背单词起点评估
表：cotent_vocab
字段：source_type=1
一个正确释义+预设的3个混淆项
所有词汇来自都来自3

3. 10000词汇背单词
表：content_dictionary
一个正确释义+当前单词小组内3个同词性混淆项
```
现阶段存在背少量单词的时候，混淆项重复出现的问题，忽略
```

4. 背单词任务
表：content_dictionary
一个正确释义+当前单词小组内3个同词性混淆项
即背10000词汇的第 i 个单词到第 j 个单词

**Comment by daweilv** [comment]
### Q&A
1. 其他词库是否需要【背单词起点评估】？
```
不需要
```
![image](https://user-images.githubusercontent.com/7405300/56856968-2b5def80-6999-11e9-80d2-017a923860d4.png)

2. 其他词库的【背单词起点评估】是否与1w词汇相同？
    如相同，“建议从第N个单词开始学习”映射关系是怎样的
    如不同，每次添加词汇都会增加额外数据维护工作。
```
忽略
```

3. 用户在背单词的时候只能背2级分类下的单词，不可背1级分类？
```
是
```

**Comment by daweilv** [comment]
需要测的两个点：
1. 原有课程的本章单词节点是否跳转到新的背单词系统，整个背单词学习、测试过程是否正常

2. 后台课程维护新增了导入课程单词的入口，测试各种情况下的导入是否正常，导入后是否每个单词都抓取到了发音，整个背单词学习、测试过程是否正常
https://dev.bstcine.com/admin/tool/lessonEditor?id=xxxxxxxxxx

测试反馈（20190529）-Jenny：
- [x] 1. 点击“立即学习”→“已认识”打勾后，在列表式页面没有打勾，且“立即学习”记录的词汇没有减少。
- [x] 2. 点击“列表式”页面，点击“显示全部”按钮后，页面没有任何变化。理论上点击“显示全部”会显示全部单词，如果点击不显示，则页面只显示没有学习的单词。
- [x] 3. 点击“立即测试”，很多单词只显示3个选项，其中有一个选项是空白。例如《疯狂学校1》chapter 1的“the big moment"一词。
- [x] 4. 所有词组的全角‘ 替换为半角'
- [x] 5. 优化windows系统下单词的字体样式
```
请大家看下win下的样式
```
- [x] 6. 有些课程里的章节本章单词量过大，需要优化。例如查理课程chapter 1，就有400多个需要学习的单词。
```
单词测试50个单词为上限
```
- [x] 7. ”列表式“页面，每个单词前的序号显示不友好。
```
去掉
```
- [x] 8. 点击“立即测试”，部分单词的干扰项不友好，例如神奇树屋1的chapter 1的“charge”，出现了两个“猛冲”选项。还有小王子的chapter 1，“ a great deal" 出现的两个选项分别为”许许多多“和”许多“。
```
问题原因为该分类下有a great many“许许多多”和a great deal“许多”，
干扰项在随机的时候有一定概率抽到这两个，造成该问题。
solution:
干扰项在抽取同类型单词/词组的时候排除相似项，如果不够3个的时候忽略类型，本类型单词随机抽取
```
- [x] 9. 有些课程，点击”本章单词“→”chapter 1“，跳到各组单词的显示页面，有些chapter名字长的课程，显示不友好。如果查理和巧克力工厂。
```
目前采用超过该区域的时候自动截断的方式显示，
待alice整理好课程的shortname后使用shortname
```

**Comment by JENNY-BSTCINE** [comment]
- [x] 后台上传本章单词，当单词表Excel第一次导入系统后，在Excel里删除两个单词后重新上传，被删除的两个单词在学习系统的背单词模块里仍然存在。
