### ISSUE TITLE
Android：学习过程打卡分享需求变更 

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#5]

**Comment by MaryLinker** [comment]
学习一个lesson结束后弹出打卡提示框，点击“继续学习下一课”按钮自动跳转至下一个lesson的播放界面；点击“结束本次学习，打卡”按钮跳转至朋友圈分享页面，点击“发表”成功后返回APP并显示打卡成功弹窗，点击“我知道了”按钮后结束本次学习，回到课程目录页面。
交互图点击链接https://modao.cc/app/1e194398bfad04bb9e17cc11a331415a9ef4adbc 进行查看

**Comment by itwangxiang** [comment]
已经完成
[http://fir.im/bstc](url)
