### ISSUE TITLE
PC-学习系统: 学习界面-刷新浏览器后播放音频错误

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#52]
### web-网站：学习界面刷新浏览器播放音频错误
如：当前播放该lesson除第一个音频段落外的时候刷新页面，出现视频画面和音频段落仍然是刷新前页面，但播放的音频概率性播放当前lesson第一段音频。

**Comment by joelin109** [comment]
Bug步骤， 怎么重现？
