### ISSUE TITLE
PC-后台管理：暨阳中学学习账号删除和添加及开通对应课程

### ISSUE THREAD

**Issue by zhuyichun** [bstcine/cine-tasklist#55]
# 暨阳中学学习账号删除和添加及开通对应课程
1.暨阳中学原有150个账号麻烦删除，并关闭账号内课程。
2.新课开通：微信上转了暨阳高一，高二的名单给你，烦请建立账号并开通课程。高一开查理和巧克力工厂，高二开动物农庄。
3.学习账号调整：两个文件里现在用的是学生考号，烦请在高一年级考号前统一添加：JY20，在高二年级四位学号前统一加：JY19；以作区分。

**Comment by joelin109** [comment]
Solution：
Step 1：现在测试数据库里面操作，自己校验
Step 2：Jerry后台数据检查一下
Step 3：提供一个SQL， Joe 检验
Step 4：在正式数据库里面执行

**Comment by joelin109** [comment]
- 待删除的150个账号：
```
jiyang001-jiyang150
```

**Comment by itwangxiang** [comment]
-  查询 jiyang 1-150 的用户
``` sql
select LENGTH(s.login) as length,s.* 
from t_user s 
where s.login like 'jiyang%' and LENGTH(s.login) > 6 and LENGTH(s.login) <= 9 
and CONVERT(REPLACE(s.login,'jiyang',''),SIGNED) > 0 and CONVERT(REPLACE(s.login,'jiyang',''),SIGNED) <= 150
order by length,s.login;
```
-  删除 jiyang 1-150 的用户
``` sql
update t_user
set delete_at = NOW(),delete_by = 'sql'
where login like 'jiyang%' and LENGTH(login) > 6 and LENGTH(login) <= 9 
and CONVERT(REPLACE(login,'jiyang',''),SIGNED) > 0 and CONVERT(REPLACE(login,'jiyang',''),SIGNED) <= 150;
``` 
-  撤销删除 jiyang 1-150 的用户
``` sql
update t_user
set delete_at = null,delete_by = null
where login like 'jiyang%' and LENGTH(login) > 6 and LENGTH(login) <= 9 
and CONVERT(REPLACE(login,'jiyang',''),SIGNED) > 0 and CONVERT(REPLACE(login,'jiyang',''),SIGNED) <= 150;
```

**Comment by itwangxiang** [comment]
-  高一新增用户
`JY200101,JY200102,JY200103,JY200104,JY200105,JY200106,JY200107,JY200108,JY200109,JY200111,JY200112,JY200113,JY200114,JY200115,JY200116,JY200117,JY200118,JY200119,JY200120,JY200121,JY200122,JY200123,JY200124,JY200125,JY200126,JY200127,JY200128,JY200129,JY200130,JY200131,JY200132,JY200133,JY200134,JY200135,JY200136,JY200137,JY200138,JY200139,JY200140,JY200141,JY200142,JY200143,JY200144,JY200145,JY200146,JY200147,JY200148,JY200201,JY200202,JY200203,JY200204,JY200205,JY200206,JY200207,JY200208,JY200209,JY200210,JY200211,JY200212,JY200213,JY200214,JY200215,JY200216,JY200217,JY200218,JY200219,JY200220,JY200221,JY200222,JY200223,JY200224,JY200225,JY200226,JY200227,JY200228,JY200229,JY200230,JY200231,JY200232,JY200233,JY200234,JY200235,JY200236,JY200237,JY200238,JY200239,JY200240,JY200241,JY200242,JY200243,JY200244,JY200245,JY200246,JY200247,JY200248,JY200301,JY200302,JY200303,JY200304,JY200305,JY200306,JY200307,JY200308,JY200309,JY200310,JY200311,JY200312,JY200313,JY200314,JY200315,JY200316,JY200317,JY200318,JY200319,JY200320,JY200321,JY200322,JY200323,JY200324,JY200325,JY200326,JY200327,JY200328,JY200329,JY200330,JY200331,JY200332,JY200333,JY200334,JY200335,JY200336,JY200337,JY200338,JY200339,JY200340,JY200341,JY200342,JY200343,JY200344,JY200345,JY200346,JY200347,JY200348,JY200349,JY200401,JY200402,JY200403,JY200404,JY200405,JY200406,JY200407,JY200408,JY200409,JY200410,JY200411,JY200412,JY200413,JY200414,JY200415,JY200416,JY200417,JY200418,JY200419,JY200420,JY200421,JY200422,JY200423,JY200424,JY200425,JY200426,JY200427,JY200428,JY200429,JY200430,JY200431,JY200432,JY200433,JY200434,JY200435,JY200436,JY200437,JY200438,JY200439,JY200440,JY200441,JY200442,JY200443,JY200444,JY200445,JY200446,JY200447,JY200448,JY200449,JY200501,JY200502,JY200503,JY200504,JY200505,JY200506,JY200507,JY200508,JY200509,JY200510,JY200511,JY200512,JY200513,JY200514,JY200515,JY200516,JY200517,JY200518,JY200519,JY200520,JY200521,JY200522,JY200523,JY200524,JY200525,JY200526,JY200527,JY200528,JY200529,JY200530,JY200531,JY200532,JY200533,JY200534,JY200535,JY200536,JY200537,JY200538,JY200539,JY200540,JY200541,JY200542,JY200543,JY200544,JY200545,JY200546,JY200547,JY200548,JY200601,JY200602,JY200603,JY200604,JY200605,JY200606,JY200607,JY200608,JY200609,JY200610,JY200611,JY200612,JY200613,JY200614,JY200615,JY200616,JY200617,JY200618,JY200619,JY200620,JY200621,JY200622,JY200623,JY200624,JY200625,JY200626,JY200627,JY200628,JY200629,JY200630,JY200631,JY200632,JY200633,JY200634,JY200635,JY200636,JY200637,JY200638,JY200639,JY200640,JY200641,JY200642,JY200643,JY200644,JY200645,JY200646,JY200647,JY200648,JY200649,JY200701,JY200702,JY200703,JY200704,JY200705,JY200706,JY200707,JY200708,JY200709,JY200710,JY200711,JY200712,JY200713,JY200714,JY200715,JY200716,JY200717,JY200718,JY200719,JY200720,JY200721,JY200722,JY200723,JY200724,JY200725,JY200726,JY200727,JY200728,JY200729,JY200730,JY200731,JY200732,JY200733,JY200734,JY200735,JY200736,JY200737,JY200738,JY200739,JY200740,JY200741,JY200742,JY200743,JY200744,JY200745,JY200746,JY200747,JY200748,JY200801,JY200802,JY200803,JY200804,JY200805,JY200806,JY200807,JY200808,JY200809,JY200810,JY200811,JY200812,JY200813,JY200814,JY200815,JY200816,JY200817,JY200818,JY200819,JY200820,JY200821,JY200822,JY200823,JY200824,JY200825,JY200826,JY200827,JY200828,JY200829,JY200830,JY200831,JY200832,JY200833,JY200834,JY200835,JY200836,JY200837,JY200838,JY200839,JY200840,JY200841,JY200842,JY200843,JY200844,JY200845,JY200846,JY200847,JY200848,JY200901,JY200902,JY200903,JY200904,JY200905,JY200906,JY200907,JY200908,JY200909,JY200910,JY200911,JY200912,JY200913,JY200914,JY200915,JY200916,JY200917,JY200918,JY200919,JY200920,JY200921,JY200922,JY200923,JY200924,JY200925,JY200926,JY200927,JY200928,JY200929,JY200930,JY200931,JY200932,JY200933,JY200934,JY200935,JY200936,JY200937,JY200938,JY200939,JY200940,JY200941,JY200942,JY200943,JY200944,JY200945,JY200946,JY200947,JY200948,JY201001,JY201002,JY201003,JY201004,JY201005,JY201006,JY201007,JY201008,JY201009,JY201010,JY201011,JY201012,JY201013,JY201014,JY201015,JY201016,JY201017,JY201018,JY201019,JY201020,JY201021,JY201022,JY201023,JY201024,JY201025,JY201026,JY201027,JY201028,JY201029,JY201030,JY201031,JY201032,JY201033,JY201034,JY201035,JY201036,JY201037,JY201038,JY201039,JY201040,JY201041,JY201042,JY201043,JY201044,JY201045,JY201046,JY201047,JY201048,JY201101,JY201102,JY201103,JY201104,JY201105,JY201106,JY201107,JY201108,JY201109,JY201110,JY201111,JY201112,JY201113,JY201114,JY201115,JY201116,JY201117,JY201118,JY201119,JY201120,JY201121,JY201122,JY201123,JY201124,JY201125,JY201126,JY201127,JY201128,JY201129,JY201130,JY201131,JY201132,JY201133,JY201134,JY201135,JY201136,JY201137,JY201138,JY201139,JY201140,JY201141,JY201142,JY201143,JY201144,JY201145,JY201146,JY201147,JY201148,JY201149,JY201201,JY201202,JY201203,JY201204,JY201205,JY201206,JY201207,JY201208,JY201209,JY201210,JY201211,JY201212,JY201213,JY201214,JY201215,JY201216,JY201217,JY201218,JY201219,JY201220,JY201221,JY201222,JY201223,JY201224,JY201225,JY201226,JY201227,JY201228,JY201229,JY201230,JY201231,JY201232,JY201233,JY201234,JY201235,JY201236,JY201237,JY201238,JY201239,JY201240,JY201241,JY201242,JY201243,JY201244,JY201245,JY201246,JY201247,JY201248,JY201249`

**Comment by itwangxiang** [comment]
- 高二新增用户
`JY190101,JY190102,JY190103,JY190104,JY190105,JY190106,JY190107,JY190108,JY190109,JY190110,JY190111,JY190112,JY190113,JY190114,JY190115,JY190116,JY190117,JY190118,JY190119,JY190120,JY190121,JY190122,JY190123,JY190124,JY190125,JY190126,JY190127,JY190128,JY190129,JY190130,JY190131,JY190132,JY190133,JY190134,JY190135,JY190136,JY190137,JY190138,JY190139,JY190140,JY190141,JY190142,JY190201,JY190202,JY190203,JY190204,JY190205,JY190206,JY190207,JY190208,JY190209,JY190210,JY190211,JY190212,JY190213,JY190214,JY190215,JY190216,JY190217,JY190218,JY190219,JY190220,JY190221,JY190222,JY190223,JY190224,JY190225,JY190226,JY190227,JY190228,JY190229,JY190230,JY190231,JY190232,JY190233,JY190234,JY190235,JY190236,JY190237,JY190238,JY190239,JY190240,JY190241,JY190301,JY190302,JY190303,JY190304,JY190305,JY190306,JY190307,JY190308,JY190309,JY190310,JY190311,JY190312,JY190313,JY190314,JY190315,JY190316,JY190317,JY190318,JY190319,JY190320,JY190321,JY190322,JY190323,JY190324,JY190325,JY190326,JY190327,JY190328,JY190329,JY190330,JY190331,JY190332,JY190333,JY190334,JY190335,JY190336,JY190337,JY190338,JY190339,JY190340,JY190341,JY190401,JY190402,JY190403,JY190404,JY190405,JY190406,JY190407,JY190408,JY190409,JY190410,JY190411,JY190412,JY190413,JY190414,JY190415,JY190416,JY190417,JY190418,JY190419,JY190420,JY190421,JY190422,JY190423,JY190424,JY190425,JY190426,JY190427,JY190428,JY190429,JY190430,JY190431,JY190432,JY190433,JY190434,JY190435,JY190436,JY190437,JY190438,JY190439,JY190440,JY190441,JY190442,JY190443,JY190444,JY190445,JY190446,JY190447,JY190448,JY190449,JY190450,JY190501,JY190502,JY190503,JY190504,JY190505,JY190506,JY190507,JY190508,JY190509,JY190510,JY190511,JY190512,JY190513,JY190514,JY190515,JY190516,JY190517,JY190518,JY190519,JY190520,JY190521,JY190522,JY190523,JY190524,JY190525,JY190526,JY190527,JY190528,JY190529,JY190530,JY190531,JY190532,JY190533,JY190534,JY190535,JY190536,JY190537,JY190538,JY190539,JY190540,JY190541,JY190542,JY190543,JY190544,JY190545,JY190546,JY190547,JY190548,JY190601,JY190602,JY190603,JY190604,JY190605,JY190606,JY190607,JY190608,JY190609,JY190610,JY190611,JY190612,JY190613,JY190614,JY190615,JY190616,JY190617,JY190618,JY190619,JY190620,JY190621,JY190622,JY190623,JY190624,JY190625,JY190626,JY190627,JY190628,JY190629,JY190630,JY190631,JY190632,JY190633,JY190634,JY190635,JY190636,JY190637,JY190638,JY190639,JY190640,JY190641,JY190642,JY190643,JY190644,JY190645,JY190646,JY190647,JY190648,JY190701,JY190702,JY190703,JY190704,JY190705,JY190706,JY190707,JY190708,JY190709,JY190710,JY190711,JY190712,JY190713,JY190714,JY190715,JY190716,JY190717,JY190718,JY190719,JY190720,JY190721,JY190722,JY190723,JY190724,JY190725,JY190726,JY190727,JY190728,JY190729,JY190730,JY190731,JY190732,JY190733,JY190734,JY190735,JY190736,JY190737,JY190738,JY190739,JY190740,JY190741,JY190742,JY190743,JY190744,JY190801,JY190802,JY190803,JY190804,JY190805,JY190806,JY190807,JY190808,JY190809,JY190810,JY190811,JY190812,JY190813,JY190814,JY190815,JY190816,JY190817,JY190818,JY190819,JY190820,JY190821,JY190822,JY190823,JY190824,JY190825,JY190826,JY190827,JY190828,JY190829,JY190830,JY190831,JY190832,JY190833,JY190834,JY190835,JY190836,JY190837,JY190838,JY190839,JY190840,JY190841,JY190842,JY190843,JY190844,JY190845,JY190846,JY190847,JY190848,JY190849,JY190850,JY190851,JY190852,JY190901,JY190902,JY190903,JY190904,JY190905,JY190906,JY190907,JY190908,JY190909,JY190910,JY190911,JY190912,JY190913,JY190914,JY190915,JY190916,JY190917,JY190918,JY190919,JY190920,JY190921,JY190922,JY190923,JY190924,JY190925,JY190926,JY190927,JY190928,JY190929,JY190930,JY190931,JY190932,JY190933,JY190934,JY190935,JY190936,JY190937,JY190938,JY190939,JY190940,JY190941,JY190942,JY190943,JY190944,JY190945,JY190946,JY190947,JY190948,JY190949,JY190950,JY190951,JY190952,JY191001,JY191002,JY191003,JY191004,JY191005,JY191006,JY191007,JY191008,JY191009,JY191010,JY191011,JY191012,JY191013,JY191014,JY191015,JY191016,JY191017,JY191018,JY191019,JY191020,JY191021,JY191022,JY191023,JY191024,JY191025,JY191026,JY191027,JY191028,JY191029,JY191030,JY191031,JY191032,JY191033,JY191034,JY191035,JY191036,JY191037,JY191038,JY191039,JY191040,JY191041,JY191042,JY191043,JY191044,JY191045,JY191046,JY191047,JY191048,JY191049,JY191050,JY191051,JY191052,JY191101,JY191102,JY191103,JY191104,JY191105,JY191106,JY191107,JY191108,JY191109,JY191110,JY191111,JY191112,JY191113,JY191114,JY191115,JY191116,JY191117,JY191118,JY191119,JY191120,JY191121,JY191122,JY191123,JY191124,JY191125,JY191126,JY191127,JY191128,JY191129,JY191130,JY191131,JY191132,JY191133,JY191134,JY191135,JY191136,JY191137,JY191138,JY191139,JY191140,JY191141,JY191142,JY191143,JY191144,JY191145,JY191146,JY191147,JY191148,JY191149,JY191150,JY191151,JY191152,JY191201,JY191202,JY191203,JY191204,JY191205,JY191206,JY191207,JY191208,JY191209,JY191210,JY191211,JY191212,JY191213,JY191214,JY191215,JY191216,JY191217,JY191218,JY191219,JY191220,JY191221,JY191222,JY191223,JY191224,JY191225,JY191226,JY191227,JY191228,JY191229,JY191230,JY191231,JY191232,JY191233,JY191234,JY191235,JY191236,JY191237,JY191238,JY191239,JY191240,JY191241,JY191242,JY191243,JY191244,JY191245,JY191246,JY191247,JY191248,JY191249,JY191250,JY191251,JY191252`

**Comment by itwangxiang** [comment]
- 批量开通课程
使用新增用户操作

**Comment by itwangxiang** [comment]
@joelin109 @zhuyichun 
> 新增用户并开通课程 -- 测试服务器上，已经校验成功

**Comment by joelin109** [comment]
Where  is the sql file?

**Comment by joelin109** [comment]
## Solution：
- 新建立账号
```
Step 1：提供新建立账号列表
Step 2：Jerry整理数据
Step 3：Jerry后台批量添加
```

- 删除账号
```
Step 1：提供一个删除账号的SQL file
Step 2：在测试数据库里面执行，然后查看结果、检验
Step 3：在正式数据库里面执行
```

**Comment by itwangxiang** [comment]
> 暨阳中学
-  删除用户
[暨阳中学删除用户jiyang01~150.zip](https://github.com/bstcine/cine-tasklist/files/1378721/jiyang01.150.zip)
- 添加用户
  - 高一用户
[2017-2018高一名单英语原著.zip](https://github.com/bstcine/cine-tasklist/files/1378726/2017-2018.zip)
  - 高二用户
[2017-2018学年高二分班名单英语原著.zip](https://github.com/bstcine/cine-tasklist/files/1378768/2017-2018.zip)
- 批量开通
  - 开通查理和巧克力工厂的用户名单
[2017-2018高一名单英语原著.txt](https://github.com/bstcine/cine-tasklist/files/1378809/2017-2018.txt)
  - 开通动物农庄的用户名单
[2017-2018学年高二分班名单英语原著.txt](https://github.com/bstcine/cine-tasklist/files/1378811/2017-2018.txt)

**Comment by zhuyichun** [comment]
> 暨阳中学昵称默认显示姓名
- 高二
update t_user set nickname=CONCAT(surname,name)   where   login like 'JY19%'   and nickname in ('',null)
- 高一
update t_user set nickname=CONCAT(surname,name)   where   login like 'JY20%'   and nickname in ('',null)
