### ISSUE TITLE
iOS-学习系统：课程播放界面的缓冲图更改

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#56]
1、这个APP的数据调入时的等待背景，“波士顿善恩教育”--->“善恩英语”，英文原著精读引领者--->“在线英语阅读课程专家”
2、所有涉及“Leading Provider of Online Reading Courses”的地方，都修改成“The Premier Online Reading Courses”
![image](https://user-images.githubusercontent.com/32290407/31475818-88d9cbb8-af35-11e7-8785-cf31bde9c742.png)

**Comment by Anawangqi** [comment]
UI修改：
![06 - 3](https://user-images.githubusercontent.com/32318334/31483939-fb649ac4-aef3-11e7-91c4-fc2bc14218c6.png)
![06 - 1](https://user-images.githubusercontent.com/32318334/31483925-f4ee690e-aef3-11e7-9ef2-450854edfc17.png)
![06 - 2](https://user-images.githubusercontent.com/32318334/31483926-f682e83a-aef3-11e7-8289-c825912b5d71.png)

**Comment by Anawangqi** [comment]
切图和标注：
Android: ftp://192.168.1.134/www/bstcine/android/videoloading
ios: ftp://192.168.1.134/www/bstcine/ios/videoloading
UI：
加载中：
![06 - 1-1](https://user-images.githubusercontent.com/32318334/31543849-bfce4d4e-afdd-11e7-811a-1cfab6171752.png)

加载中-横屏：
![06 - 1-](https://user-images.githubusercontent.com/32318334/31543863-ccc3f2ec-afdd-11e7-872d-cb3e0fa66cbb.png)
