### ISSUE TITLE
iOS-下载：删除已下载的lesson出现闪退

### ISSUE THREAD

**Issue by itwangxiang** [bstcine/cine-tasklist#59]
bug描述：点击我的下载-在已下载页面点击已下载课程-在已下载课程目录页面左滑lesson点击删除出现闪退by mary
重现操作：使用老版本APP下载课程之后，在App Store下载最新APP之后，去我的下载中左滑删除lesson

**Comment by AaronLiDangkun** [comment]
#### 现象描述：
滑动删除已下载的 lesson，将一组的最后一个 lesson 滑动删除时，出现闪退。
- Reason:
```
在执行删除单个 lesson 时，app 存在两种删除手势，长按单元格和系统的左划删除。
因为系统的左划删除在点击或长按之后会失效，所以对左划删除手势处理不严密。
当删除最后一个 Lesson 时，会同时删除对应的 chapter。
在执行只一个 chapter 删除时，仅删除了组头，没有删除对应的 chapter 模型，
造成系统tableView冲突，出现闪退现象
```

- Solution:
