### ISSUE TITLE
iOS-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#60]
需求描述：
> * 当某一课程数据由后台更改之后，用户已经下载了此课程，需要确保用户下载的数据也能同步更新为最新的数据
> * 如果当前播放的lesson存在需要更新的数据，需要做到不能影响视频的正常播放。
> * 更新的数据需要精确到图片，不能一次性更新将整本书或整个lesson

逻辑流程图：
![2](https://user-images.githubusercontent.com/32290407/31534209-8fa249ae-b028-11e7-9bcb-c634a379e27c.png)

**Comment by YinZhenJob** [comment]
希望提供完整的流程图，以便梳理没有遗漏的case，以及要注意的case。

**Comment by joelin109** [comment]
2017-10-18上午给一个Deadline

**Comment by YinZhenJob** [comment]
周五做出来

**Comment by joelin109** [comment]
## 针对每个课程
- 需含有如下方法： getChangedMediaList

- 如果本地已经下载，与API的数据进行比较，需要消耗的时间是多少？

**Comment by YinZhenJob** [comment]
Solution:
1. 创建 BCNetwork 网络接触层、BCRequestPath 网络地址索引、BCRequestLogic 网络接触层，用于V2版网络数据的请求；
2. 创建三个类型Model：Course、Lesson、Media；
3. 创建 BCDBManager 用于管理本地下载信息数据（增删改查），并提供与旧有信息表格式的互相转化方法；
4. 拓展原有的 DownManager 增加下载个数的限制方法，拓展 BCDBManager 提供更新本地信息方法。

**Comment by joelin109** [comment]
Deadline: 2017-10-24

**Comment by YinZhenJob** [comment]
测试数据为：《动物农庄》全部 Lesson 下载，数据量为 1112 个 Media；
当前5S设备上比较数据 进行4次相同操作，平均耗时为：0.069 秒。

**Comment by YinZhenJob** [comment]
测试数据为：《动物农庄》全部 Lesson 下载，数据量为 1112 个 Media；
当前5S设备上比较数据 进行4次相同操作，平均耗时为：0.069 秒。

加载数据，耗时操作需要： 15秒

**Comment by YinZhenJob** [comment]
Final DeadLine: 2017-10 - 27

**Comment by YinZhenJob** [comment]
Solution Change:

1. 进入 课程 播放页面，读取本地该课程数据, 并随后发起网络请求获取最新课程目录数据；
2. 将最新课程目录 与 本地下载课程数据 做比较，得出需要更新的内容；
3. 将待更新的内容放入过滤器，决定是否更新此次课程；
4. 开启更新服务，下载完更新文件后，将新的文件关系更新到本地已下载课程数据中；
5. 在子线程中移除旧的文件（当前没有播放要移除的内容情况下）。

**Comment by YinZhenJob** [comment]
新增的码源文件：
[Network 文件夹下](https://gitee.com/shanen/cineeducation/tree/workTogether/CineEducation/CineEducation/Class/Network)
BCNetwork、BCRequestPath、BCRequestLogic；
[Update 文件夹下](https://gitee.com/shanen/cineeducation/tree/workTogether/CineEducation/CineEducation/Class/ModualClass/DownloadLogic/Update)
BCDBManager、BCUpdateManager；

主要方法：
BCUpdateManager 中 ：
+ static func getChangedMediaList(courseId: String)
+ fileprivate func updateMark(lMedia: BCPlayerMediaModel, parentModel: BCPlayerContentsLeafModel) -> BCPlayerMediaModel?
+ fileprivate func updateFilter(mediaList: [BCPlayerMediaModel], updateMediaList: @escaping () -> Void)

**Comment by MaryLinker** [comment]
1.增加或更改一个lesson里面的小tag里面的图片，出现闪退

**Comment by zhuyichun** [comment]
## 问题如下
- P1. 出现闪退
（1）更改lesson里面tag音频时间，重新点击学习广场进入该课程，提示有更新后闪退，进入我的下载课件内容并没有更改。
（2）如果一个lesson里面的一个tag里面有多张图片，对其中的图片增加或更改（在后台对课内容进行更改).重新点击学习广场进入该课程，提示有更新后闪退，进入我的下载课件内容并没有更改。

（3）后台删除lesson里面的一个tag，重新点击学习广场进入该课程，提示有更新后闪退，进入我的下载课件内容并没有更改。
（4）后台添加lesson里面的一个tag，重新点击学习广场进入该课程，提示有更新，下载列表内容已经更新，学习广场的播放界面需要再次刷新后显示该节点。

**Comment by YinZhenJob** [comment]
1. 问题一不能重现；
2. 更新模块非用户可操作，故不可以进行手动撤销；
3. 从本地下载入口点击 播放器界面出现，相关的程序逻辑没有在相应逻辑分支（本地），而是放在了通用的部分执行。

**Comment by zhuyichun** [comment]
# 下载本地的文件不能播放
- step1.下载lesson1，lesson2到本地
- step2.后台更改lesson1文件为试听
- step3.打开播放器播放lesson1一直显示加载中，在下载中打开lesson1 也一直显示加载中

**Comment by zhuyichun** [comment]
# 下载本地的文件不能更改chapter名称
- step1.下载chapter10/lesson19到本地
- step2.服务器更改Chapter10名称到Chapter10000
-step2.重新点击我的学习进入该课程后，到我的下载中查看仍然显示Chapter 10

# 下载本地的文件不能更改课程名称
操作同上下载本地的文件不能更改chapter名称

# 下载本地的文件不能更新下载列表
- step1.下载chapter10/lesson19到本地
- step2.服务器更改清空lesson19的数据内容保留空
-step2.重新点击我的学习进入该课程后，到我的下载中查看lesson19保留之前的下载文件

# 下载本地的课件不能清除
- step1.下载chapter10/lesson19到本地
- step2.服务器删除lesson19
-step2.重新点击我的学习进入该课程后，到我的下载中查看lesson19保留之前的下载文件
