### ISSUE TITLE
安卓-下载：当后台提供的Lesson对应资源发生改变，本地已下载的课程内容也应更新

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#61]
需求描述：
> * 当某一课程数据由后台更改之后，用户已经下载了此课程，需要确保用户下载的数据也能同步更新为最新的数据
> * 如果当前播放的lesson存在需要更新的数据，需要做到不能影响视频的正常播放。
> * 更新的数据需要精确到图片，不能一次性更新将整本书或整个lesson

逻辑流程图：
![2](https://user-images.githubusercontent.com/32290407/31534209-8fa249ae-b028-11e7-9bcb-c634a379e27c.png)

**Comment by itwangxiang** [comment]
- 数据低于 10 M，是指每一个课程的更新量，还是某个章节的更新量？
- 文件更新机制是什么？下载同时几个任务？下载速度怎么控制？
-

**Comment by joelin109** [comment]
## 针对每个课程
- 需含有如下方法： getChangedMediaList

- 如果本地已经下载，与API的数据进行比较，需要消耗的时间是多少？

**Comment by itwangxiang** [comment]
1. 判断当前课程是否存在更新任务
  - 存在更新任务，返回
  - 不存在更新任务，则请求已缓存章节的最新数据
2. 判断当前课程缓存数据是否最新
  - 没有更新，返回
  - 存在更新，则保存最新的数据
3. 下载更新数据

**Comment by itwangxiang** [comment]
1. loadNetMediaAndUpdateCacheMedia 获取网络数据并更新缓存数据
   > 获取 1048 个 media 缓存清单 ,耗时【 ≈ 350ms 】
   - getChangedMediaList 获取课程需要更新的缓存清单
      > 58 个 lesson,1048 个 media 1050 image ,耗时【 ≈ 650ms 】
      - getLessonChangedMediaMap 获取一个章节需要更新的缓存清单
         > 获取 一个lesson 下所有图片，耗时 【 ≈ 20ms】 
   - refreshUpdateData 将需要更新的清单保存到本地表
2. startUpdateTask 开始更新任务
3. upgradeCacheData 升级缓存数据表

**Comment by joelin109** [comment]
- 测试Case：
```
step1： pc-admin端， 调整某课程的Lesson相关Media数据
          - 比如：修改，删除，移动位置， 调整相应图片等
step2：移动端，显示需要更新的Media与图片数量
          - 测试通过后， 改提示需要隐藏（delete）
step3：等一会了， 关闭网络，查看本地是否有最新数据
```

**Comment by zhuyichun** [comment]
-对应数据操作
type1:调整某课程的Lesson相关Media数据
         step1:pc-admin端,管理员角色进入课内容Content表搜索到对应的Lesson

![Uploading image.png…]()
￼

**Comment by MaryLinker** [comment]
后台删除课程的一个lesson里面的一个tag之后，已下载的内容没有更新

**Comment by itwangxiang** [comment]
修复保存播放音频的位置记录时，如果该音频被删除时，缓存更新后无法播放的问题

**Comment by MaryLinker** [comment]
后台更改已下载的lesson图片，再次进入播放时没有更新

**Comment by itwangxiang** [comment]
课程数据问题

**Comment by MaryLinker** [comment]
托福口语精讲lesson2的第3个和第5个小节是视频课程，将两个视频替换之后，会跳过第3个下节和第5个小节直接播放下一个小节。之后再对其他内容进行修改，已下载的内容都不会更新

**Comment by itwangxiang** [comment]
优化的提示逻辑，用于测试
