### ISSUE TITLE
iOS-学习系统：手机处于静音模式时，播放课程也能够正常听见音频

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#63]
需求描述：
手机处于静音模式时，打开APP进入学习页面，点击课程进入课程播放界面，要求此时可以正常听见音频

**Comment by AaronLiDangkun** [comment]
#### 当前现象描述：
app 启动后，点击播放课程，将静音键置于静音状态，不能发出声音。
app 进入后台，再返回前台，此时不管静音键处于何种状态，都能正常发出声音。
- need:
```
app 正常启动后，不需要进入后台，只要点击播放课程，不论静音键处于何种状态，都需要正常发声。
```
- Solution:
```
在 app 启动后，直接激活后台托管多媒体播放
```
