### ISSUE TITLE
iOS-Code规范：迁移到项目的V2框架 - UI界面的列表清单

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#68]
先提供UI界面的列表清单

**Comment by YinZhenJob** [comment]
模块 | 层级 | 建议类名：V2 | 建议路径：V2 | 类名：V1 | 路径：V1
-- | -- | -- | -- | -- | --
商城界面 | 1 | BCStoreVC | ~/Store/BCStoreVC.swift |   |  
搜索界面 | 1 | BCSearchVC | ~/Search/BCSearchVC.swift |   |  
课程详情界面 | 2 | BCCourseVC | ~/Course/BCCourseVC.swift |   |  
结算中心界面 | 3 | BCPurchaseVC | ~/Money/Purchase/BCPurchaseVC.swift |   |  
善恩收银台界面 | 4 | BCPaymentVC | ~/Money/Payment/BCPaymentVC.swift |   |  
学习界面 | 1 | BCLearnVC | ~/Study/Learn/BCLearnVC.swift |   |  
视屏播放界面 | 2 | BCPlayerVC | ~/Study/Player/BCPlayerVC.swift |   |  
登录界面 | 1 | BCLoginVC | ~/Auth/Login/BCLoginVC.swift |   |  
帮助界面 | 2 | BCHelpVC | ~/Auth/Help/BCHelpVC.swift |   |  
服务协议界面 | 2 | BCServerProtocolVC | ~/Auth/Protocol/Server/BCServerProtocolVC.swift |   |  
隐私界面 | 2 | BCPrivacyProtocolVC | ~/Auth/Protocol/Privacy/BCPrivacyProtocolVC.swift |   |  
注册界面 | 2 | BCRegisterVC | ~/Auth/Register/BCRegisterVC.swift |   |  
重置密码界面 | 2 | BCResetKeyVC | ~/Auth/ResetKey/BCResetKeyVC.swift |   |  
国家选择界面 | 3 | BCCountryVC | ~/Auth/Country/BCCountryVC.swift |   |  
我的界面 | 1 | BCMineVC | ~/Center/Mine/BCMineVC.swift |   |  
我的信息界面 | 2 | BCMyInfoVC | ~/Money/MyInfo/BCMyInfoVC.swift |   |  
可用积分界面 | 2 | BCBonusVC | ~/Money/Bonus/BCBonusVC.swift |   |  
积分规则界面 | 3 | BCBonusRuleVC | ~/Center/Bonus/BCBonusRuleVC.swift |   |  
我的订单界面 | 2 | BCMyOrderVC | ~/Money/MyOrder/BCMyOrderVC.swift |   |  
订单详情界面 | 3 | BCOrderVC | ~/Money/Order/BCOrderVC.swift |   |  
我的优惠券界面 | 2 | BCMyCouponVC | ~/Money/MyCoupon/BCMyCouponVC.swift |   |  
添加优惠券界面 | 3 | BCAddCouponVC | ~/Money/AddCoupon/BCAddCouponVC.swift |   |  
我的下载界面 | 2 | BCMyDownloadVC | ~/Center/Download/BCMyDownloadVC.swift |   |  
课程播放目录界面 | 3 | BCCourseGuideVC | ~/Center/Download/CourseGuide/BCCourseGuideVC |   |  
关于我们界面 | 2 | BCAboutUsVC | ~/Center/About/BCAboutUsVC.swift |   |

**Comment by YinZhenJob** [comment]
模块 | 层级 | 建议类名：V2 | 建议路径：V2
-- | -- | -- | --
商城界面 | 1 | BCStoreVC | ~/Store/BCStoreVC.swift
搜索界面 | 1 | BCSearchVC | ~/Search/BCSearchVC.swift
课程详情界面 | 2 | BCCourseVC | ~/Course/BCCourseVC.swift
结算中心界面 | 3 | BCPurchaseVC | ~/Money/Purchase/BCPurchaseVC.swift
善恩收银台界面 | 4 | BCPaymentVC | ~/Money/Payment/BCPaymentVC.swift
学习界面 | 1 | BCLearnVC | ~/Study/Learn/BCLearnVC.swift
视屏播放界面 | 2 | BCPlayerVC | ~/Study/Player/BCPlayerVC.swift
登录界面 | 1 | BCLoginVC | ~/Auth/Login/BCLoginVC.swift
帮助界面 | 2 | BCHelpVC | ~/Auth/Help/BCHelpVC.swift
服务协议界面 | 2 | BCServerProtocolVC | ~/Auth/Protocol/Server/BCServerProtocolVC.swift
隐私界面 | 2 | BCPrivacyProtocolVC | ~/Auth/Protocol/Privacy/BCPrivacyProtocolVC.swift
注册界面 | 2 | BCRegisterVC | ~/Auth/Register/BCRegisterVC.swift
重置密码界面 | 2 | BCResetKeyVC | ~/Auth/ResetKey/BCResetKeyVC.swift
国家选择界面 | 3 | BCCountryVC | ~/Auth/Country/BCCountryVC.swift
我的界面 | 1 | BCMineVC | ~/Center/Mine/BCMineVC.swift
我的信息界面 | 2 | BCMyInfoVC | ~/Money/MyInfo/BCMyInfoVC.swift
可用积分界面 | 2 | BCBonusVC | ~/Money/Bonus/BCBonusVC.swift
积分规则界面 | 3 | BCBonusRuleVC | ~/Center/Bonus/BCBonusRuleVC.swift
我的订单界面 | 2 | BCMyOrderVC | ~/Money/MyOrder/BCMyOrderVC.swift
订单详情界面 | 3 | BCOrderVC | ~/Money/Order/BCOrderVC.swift
我的优惠券界面 | 2 | BCMyCouponVC | ~/Money/MyCoupon/BCMyCouponVC.swift
添加优惠券界面 | 3 | BCAddCouponVC | ~/Money/AddCoupon/BCAddCouponVC.swift
我的下载界面 | 2 | BCMyDownloadVC | ~/Center/Download/BCMyDownloadVC.swift
课程播放目录界面 | 3 | BCCourseGuideVC | ~/Center/Download/CourseGuide/BCCourseGuideVC
关于我们界面 | 2 | BCAboutUsVC | ~/Center/About/BCAboutUsVC.swift
  |   |   |

**Comment by YinZhenJob** [comment]
![Uploading UI List.jpg…]()

**Comment by YinZhenJob** [comment]
![ui list](https://user-images.githubusercontent.com/23608794/31546009-28ffb7f0-b054-11e7-86a4-254e87ac575e.jpg)

**Comment by joelin109** [comment]
## UI界面的列表

- 1级 - 学习
  -   [ ] 课程的Chapter目录 （ ？）
  - 课程播放页 （ ？）

<br>

- 1级 - 商城.搜索
- 1级 - 商城
  -  ..
  - ..

<br>

- 1级 - 我的.未登入
  -  注册
  - ..

- 1级 - 我的
  -  ..
  - ..

```
每个界面对应的V1的Viewcontrol 的名称、路径
```
