### ISSUE TITLE
api-商城：课程的搜索结果只能出现已上架的课程

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#7]

**Comment by iott** [comment]
搜索出来的课程是已上架但未显示分类的课程，课程维护时请注意关闭web、ios、Android显示。 @zhuyichun

**Comment by MaryLinker** [comment]
### 点击商城-课程搜索，输入搜索内容，结果只能显示已上架的课程
![_20170927111833](https://user-images.githubusercontent.com/32290407/30894346-dd7f5fdc-a375-11e7-8820-16a30c32becb.jpg)

**Comment by iott** [comment]
课程维护修改后，Android搜索结果正常ios因传参问题需更新版本解决

**Comment by iott** [comment]
/api/app/search
platform:平台标识[web:1,ios:2,android:3]

**Comment by limingLiuBaBa** [comment]
platform字段已修改.
