### ISSUE TITLE
后台-APP中积分规则显示内容变更

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#70]
位置：打开APP点击我的-可用积分-积分规则
需要更改的规则：4.学习完成后打卡“每次获得2个积分”改为“每次可随机获得积分”
需要增加的规则：分享APP每日可获得3个积分，可获得的总积分为实付金额的1%，小于10则计10积分
（具体的文字由@杨凯琪提供）
![image](https://user-images.githubusercontent.com/32290407/31536848-b5190e16-b032-11e7-86cb-619936d173c8.png)

**Comment by YangKaiqiCine** [comment]
4、学习完成后打卡：
可获得随机积分。
5、分享APP：
可获得1个积分
6、其它：原文字不变
