### ISSUE TITLE
iOS-商城：课程详情页不仅可以分享至朋友圈还可发送给朋友

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#71]
位置：打开APP点击商城-点击课程进入课程详情页-点击右上角的分享按钮
需求描述：现在点击分享按钮后只能分享至朋友圈，要求既可以分享至朋友圈也可分享给朋友

**Comment by AaronLiDangkun** [comment]
#### 解决方案：

- 1.点击分享按钮，判断用户是否安装微信
- 2.如果设备未安装微信，直接弹出二维码分享到朋友圈
- 3.如果设备已安装微信，弹出选择视图（包含朋友圈，和微信好友两个按钮），
    点击朋友圈，则分享到朋友圈；
    点击微信好友，则分享到聊天对话框

以上请知悉 @MaryLinker
