### ISSUE TITLE
iOS-个人设置：优惠券信息显示错误

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#74]
bug描述：
1.错误：点击我的-优惠券，刚点进去时“测试5”显示的信息是“未使用”，当点击“已使用”或“已过期”页面之后（前提是“已使用”或“已过期”页面内需要有内容），“测试5”显示的信息变成了“已过期”，可正常使用，返回至“我的”页面再次进入优惠券的“未使用页面又可恢复正常”。
正确：“测试5”显示的信息应该仍然显示为“未使用”

![image](https://user-images.githubusercontent.com/32290407/31593073-fe764cc6-b25e-11e7-920f-45e01bae0eb2.png)![image](https://user-images.githubusercontent.com/32290407/31593933-41f82618-b264-11e7-97c4-e2be967eeb17.png)

2.错误：在“已使用”或“已过期”页面点击添加正常未过期可使用的优惠券之后，所有“未使用”的优惠券都会显示在当前页面，返回“我的”或点击“未使用”页面之后，会显示正常。
正确：添加正常未过期可使用的优惠券之后，不应该显示在“已使用”或“已过期”页面，应根据添加的优惠券信息显示在正确的页面。
![image](https://user-images.githubusercontent.com/32290407/31593852-d4821b52-b263-11e7-9935-e777194c03e1.png)![image](https://user-images.githubusercontent.com/32290407/31593863-e1d211cc-b263-11e7-81ee-5a4196a61491.png)

**Comment by limingLiuBaBa** [comment]
两种显示bug已解决.
