### ISSUE TITLE
iOS-注册：注册手机号或邮箱账号在发送验证码时点击取消后不可进行编辑

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#75]
## 1. 取消`确认手机号` 的弹窗, 手机号码不能继续编辑
- Step1  `我的·（未登入)` -> `立即注册`
- Step2  输入 手机号码，点击 `下一步`
- Step3  屏幕会弹出 `确认手机号` 的弹窗，点击 `取消`
- Step4  不能进行编辑手机号码 （错误）
- 正确：应该都可以编辑

<br>

2.错误：使用电子邮箱进行注册，输入电子邮箱点击下一步弹出“发送验证码”的弹窗，点击取消后，电子邮箱不能进行编辑，接着点击“我要用手机号注册”后，不能输入手机号
正确：手机号码和邮箱账号应该都可以编辑

<br> 
3.错误：当注册手机号或邮箱账号输入为空时，点击下一步弹出提示“该手机号/邮箱账号已被注册”
正确：未填写手机号或邮箱账号时，下一步应设置为不可点击状态
4.点击“忘记密码”进到重置密码页面、点击“下一步”发送验证码到填写验证码页面、输入验证码到重设密码页面，在这三个页面上左滑，页面左上角的“返回”按钮会消失

**Comment by joelin109** [comment]
@MaryLinker Aaron目前主要工作在V2版app
