### ISSUE TITLE
iOS-学习系统：一个lesson里同时有视频和图片的课程中，视频无法播放画面，只有声音

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#76]
## 步骤：

-  S1.  点击`入学习广场`
-  S2.（已购买此课程）点击托福口语课程，进入托福口语课程的播放页
-  S3.  点击目录，左侧会弹出目录页
-  S4.  点击lesson 2, 播放lesson 2 的内容
-  S5.  当播放至第3个tag和第5个tag时，播放器的画面依旧是前一个tag的画面，音频正确，画面不正确

```
> * 重现频率：100%
> * 版本：（build1.1.6.0） & App Store上的1.1.3 
> * 备注：之前的版本也出现过这个问题，解决了之后在这次更新之后又出现了这个问题。
```

**Comment by limingLiuBaBa** [comment]
状态:已解决.
原因:历史上因其他问题做的数组越界条件判断,后其他问题解决.不过数组越界的条件判断还在,导致针对有视频的课件会一直走不隐藏图片视图层的条件分支.
