### ISSUE TITLE
pc: 端打卡功能

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#8]
1.点击课程播放界面右上角“结束本次学习，打卡”按钮之后，课程仍然继续播放，没有结束学习；
2.拖动进度条至一个lesson结束时，弹出打卡框后，课程在本lesson的最后一个小节从头播放；
3.在lesson的倒数第二个小节拖动进度条至结束会弹出打卡框。

**Comment by daweilv** [comment]
1. fixed
2. 浏览器特性，建议不直接拖放到最后，拖放到倒数一秒
3. 未能重现
