### ISSUE TITLE
iOS-商城：用户购买课程使用的账号是api_ios_buy,无法开通课程

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#81]
![image](https://user-images.githubusercontent.com/32290407/31702905-72e0cfa6-b40c-11e7-8777-99058f97a8ea.png)
![image](https://user-images.githubusercontent.com/32290407/31703471-3f4c7ade-b40f-11e7-95a8-a10bc54aaadc.png)

第一笔用户手机号13998660221

**Comment by joelin109** [comment]
## Solution:
- API
```
提供一个api， 至少包含4个字段：版本号，审核开始时间、结束时间，审核通道是否关闭
```

- iOS
```
判断是否内购的位置：点击“立即购买”的页面（课程详情页）
```

**Comment by AaronLiDangkun** [comment]
#### 用户在未知状况下，激活了审核状态，在未登录时购买课程，走通了未登录购买流程，客户所开通的课程不在设备上显示
- Reason:
```
  判断机制不够灵活，不是在客户点击购买时实时检测，而是在程序启动时一次性检测
```
- Solution:
```
  灵活判断审核状态，在每次购买课程时实时检查，保证审核状态明确性。
  增加新的 api，记录 app上架信息，实时检查是否正在审核
```

**Comment by joelin109** [comment]
- api
  http://apptest.bstcine.com/api/review/general/appInfo

```
{
    "token":"8xXHCySK",
    "sitecode": "cine.ios.iphone",
    "channel": "i5", 
    "locale": "zh_CN",
    "appver": "1.1.6",
    "data":{
    }
}
```
