### ISSUE TITLE
iOS-下载：下载多个lesson时，有些lesson一直处于读取状态，无法开始下载

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#83]
### P1：
- 点击`学习`，进入学习广场,  点击 `神奇书屋1...`
- 课程播放界面, 点击 `目录`- 点击 `Chapter1`
- 点击'Lesson2'下载,
- 无法下载 (问题）
```
1. 测试版：类似的问题，最近出现了很多次.
2. 正式版：没有出现类似的问题.
From Joe

1. 测试版： 无法重现；
2. 正式版：无法重现；
From  Zohar
```
<br>

### P2：
1.打开APP，点击学习，进入学习广场
2. 打开一个课程，进入课程播放界面
3.点击目录
4.点击多个lesson的下载按钮，下载多个lesson
bug描述：
进行第4步时，会出现有些lesson一直处于加载中的状态，不能进入下载

```
V1版本：暂不解决
```

**Comment by joelin109** [comment]
## Problem
- 学习-神奇书屋1-Lesson2，
- 点击下载， 无法下载
