### ISSUE TITLE
pc-H5: 词汇量测试设计

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#86]
需求描述：
1.入口
> 放在首页和我的学习页面

2.规则
>* 年级选择：学前，1-12年级，成人；设计中采用下拉框的形式进行选择
>* 年龄信息，设计中也采用下拉框的形式进行选择，且选择的是出生年份，选择范围为1947-2012年，但是年龄信息只做参考。
>* 区域信息，设计中也采用下拉框的形式进行选择，且选择的是省份级别（包含直辖市） - `J`。
>* 如果该用户已经做过测试，系统已经记录了该用户的年级和年龄信息，则在半年不再提醒用户更改年级信息。如果是成人用户，永不主动更新其年级信息。该信息同时同步更新到个人档案信息中。
>* 在测试开始前，需要有一个提示登录的界面，其中的文字为“系统检测到你没有登录，为了记录你的学习成长过程，强烈建议你登录系统后再进行测试”，下面显示两个按钮：“登录系统”，“先测一下看看”，点击“登录系统”按钮，登录后回到测试
>* 登录后，如果判断到用户没有登记过年级和年龄，则出现如下界面，在“请选择你的出生年份”文字上方，加上如下文字“为了保证本测试的学术参考价值，请补充如下个人信息”，其中的“下一步”按钮改为“开始词汇量测试”

2.词汇测试数据 
>* 系统在开始测试之前，从最低级到最高级（词汇等级分为0-1000【1级，入门】，1000-3000【2级，中学】，3000-5000【3级，大学四级】，5000-8000【4级，托福】，8000-12000【5级，SAT】，12000-2500【6级】）的每个等级中随机抽取30个单词，生成一整套完整的测试题，让学生做词义的多项选择；
> * 测试题库词库用excel导入，excel表格的格式先确定好
> * 词库可以维护所属词汇量区间，词汇量区间可以定义。词汇量区间单独用表来维护，词汇库表中的所属词汇量区间属性值只存储词汇量区间的编码
> * 错误选项需要是同性词且是固定词
> * 点击开始测试后，系统不做任何预判，都是让其从最低等级开始做起，每一题都必须选择才可进入下一题。

3.词汇量计算 
> * 词汇量S=（1000×S1 + 2000×S2 + 2000×S3 + 3000×S4 + 4000xS5 + 13000xS6）/30。
> * 每个等级上的得分Sn=正确的个数 - 错误的个数/3
> * 当Sn<3时，测试不进入下一等级，测试终止，下一测试等级的词汇视作本测试者不掌握，词汇量S只累加到当前Sn，当前级别的词汇量还是按照Sn=正确的个数 - 错误的个数/3计算
> * 每一道题都有固定的测试时间，如果超过了测试时间，直接进入下一题，超时未答的题记为答错（具体时间未定）

4.生成测试报告 
> * 词汇测试完成后，需要生成测试报告。报告的内容包含：测试者姓名、年龄、测试时间、词汇量、词汇量在所有测试者的百分比排名、词汇量在同龄测试者中的百分比排名和适合阅读书目推荐。
> * 词汇量在同龄测试者中的百分比排名需要用表来维护，根据不同的年级年龄对应相应的词汇区间
> * 系统要记录用户的测试记录明细数据，也就是，每道题的答对答错情况用于事后分析。
> * _****_需要有一个用于配置每一个年级对应的词汇量区间的配置表，其中包含字段：年级，词汇量下限，词汇量上限，比如，某用户是3年级学生，3年级的配置词汇量标准的下限为500，上限为3000，其测试词汇量结果为800，则给出信息为“你的词汇量超越了60%的同年级同学！”，如果不到500，则给出“跟同年级同学相比，你需要努力加油了！”，如果超过3000，则给出“你在同年级同学中属于10%的佼佼者，继续努力保持！”，当然，这个上限我们会定得比较高，让一般人很难触及。_**由于缺乏有说服力的数据支撑，该需求暂缓**_
> * 根据词汇量测试结果，给出我们推荐的书单/课程。也就是需要有一个配置表，配置好词汇量和课程的对应关系。

<br>

5.步骤 
已登录未填写年级、年龄、区域信息：

> * （1）在首页或我的学习页面点击词汇水平测试进入词汇测试页面
> * （2）在词汇测试页面选择年级、年龄、区域信息，点击开始测试
> * （3）进入测试，选择答案后自动进入下一题，且不对答案的正确与否进行提示，直到测试终止后进入测试报告页面，测试结束

已登录已填写年级、年龄、区域信息：

> * （1）在首页或我的学习页面点击词汇水平测试进入词汇测试页面
> * （2）点击开始测试
> * （3）进入测试，选择答案后自动进入下一题，且不对答案的正确与否进行提示，直到测试终止后进入测试报告页面，测试结束

未登录：

> * （1）在首页或我的学习页面点击词汇水平测试
> * （2）点击登陆系统——已登录未填写和已填写年级、年龄、区域信息两种情况

<br>
<br>

交互图点击链接 https://modao.cc/app/XBLlWCqMdq8lUUgWfjKX9CeX0Xa0YFN 进行查看
```
这不是真正的UI交互图， 参考Comment “词汇量测试UI”- Joe
```

**Comment by daweilv** [comment]
* 建议年龄以输入框的形式
* 年级的下拉框值有哪些
> 一年级~六年级，初一~初三……，建议业务提供合适的年级枚举值

**Comment by daweilv** [comment]
每次测试的单词总数受被测人的单词量影响无法提前预知，测试进度的基数不固定，进度无法以一个合适的百分比显示出来。

**Comment by joelin109** [comment]
- 提供Demo（使用数据库的数据）
DeadLine：2017-11-03

**Comment by joelin109** [comment]
## Question
- q1:
- q2:

**Comment by YangKaiqiCine** [comment]
词汇量算法更正：S=（1000×S1 + 2000×S2 + 2000×S3 + 3000×S4 + 4000xS5 + 13000xS6）/30，其中为每一级的取样值

**Comment by YangKaiqiCine** [comment]
1、年级，用1-12来表示
2、就定为不显示总进度条，在开始时用一句文字说明即可：“本测试大约需要3-15分钟不等，具体测试时间跟词汇量和答题速度有关”

**Comment by daweilv** [comment]
请业务提供如下数据：

1. 所有`年级`对应的平均词汇量、优秀词汇量
`（学龄前,一年级,二年级,三年级,四年级,五年级,六年级,七年级,八年级,九年级,十年级,十一年级,十二年级,成人）`

2. 目前上线的所有课程对应的单词区间，最低词汇量、最高词汇量
eg. 动物农庄 1500~3000

@joelin109 @YangKaiqiCine

**Comment by MaryLinker** [comment]
更新是否登录和是否记录过年级年龄信息两种情况下的处理：
1、在测试开始前，需要有一个提示登录的界面，其中的文字为“系统检测到你没有登录，为了记录你的学习成长过程，强烈建议你登录系统后再进行测试”，下面显示两个按钮：“登录系统”，“先测一下看看”，点击“登录系统”按钮，登录后回到测试
2、登录后，如果判断到用户没有登记过年级和年龄，则出现如下界面，在“请选择你的出生年份”文字上方，加上如下文字“为了保证本测试的学术参考价值，请补充如下个人信息”，其中的“下一步”按钮改为“开始词汇量测试”

**Comment by Anawangqi** [comment]
词汇量测试UI：
## **0 是否登录判断**
![01- -0](https://user-images.githubusercontent.com/32318334/32824805-0ca06bd2-c9a8-11e7-9231-536d11e9732c.png)

## **1 已登录已填个人信息**
![01- -1 -](https://user-images.githubusercontent.com/32318334/32824823-1ce46f20-c9a8-11e7-9fc5-05e86b92add4.png)

## **2 已登录-未填个人信息**
![01- -2 -0](https://user-images.githubusercontent.com/32318334/32824806-0ce1a318-c9a8-11e7-85df-26627bdad08d.png)

## **2.1 已登录-选择出生年份**
![01- -2 -1](https://user-images.githubusercontent.com/32318334/32824807-0d1fa320-c9a8-11e7-9d49-ced85d89fcd8.png)

## **2.2 已登录-选择年级**
![01- -2 -2](https://user-images.githubusercontent.com/32318334/32824819-1a5a8b18-c9a8-11e7-9e9a-8ce70b22dc08.png)

## **2.3 未登录-选择所在地区**
![01- -2 -3](https://user-images.githubusercontent.com/32318334/32824824-1d384118-c9a8-11e7-8a27-7ba1486840b5.png)

## **3 选择答案**
![01- -4](https://user-images.githubusercontent.com/32318334/32824825-1dae522c-c9a8-11e7-9546-a25340e75333.png)

## **4 测试报告**
![01- -5](https://user-images.githubusercontent.com/32318334/32824827-1f78dd34-c9a8-11e7-8a79-9f0d9cee3839.png)

**Comment by daweilv** [comment]
更新Deadline: 20171121

**Comment by daweilv** [comment]
更新Deadline: 2017-11-22

**Comment by YangKaiqiCine** [comment]
在测试过程中，不显示任何“你的词汇量已经超过了大部分同年级同学”等字眼。
只在某个词汇区间的测试完成后，显示如下文字：“你已经完成了1000-2000区间的词汇测试，现在进入2000-3000区间的词汇测试”，“你已经完成了3000-4000区间的词汇测试，现在进入4000-5000区间的词汇测试”

**Comment by daweilv** [comment]
这个界面中，需要加上一个逻辑判断，年级和年龄的关系，年级值（学前为0，一年级=1，二年级=2.。。）所属区间应该在：【当前年份 - 用户输入的年份 - 8，当前年份 - 用户输入年份 - 3】之间，如果不再该区间，那么提示用户“年份和年级是否填写正确？”，如果“是”，那么进入下一步，如果是“否”，那么停留在本界面

【当前年份 - 用户输入的年份 - 8，当前年份 - 用户输入年份 - 3】，比如用户输入的出生年份是2010，那么正常的年级应该是2017 - 2010 - 6 = 1年级，假设提前上学，也最多往前推2年，再晚上学，也最多往后推3年，如果不在本区间，很可能是填错了

--- by Shaun

**Comment by daweilv** [comment]
年级和年龄的关系算法更新
原算法的判定条件应为用户输入的年级值 grade >=1 && grade <=12的时候。
1. 当用户输入grade <= 0时，grade 应小于【当前年份 - 用户输入年份 - 3】，也就是grade大于或等于【当前年份 - 用户输入年份 - 3】的时候应给予提示框确认。
2. 当用户输入grade>=13时，grade 应大于【当前年份 - 用户输入年份 - 8】，也就是grade小于或等于【当前年份 - 用户输入年份 - 8】的时候应给予提示框确认。

**Comment by joelin109** [comment]
## 推荐课程
### 当测试结果分数不在设置的区间内
- < min, 显示min最小的那一批课程
- > max, 显示max最大的那一批课程

**Comment by YangKaiqiCine** [comment]
1、提示信息改为“本测试是严谨的学术型词汇量测试，耗时比一般的词汇量测试更长，大约需要5-10分钟。在本测试中，您将得不到任何“对错”的提示。在测试结束后，您将获得详细的词汇量报告”
2、每一个级别的题量（现在是每个级别30个），这个要做成可配置。
3、每一个级别净正确题数低于3题就不进入下一级别。这个3题也要做成可配置。
4、每一个级别上，如果测试者满足一定的条件，系统可以认为测试者这个级别的单词完全掌握。这个条件可以是：但测试者开始一个级别的测试后，在最初的n题全部正确，这个n也要可配置。先把n取值8
5、如果用户在中途退出，不记录其测试明细
6、在测试完成后，给出一个“查看测试详情”的链接，点击后，显示其测试的所有词汇和对错。

**Comment by daweilv** [comment]
1947做成“当前年份减去70”，2012做成“当前年份减去5”，还是做成自适应的
---by Shaun

**Comment by YangKaiqiCine** [comment]
测试报告格式：
测试人账号：     年龄：     年级：      所在地区：     测试时间：       词汇量：
各种考试词汇量要求参考数据：
中考：1500；高考：3500；大学4级：4500；大学6级：6000，托福8000；SAT：10000以上。

全国5年级词汇量均值：（其中，“五年级”从用户所填数据中获取）
在全国5年级中的词汇量排位：图例
上海5年级词汇量均值：（其中，“上海”和“五年级”从用户所填数据中获取）
上海5年级的词汇量排位：图例

基于你的词汇量和年龄，我们向你推荐下列英文原版书。

**Comment by joelin109** [comment]
## 推荐课程规则 - 最多只显示3本
- 如果符合条件的超过3本， 选择min_vocab最大的3本
- 如果符合条件为0，且超过max_vocab，选择max_vocab最大那一批的3本
- 如果符合条件为0，且小于min_vocab，选择min_vocab最小那一批的3本

**Comment by MaryLinker** [comment]
新增需求：
词汇测试过程中，如果离开了词汇测试页面，需要暂停测试，再次回到测试页面时，继续测试

**Comment by YangKaiqiCine** [comment]
![image](https://user-images.githubusercontent.com/32290617/33541461-3640ace2-d90a-11e7-8a35-d2cef764e7c9.png)

**Comment by zhuyichun** [comment]
[https://github.com/bstcine/cine-tasklist/issues/209](url)
