### ISSUE TITLE
PC-学习系统：音频每次都是从lesson的第一个tag开始播放，而图片显示的是上次学习的位置

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#88]
步骤：
1.登录官网，点击我的学习首页
2.点击任意一门课程，进入课程学习播放页
3.点击任意lesson假设lesson1,学习几个tag之后，点击lesson2学习一段时间后，再点击lesson1,之后：
错误：音频仍然从lesson1的第一个tag开始播放，而图片显示的是上次学习完的位置
正确：音频和图片均需要从上次学习完的位置开始播放

**Comment by daweilv** [comment]
* Reason
初始化播放器时默认播放第一个片段，如果检测到有历史记录则中断播放，播放历史记录的片段，两次音频资源切换间隔很短，导致第一个音频还没有播放的时候就被中断，浏览器认为是异常，被 throw 出来，第二次播放被中端。

* Solution
修改了初始化播放器逻辑，优先检查是否有历史记录，如果有，则直接播放历史记录的片段，如果没有，则默认播放第一个，整个过程播放器只播放一次，不会被中断报错。
