### ISSUE TITLE
iOS：课程播放目录

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#9]
《神奇书屋6》课程播放目录显示发生错误，手机型号：iPhone6s  手机版本：iOS11
![_20170927110559](https://user-images.githubusercontent.com/32290407/30894087-257ac4e0-a374-11e7-9f5a-c98bc77ef56f.jpg)

**Comment by AaronLiDangkun** [comment]
此问题已解决，https://fir.im/cineEducation
