### ISSUE TITLE
Android-Code调整：移动端使用统一的Model定义，然后代码check in `Gitee`

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#90]
## Model
- Content
  - BCCategoryModel
  - BCCoursePackageModel
  - BCCourseModel
  - BCChapterModel
  - BCLessonModel
  - BCLessonSubMediaModel

<br>

- User
  - BCUserModel

<br>

- Order
  - BCOrderModel

<br>

- Discount
  - BCCouponModel
  - BCIntegralModel

```
调整后代码check in
https://gitee.com/bstcine/cine.android
```

**Comment by itwangxiang** [comment]
> deadline: 2017-11-1

**Comment by joelin109** [comment]
2017-11-10前，代码check in
https://gitee.com/bstcine/cine.android
