### ISSUE TITLE
PC-后台-商城-订单管理：手动开通课程课程权限页面新增实付总金额功能

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#91]
需求描述：
>* 在手动开通课程课程权限页面的备注上方添加实付订单总金额一栏，用以计算手动开通多门课程时，每门课程的金额；
>* 仅当支付类型为线下支付时，才可对实付订单总金额进行编辑；
>* 该课程的金额=实付订单总金额*该课程的原价/总开通课程的实际总金额   （计算结果取整数） 
>* 计算出该课程的金额后，系统将自动设置该课程的实付金额

![image](https://user-images.githubusercontent.com/32290407/31921032-736a0a54-b89f-11e7-96ca-862331ad8634.png)

**Comment by daweilv** [comment]
done
