### ISSUE TITLE
安卓-学习系统：课程播放界面的缓冲图更改

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#93]
1、这个APP的数据调入时的等待背景，“波士顿善恩教育”--->“善恩英语”，英文原著精读引领者--->“在线英语阅读课程专家”
2、所有涉及“Leading Provider of Online Reading Courses”的地方，都修改成“The Premier Online Reading Courses”
![image](https://user-images.githubusercontent.com/32290407/31475818-88d9cbb8-af35-11e7-8785-cf31bde9c742.png)

**Comment by MaryLinker** [comment]
UI- #56iOS-学习系统：课程播放界面的缓冲图更改

**Comment by itwangxiang** [comment]
过旧

**Comment by MaryLinker** [comment]
课程播放界面的缓冲图未更改

**Comment by itwangxiang** [comment]
新的缓冲图： 不同设备会将缓冲图片拉伸
> 建议：采用背景色+LOGO
