### ISSUE TITLE
安卓-下载：当账号被登录后，第一次点击播放已下载的课程只有声音，没有图片

### ISSUE THREAD

**Issue by MaryLinker** [bstcine/cine-tasklist#97]
当账号被其他设备登录后，
1.从我的页面进入我的下载页面
2.点击播放已下载课程进入播放界面
3.显示账号被登录，并出现了重新加载的图片，音频仍然正常播放（错误）
正确的应该是：显示账号被登录后，不允许播放课程
![image](https://user-images.githubusercontent.com/32290407/31982343-0ca3d934-b98b-11e7-973c-d762c7eebf62.png)

**Comment by itwangxiang** [comment]
##Solution:
- 当token失效时，退出播放界面
- 进入播放前，判断是否登录
