### ISSUE TITLE
PC:  双11活动一元购-某些课程分享拿优惠券

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#98]
双十一苏斯一元购活动

活动内容：从11月1日起每日有一本苏斯做活动，用户分享后就可以1元购买当日参加活动的这本书。

活动时间：11月1日至11月11日
每日参加活动的课程：
《The cat   in The Hat》原版讲读 | 11/1 11:11-11/2   11:11
《The Fox in The Socks》原版讲读 | 11/2 11:11-11/3 11:11
《Mr. Brown Can Moo, Can You?》原版讲读 | 11/3 11:11-11/4 11:11
《Hop On Pop》原版讲读 | 11/4 11:11-11/5 11:11
《The Shape of Me and Other Stuff》原版讲读 | 11/5 11:11-11/6 11:11
《Oh，the Thinks You Can Think!》原版讲读 | 11/6 11:11-11/7 11:11
《Dr. Seuss's ABC》原版讲读 | 11/7 11:11-11/8 11:11
《The Foot Book》原版讲读 | 11/8 11:11-11/9 11:11
《One Fish Two Fish Red Fish Blue Fish》原版讲读 | 11/9 11:11-11/10   11:11
《There's a Wocket in my Pocket!》原版讲读 | 11/10 11:11-11/11   11:11
《Ten Apples Up On Top!》原版讲读 | 11/11 11:11-11/12   11:11

活动规则：转发该门课程后可1元购买该课程。

注：课程因为会被转发，所以课程标题需修改为：“【1元购】苏斯XX原版讲读课程....”

**Comment by daweilv** [comment]
前提：业务侧要求尽快提供功能，最好在 11.1 前提供，最迟 11.6 前，故本次开发以快速实现为前提，不在细节上深究。

1. 只在微信浏览器内进行分享

2. t_lesson 增加 分享后是否能领取优惠券 字段，is_share_get_coupon [0:可以,1:不可以]

3. 增加 /api/web/sharegetcoupon 接口，成功分享后给当前用户赠送优惠券，前台弹出原生提示框通知（不做设计）+ 短信通知

> 接口根据 lesson_id 查询是否能领取优惠券，新建一张只可用于该课程的27元优惠券，直接指定给当前分享用户，领券时起，24小时有效

4. 活动课程微信分享的分享参数(ShareParam)定制，微信公众号的在发文后将微信文章地址、标题维护在系统中，图标可使用该课程图标或定制均可，微信文章地址为需登录的详情页地址，类似 http://www.bstcine.com/login?go=http%3A%2F%2Fwww.bstcine.com%2Flesson%2Fd011503986876187c8SNfu2mnm

5. 该活动课程的课程详情页在分享的时候分享链接替换为对应的微信文章地址

6. 维护人员维护当天活动课程，将活动图片+公告，课程分享参数维护进系统

**Comment by daweilv** [comment]
优惠券方案废除，改为分享后才能购买的方案

1. t_lesson 增加 是否为分享后购买 字段 is_share_buy [0:否,1:是]

2. 课程详情页根据 is_share_buy 隐藏显示立即购买

3. 活动课程微信分享的分享参数(ShareParam)定制，微信公众号的在发文后将微信文章地址、标题维护在系统中，图标可使用该课程图标或定制均可，微信文章地址为需登录的详情页地址，类似 http://www.bstcine.com/login?go=http%3A%2F%2Fwww.bstcine.com%2Flesson%2Fd011503986876187c8SNfu2mnm

4. 该活动课程的课程详情页在分享的时候分享链接替换为对应的微信文章地址

**Comment by daweilv** [comment]
modify
分享课程在pc端的二维码由原来的活动文章改为本课程详情页地址
