### ISSUE TITLE
API: 双11活动 - 新用户满3500送pad&老用户1500送pad

### ISSUE THREAD

**Issue by joelin109** [bstcine/cine-tasklist#99]
### 双十一送善恩学习机活动：

活动起止日期：10月27日新概念上架起为活动开始时间，11月11日为活动结束时间
善恩学习机上架时间：11月8日
善恩学习机定价：880元

活动规则：
1. 对于活动前10月27日前购买未满3500元的用户，需要在活动期间另外购买满3500元，可以送善恩学习机
2. 对于活动前10月27日前已消费满3500元的用户，需要在活动期间另外购买满1500元，即可赠善恩学习机

赠送实现方式——优惠券形式：
1. 从11月9日至11月12日每日固定时间（如上午9点30）在后台数据中查找符合赠送要求的用户，并自动在账户中添加一个880元的优惠券（仅供购买善恩学习机），并给用户发送邮件或者短信通知。
2. 反馈赠送优惠券的用户列表
3. 对于已经发送过优惠券的用户不再重复发送优惠券（即每个用户仅有一次机会）。
4. 优惠券有效期：截止为11月18日晚24点

**Comment by daweilv** [comment]
done
